### ISSUE TITLE
python -m pymobiledevice3 remote start-tunnel showing error Device Not Connected

### ISSUE THREAD

**Issue by Rayray1099** [doronz88/pymobiledevice3#1006]
**Test environment**
- Windows 11 23H2
- iPad Pro 4th Generation

**Describe the bug**
`python -m pymobiledevice3 remote start-tunnel` cannot connect to the device, but running `python -m pymobiledevice3 usbmux list` shows the connected device:
```json
[
    {
        "BuildVersion": "21F79",
        "ConnectionType": "USB",
        "DeviceClass": "iPad",
        "DeviceName": "Pro",
        "Identifier": "00008112-000558EC3668A01E",
        "ProductType": "iPad14,3",
        "ProductVersion": "17.5",
        "UniqueDeviceID": "00008112-000558EC3668A01E"
    }
]
```
To Reproduce

1.Open 'cmd'.
2.Run the command python -m pymobiledevice3 remote start-tunnel.
3.Observe the error: main__[24152] ERROR Device is not connected.
**Expected behavior**
The tunnel should start successfully.

**Logs**
```
D:\FDM Downloads\iOS17-JIT-WIN-main\iOS17-JIT-WIN-main>python -m pymobiledevice3 usbmux list
[
    {
        "BuildVersion": "21F79",
        "ConnectionType": "USB",
        "DeviceClass": "iPad",
        "DeviceName": "Pro",
        "Identifier": "00008112-000558EC3668A01E",
        "ProductType": "iPad14,3",
        "ProductVersion": "17.5",
        "UniqueDeviceID": "00008112-000558EC3668A01E"
    }
]

D:\FDM Downloads\iOS17-JIT-WIN-main\iOS17-JIT-WIN-main>python -m pymobiledevice3 remote start-tunnel
2024-05-19 10:32:58 LAPTOP-73MT3CPQ __main__[24152] ERROR Device is not connected
```
**For community**
⬇️ Please click the 👍 reaction instead of leaving a +1 or 👍 comment

**Comment by doronz88** [comment]
Please read project's documentation before posting. Your correct command would be:
```shell
python -m pymobiledevice3 lockdown start-tunnel
```

**Comment by Rayray1099** [comment]
Sorry but it is showing this error
````
C:\Windows\System32>python -m pymobiledevice3 lockdown start-tunnel
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\lib\site-packages\pymobiledevice3\__main__.py", line 167, in <module>
    main()
  File "C:\Python310\lib\site-packages\pymobiledevice3\__main__.py", line 100, in main
    cli()
  File "C:\Python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Python310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Python310\lib\site-packages\pymobiledevice3\cli\cli_common.py", line 146, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "C:\Python310\lib\site-packages\pymobiledevice3\cli\cli_common.py", line 120, in wrapper
    func(*args, **kwargs)
  File "C:\Python310\lib\site-packages\pymobiledevice3\cli\lockdown.py", line 160, in cli_start_tunnel
    asyncio.run(tunnel_task(service, script_mode=script_mode, secrets=None, protocol=TunnelProtocol.TCP), debug=True)
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Python310\lib\site-packages\pymobiledevice3\cli\remote.py", line 117, in tunnel_task
    async with start_tunnel(
  File "C:\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "C:\Python310\lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 994, in start_tunnel
    async with protocol_handler.start_tcp_tunnel() as service:
  File "C:\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "C:\Python310\lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 908, in start_tcp_tunnel
    tunnel.start_tunnel(handshake_response['clientParameters']['address'],
  File "C:\Python310\lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 295, in start_tunnel
    super().start_tunnel(address, mtu)
  File "C:\Python310\lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 177, in start_tunnel
    self.tun = TunTapDevice()
  File "C:\Python310\lib\site-packages\pytun_pmd3\wintun.py", line 206, in __init__
    raise PyWinTunException(f"Failed to create adapter. Last error: {last_error.value}")
pytun_pmd3.exceptions.PyWinTunException: Failed to create adapter. Last error: 0
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x000001D034F89D80>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\sslproto.py", line 321, in __del__
  File "C:\Python310\lib\asyncio\sslproto.py", line 316, in close
  File "C:\Python310\lib\asyncio\sslproto.py", line 599, in _start_shutdown
  File "C:\Python310\lib\asyncio\sslproto.py", line 604, in _write_appdata
  File "C:\Python310\lib\asyncio\sslproto.py", line 712, in _process_write_backlog
  File "C:\Python310\lib\asyncio\sslproto.py", line 726, in _fatal_error
  File "C:\Python310\lib\asyncio\proactor_events.py", line 152, in _force_close
  File "C:\Python310\lib\asyncio\base_events.py", line 753, in call_soon
  File "C:\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
````

**Comment by doronz88** [comment]
Looks like its not running in a privelged shell

**Comment by Rayray1099** [comment]
How to use privelged shell for iOS 17?

**Comment by doronz88** [comment]
u need an admin shell on windows to execute this command.
Also, if you still cannot start it perhaps your windows workstation doesn't have the wintun drivers. You can install them from:

https://www.wintun.net/

**Comment by doronz88** [comment]
You also may install them from here:
https://staging.openvpn.net/openvpn2/

**Comment by Rayray1099** [comment]
oh okay thanks

**Comment by Rayray1099** [comment]
like I am wondering what I can do with the binaries lol

**Comment by Rayray1099** [comment]
Still getting the same error :(
Btw my iPadOS is 17.5

**Comment by Rayray1099** [comment]
Are there any fix that I can do?

**Comment by doronz88** [comment]
Please open this is another issue detailaing what happens when you execute the correct command - though currently I'm not able to reproduce, but maybe someone will know this
