### ISSUE TITLE
USBMUX LIST Bug on windows 

### ISSUE THREAD

**Issue by omggodlike123** [doronz88/pymobiledevice3#1040]
**Test environment**
- Host OS version. Windows 10
- Target device model and iOS version. ios 17.5

**Describe the bug**
when i use pymobiledevice3 usbmux list on windows, it has a chance to get below bugs

**To Reproduce**
1. connect iphone ios 17 to windows pc 
2. pymobiledevice3 usbmux list 
3. getting deviceVersion error 

**Logs**
error2:exit status 1
Traceback (most recent call last):
  File "pymobiledevice3\__main__.py", line 156, in <module>
  File "pymobiledevice3\__main__.py", line 98, in main
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1688, in invoke
  File "click\core.py", line 1688, in invoke
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "pymobiledevice3\cli\usbmux.py", line 65, in usbmux_list
  File "pymobiledevice3\lockdown.py", line 645, in create_using_usbmux
  File "pymobiledevice3\service_connection.py", line 92, in create_using_usbmux
  File "pymobiledevice3\usbmux.py", line 88, in connect
  File "pymobiledevice3\usbmux.py", line 226, in connect
  File "pymobiledevice3\usbmux.py", line 384, in _connect
  File "pymobiledevice3\usbmux.py", line 407, in _send_receive
  File "pymobiledevice3\usbmux.py", line 247, in _raise_mux_exception
pymobiledevice3.exceptions.BadDevError: got an error message: {'MessageType': 'Result', 'Number': 2}
[9600] Failed to execute script '__main__' due to unhandled exception!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by omggodlike123** [comment]
@doronz88 @davesc63

**Comment by omggodlike123** [comment]
usbmux list works perfectly on mac. only windows have this problem

**Comment by doronz88** [comment]
Sounds like a bug in your iTunes. What would you expect pymobile to do?

**Comment by omggodlike123** [comment]
> Sounds like a bug in your iTunes. What would you expect pymobile to do?

i did not install itunes on my windows. but i already installed apple usb driver using usbaapl64.inf

**Comment by doronz88** [comment]
Or the iTunes software

**Comment by AnNEDoMini** [comment]
> > Sounds like a bug in your iTunes. What would you expect pymobile to do?
> 
> i did not install itunes on my windows. but i already installed apple usb driver using usbaapl64.inf

drivers are not enough. You need "Apple Mobile Device Service" which is installed with iTunes. you can download iTunes isntallator, and extract "AppleMobileDeviceService,msi" from it with winrar

**Comment by omggodlike123** [comment]
> > > Sounds like a bug in your iTunes. What would you expect pymobile to do?
> > 
> > 
> > i did not install itunes on my windows. but i already installed apple usb driver using usbaapl64.inf
> 
> drivers are not enough. You need "Apple Mobile Device Service" which is installed with iTunes. you can download iTunes isntallator, and extract "AppleMobileDeviceService,msi" from it with winrar

only see apple mobile device support.exe from itunes

**Comment by AnNEDoMini** [comment]
> > > > Sounds like a bug in your iTunes. What would you expect pymobile to do?
> > > 
> > > 
> > > i did not install itunes on my windows. but i already installed apple usb driver using usbaapl64.inf
> > 
> > 
> > drivers are not enough. You need "Apple Mobile Device Service" which is installed with iTunes. you can download iTunes isntallator, and extract "AppleMobileDeviceService,msi" from it with winrar
> 
> only see apple mobile device support.exe from itunes

Sry, exact file name is "AppleMobileDeviceSupport64.msi"

**Comment by doronz88** [comment]
Closing — this requires the Apple Mobile Device Service (installed with iTunes) on Windows; not a pymobiledevice3 bug.
