### ISSUE TITLE
Meeting "[Errno 32] Broken pipe" while killing apps

### ISSUE THREAD

**Issue by zyonbao** [doronz88/pymobiledevice3#1061]
**Test environment**
- MacOS 13.6.
- iOS 15.3.1

**Describe the bug**
While repeatly operation kill/restart app through pymobiledevice3, I got the broken pipe error. 

**To Reproduce**
I have a script to restart/kill app at regular times every day. Broken pipe error may occurs sometimes.

**Expected behavior**
Should not occur broken pipe error, or there is a way to recover the pipe? 

**Logs**
Here is the traceback:
[Errno 32] Broken pipe Traceback (most recent call last):
  File "/Users/ZaynBao/SourceCode/pandsta/package_installer/installer_tools/ios_install_package.py", line 172, in relaunch
    device_t.kill_app_by_bundle_id(*set(to_kill_bundle_ids))
  File "/Users/zyon/ios_package_install/main.py", line 352, in kill_app_by_bundle_id
    return self._kill_app_by_bundle_id(*bundle_id)
  File "/Users/zyon/ios_package_install/main.py", line 37, in wrapper
    return fn(*args, **kwargs)
  File "/Users/zyon/ios_package_install/main.py", line 322, in _kill_app_by_bundle_id
    with DvtSecureSocketProxyService(lockdown=self.lockdown_service) as dvt:
  File "/Users/zaynbao/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/services/remote_server.py", line 492, in __enter__
    self.perform_handshake()
  File "/Users/zaynbao/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/services/remote_server.py", line 386, in perform_handshake
    self.send_message(0, '_notifyOfPublishedCapabilities:', args, expects_reply=False)
  File "/Users/zaynbao/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/services/remote_server.py", line 432, in send_message
    self.service.sendall(msg)
  File "/Users/zaynbao/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/service_connection.py", line 118, in sendall
    self.socket.sendall(data)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1173, in send
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

**Additional context**

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Please submit a reproducable example

**Comment by zyonbao** [comment]
@doronz88 I use pymobiledevice3 as the remote control for my iOS device, install/uninstall/kill apps everyday, and it appears  in 1 month after I setup the device ready (trust computer, load images, etc.). Sorry for that I can not privide specific steps because I just use the tool normally, and it is be found while I operate install/kill/uninstall apps...

**Comment by doronz88** [comment]
I'm sorry but have not encountered this behavior ever so cannot reproduce.
Feel free to submit a PR to solve it

**Comment by doronz88** [comment]
Closing due to inactivity — no reproduction was provided and the broken-pipe error was not reproducible. Reopen with steps if it persists.
