### ISSUE TITLE
ValueError when using pcap service on Windows

### ISSUE THREAD

**Issue by prosch88** [doronz88/pymobiledevice3#1098]
**Test environment**
- Windows 11
- iPhone 7+ iOS 15.8.2

**Describe the bug**
Shortly after capturing the traffic it stops with a valueerror.

**To Reproduce**
1. Connect device and pair
2. in Terminal write: python -m pymobiledevice3 pcap out.pcap
3. Wait and see error

**Expected behavior**
Write pcap until manual interrupt

**Logs**
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 174, in <module>
    main()
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 100, in main
    cli()
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\cli_common.py", line 150, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\pcap.py", line 54, in pcap
    service.write_to_pcap(out, packets_generator_with_print)
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\pcapd.py", line 387, in write_to_pcap
    for packet in packet_generator:
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\pcapd.py", line 357, in watch
    packet.protocol_family = socket.AddressFamily(packet.protocol_family)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 30 is not a valid AddressFamily
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Please verify the PR I just published resolves the issue

**Comment by prosch88** [comment]
This gives a new ValueError:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 174, in <module>
    main()
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 100, in main
    cli()
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\cli_common.py", line 150, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\pcap.py", line 54, in pcap
    service.write_to_pcap(out, packets_generator_with_print)
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\pcapd.py", line 392, in write_to_pcap
    for packet in packet_generator:
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\pcapd.py", line 362, in watch
    packet.protocol_family = CrossPlatformAddressFamily(packet.protocol_family)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 0 is not a valid CrossPlatformAddressFamily

**Comment by doronz88** [comment]
Pushed another fix. Try again

**Comment by prosch88** [comment]
This gives again the ValueError with 30:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 174, in <module>
    main()
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 100, in main
    cli()
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\cli_common.py", line 150, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\pcap.py", line 54, in pcap
    service.write_to_pcap(out, packets_generator_with_print)
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\pcapd.py", line 393, in write_to_pcap
    for packet in packet_generator:
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\pcapd.py", line 363, in watch
    packet.protocol_family = CrossPlatformAddressFamily(packet.protocol_family)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prosc\AppData\Local\Programs\Python\Python312\Lib\enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 30 is not a valid CrossPlatformAddressFamily

**Comment by doronz88** [comment]
check again

**Comment by prosch88** [comment]
Capture is running for some minutes. Seems to be fixed.
