### ISSUE TITLE
SSL internal error

### ISSUE THREAD

**Issue by ghost** [doronz88/pymobiledevice3#110]
**Test environment**
- Ubuntu 21.04
- iPhone X, iOS 15.0b5

**Describe the bug**
When trying to use lockdown services, I get the following error: `ssl.SSLError: [SSL] internal error (_ssl.c:1129)`

**To Reproduce**
1. Connect a device via USB
2. Run `pymobiledevice3 lockdown service com.apple.mobile.heartbeat`

**Expected behavior**
The command should complete successfully.

**Logs**
```
❯ pymobiledevice3 lockdown service com.apple.mobile.heartbeat
2021-08-12 13:41:58 athena root[234679] WARNING Using iTunes pair record: [REDACTED].plist
Traceback (most recent call last):
  File "/home/nyuszika7h/getnonce/.venv/bin/pymobiledevice3", line 8, in <module>
    sys.exit(cli())
  File "/home/nyuszika7h/getnonce/.venv/lib/python3.9/site-packages/pymobiledevice3/__main__.py", line 41, in cli
    cli_commands()
  File "/home/nyuszika7h/getnonce/.venv/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/nyuszika7h/getnonce/.venv/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/nyuszika7h/getnonce/.venv/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nyuszika7h/getnonce/.venv/lib/python3.9/site-packages/click/core.py", line 1666, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/home/nyuszika7h/getnonce/.venv/lib/python3.9/site-packages/click/core.py", line 923, in make_context
    self.parse_args(ctx, args)
  File "/home/nyuszika7h/getnonce/.venv/lib/python3.9/site-packages/click/core.py", line 1379, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/nyuszika7h/getnonce/.venv/lib/python3.9/site-packages/click/core.py", line 2364, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/home/nyuszika7h/getnonce/.venv/lib/python3.9/site-packages/click/core.py", line 2326, in process_value
    value = self.callback(ctx, self, value)
  File "/home/nyuszika7h/getnonce/.venv/lib/python3.9/site-packages/pymobiledevice3/cli/cli_common.py", line 44, in udid
    return LockdownClient(udid=value)
  File "/home/nyuszika7h/getnonce/.venv/lib/python3.9/site-packages/pymobiledevice3/lockdown.py", line 101, in __init__
    if not self.validate_pairing():
  File "/home/nyuszika7h/getnonce/.venv/lib/python3.9/site-packages/pymobiledevice3/lockdown.py", line 188, in validate_pairing
    self.service.ssl_start(self.ssl_file, self.ssl_file)
  File "/home/nyuszika7h/getnonce/.venv/lib/python3.9/site-packages/pymobiledevice3/service_connection.py", line 120, in ssl_start
    self.socket = context.wrap_socket(self.socket)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL] internal error (_ssl.c:1129)
```

**Additional context**
N/A

**Comment by doronz88** [comment]
Thanks for the report! I'll be sure to check it out as soon a I get my hands on an iOS 15 device (I'm currently more focused on implementing `idevicerestore` functionality). Until then, maybe try to remove the following lines from `lockdown.py`

```python
        if attr.get('EnableServiceSSL', False):
            service_connection.ssl_start(self.ssl_file, self.ssl_file)
```

**Comment by doronz88** [comment]
I've tested iOS 15.0b5 with an iPhone 8 Plus but all seems to work just fine.
I suspect the problem has something to do with your local openssl installation. Maybe an update is required? Also, does this occur with other relays such as the AFC?

```shell
pymobiledevice3 afc shell
```

**Comment by edmundsmith** [comment]
Hi, I also had this issue on Ubuntu 21.04. 

I got it working locally by patching the line at https://github.com/doronz88/pymobiledevice3/blob/a1908007b5a6cc5e45e2530b54e4133de5e45858/pymobiledevice3/service_connection.py#L114 to use `ssl.PROTOCOL_TLSV1_2` instead of `ssl.PROTOCOL_TLSv1`. 

Googling for "internal error _ssl.c 1129" got me down a rabbit hole of bug reports about OpenSSL handshakes and negotiating minimum TLS version, with Ubuntu's version of OpenSSL not accepting TLS 1.0 on the settings that other distros/OSs do. Thus, using 1.2 by default sidestepped the issue and works again (at least for me).

@doronz88 @nyuszika7h does this change work in your environments/solve the issue?
(and thank you for this library, by the way!)

**Comment by doronz88** [comment]
Thanks for the review and possible solution! 😃 We're testing stuff mostly on macOS and the bug doesn't occur there. We'll test if the following fix doesn't break on different iOS versions and add the required change to support all variants

**Comment by doronz88** [comment]
@edmundsmith @nyuszika7h can you verify the PR solves the issue?

**Comment by edmundsmith** [comment]
The PR solves the issue for me, tested successfully with both `pymobiledevice3 lockdown service com.apple.mobile.heartbeat` and my own app.

**Comment by ghost** [comment]
Yes, I can confirm it works too.
