### ISSUE TITLE
Can't start a debugserver on tvOS 17

### ISSUE THREAD

**Issue by corrrso** [doronz88/pymobiledevice3#1122]
**Test environment**
- Ubuntu 20.
- tvOS 17.5.1 - AppleTV5,3.
- pymobiledevice3: version 4.11.8

**Describe the bug**
I'm trying to open a debugserver with `pymobiledevice3 developer debugserver start-server --tunnel ''`, but I get the generic error "Failed to start the service"

**To Reproduce**
1. Open a remote tunnel with `pymobiledevice3 remote tunneld`
2. Try to start a debugserver with `pymobiledevice3 developer debugserver start-server --tunnel ''`
3. The following error is printed:

```
pymobiledevice3.__main__[6219] ERROR Failed to start service. Possible reasons are:
- If you were trying to access a developer service (developer subcommand):
    - Make sure the DeveloperDiskImage/PersonalizedImage is mounted via:
      > python3 -m pymobiledevice3 mounter auto-mount

    - If your device iOS version >= 17.0:
        - Make sure you passed the --rsd option to the subcommand
          https://github.com/doronz88/pymobiledevice3#working-with-developer-tools-ios--170

- Apple removed this service

- A bug. Please file a bug report:
  https://github.com/doronz88/pymobiledevice3/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=
  ```
4. Please notice that in the tunnel logs, I can see a successful ping to it when the error is thrown: `127.0.0.1:38020 - "GET / HTTP/1.1" 200 OK`

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Sounds like the DDI wasn't mounted. Try:

```shell
pymobiledevice3 mounter auto-mount
```

**Comment by corrrso** [comment]
Apologies, forgot to say I already tried to auto-mount (auto-mount works for devices < 17, seems it doesn't for devices 17+)

I'm receiving this error. Tried both after creating a tunnel and without any tunnels open

Looks like the auto-mounter can't find a DDI for my specific model? Is there any way I can help with this?

```
pymobiledevice3 mounter auto-mount --tunnel ''
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pymobiledevice3/services/mobile_image_mounter.py", line 162, in query_personalization_manifest
    return response['ImageSignature']
KeyError: 'ImageSignature'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pymobiledevice3/services/mobile_image_mounter.py", line 208, in mount
    manifest = self.query_personalization_manifest('DeveloperDiskImage', hashlib.sha384(image).digest())
  File "/usr/local/lib/python3.9/dist-packages/pymobiledevice3/services/mobile_image_mounter.py", line 164, in query_personalization_manifest
    raise MissingManifestError()
pymobiledevice3.exceptions.MissingManifestError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pymobiledevice3", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/pymobiledevice3/__main__.py", line 100, in main
    cli()
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pymobiledevice3/cli/cli_common.py", line 146, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pymobiledevice3/cli/mounter.py", line 120, in mounter_auto_mount
    auto_mount(service_provider, xcode=xcode, version=version)
  File "/usr/local/lib/python3.9/dist-packages/pymobiledevice3/services/mobile_image_mounter.py", line 362, in auto_mount
    auto_mount_personalized(lockdown)
  File "/usr/local/lib/python3.9/dist-packages/pymobiledevice3/services/mobile_image_mounter.py", line 355, in auto_mount_personalized
    PersonalizedImageMounter(lockdown=lockdown).mount(image, build_manifest, trustcache)
  File "/usr/local/lib/python3.9/dist-packages/pymobiledevice3/services/mobile_image_mounter.py", line 211, in mount
    manifest = self.get_manifest_from_tss(plistlib.loads(build_manifest.read_bytes()))
  File "/usr/local/lib/python3.9/dist-packages/pymobiledevice3/services/mobile_image_mounter.py", line 242, in get_manifest_from_tss
    raise NoSuchBuildIdentityError(f'Could not find the manifest for board {board_id} and chip {chip_id}')
pymobiledevice3.exceptions.NoSuchBuildIdentityError: Could not find the manifest for board 52 and chip 28672
```

**Comment by doronz88** [comment]
Oh you are correct. I only included the DDI for iOS. Please submit a PR to add your model which is queried from:
https://github.com/doronz88/DeveloperDiskImage/tree/main/PersonalizedImages

Alternatively, you can just open XCode which will mount the relevant DDI automatically

**Comment by corrrso** [comment]
Thank you, will look into this. Are there any resources on how to gather all the data for the new `<dict>` entry? Apologies, but I'm not really used to this.

**Comment by doronz88** [comment]
They should all be present in `~/Library/Developer`
