### ISSUE TITLE
ConnectionAbortedError in pull dir

### ISSUE THREAD

**Issue by huan1936** [doronz88/pymobiledevice3#1142]
**Test environment**
- Host OS version. Windows 10
- Target device model and iOS version.  iPhone 11  13.5.1

**Describe the bug**
I want to backup ipa
Error when exporting multiple nested folders. e.g.: 
```
/private/var/containers/Bundle/Application/AA6B8411-49E5-4A20-A07C-5C6A41D9D09F/ace.app
```

**To Reproduce**
1. use 'AfcService and service_name='com.apple.afc2''
2. get app path   e.g.
```
/private/var/containers/Bundle/Application/AA6B8411-49E5-4A20-A07C-5C6A41D9D09F/ace.app
```

3. pull path afc.pull

**Expected behavior**
There are 60 files in total, and all of them were expected to be exported. In fact, only 34 files were exported and an error occurred.

**Logs**
```python
Traceback (most recent call last):
  File "D:\pyCode\other\pyapp\app\devices\server\backup_ipa.py", line 40, in _backup_ipa
    afc.pull(path, output_path)
  File "D:\pyCode\other\venv\lib\site-packages\pymobiledevice3\services\afc.py", line 258, in pull
    self.pull(src_filename, str(dst_path), callback=callback)
  File "D:\pyCode\other\venv\lib\site-packages\pymobiledevice3\services\afc.py", line 237, in pull
    f.write(self.get_file_contents(src))
  File "D:\pyCode\other\venv\lib\site-packages\parameter_decorators\common.py", line 28, in new_f
    return f(*ba.args, **ba.kwargs)
  File "D:\pyCode\other\venv\lib\site-packages\pymobiledevice3\services\afc.py", line 528, in get_file_contents
    d = self.fread(h, int(info['st_size']))
  File "D:\pyCode\other\venv\lib\site-packages\pymobiledevice3\services\afc.py", line 471, in fread
    status, chunk = self._receive_data()
  File "D:\pyCode\other\venv\lib\site-packages\pymobiledevice3\services\afc.py", line 592, in _receive_data
    data = self.service.recvall(length)
  File "D:\pyCode\other\venv\lib\site-packages\pymobiledevice3\service_connection.py", line 140, in recvall
    raise ConnectionAbortedError()
ConnectionAbortedError
```

```python
            with AfcService(lockdown, service_name='com.apple.afc2') as afc:
                afc.pull(path, output_path)
```

**Additional context**

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
I don't know of `afc2` so I cannot reproduce, but sounds like it's buggy. Do you have a good reason to believe otherwise?
