### ISSUE TITLE
pymobiledevice3 developer dvt launch error

### ISSUE THREAD

**Issue by E3lleyyaa** [doronz88/pymobiledevice3#1143]
I'm getting this error, when trying to procced developer dvt launch.
I've tested on IOS 17+ and IOS 16.8 same result.
[2024-07-30 12:29:41.253] [error] open-app-ios error Error: Command failed:  C:\Users\Ilya\AppData\Local\Programs\electron-react-boilerplate\resources\python\python.exe C:\Users\Ilya\AppData\Local\Programs\electron-react-boilerplate\resources\python\pymobiledevice3\pymobiledevice3 developer dvt launch my-bundle-id
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Ilya\AppData\Local\Programs\electron-react-boilerplate\resources\python\pymobiledevice3\pymobiledevice3\__main__.py", line 8, in <module>
    from pymobiledevice3.exceptions import AccessDeniedError, ConnectionFailedToUsbmuxdError, DeprecationError, \
ModuleNotFoundError: No module named 'pymobiledevice3.exceptions'

**Comment by E3lleyyaa** [comment]
@doronz88

**Comment by doronz88** [comment]
I'm not sure what are you doing, but you are not executing the binary pymobiledevice3 entry point

**Comment by E3lleyyaa** [comment]
> I'm not sure what are you doing, but you are not executing the binary pymobiledevice3 entry point

It's challenging to explain in detail, but here's a brief overview. I store the Python and pymobiledevice3 files locally in my project directory. When I need to run something, I use the exec function from Node.js, specifying the path to the necessary files.
