### ISSUE TITLE
Could not be able to mount the developer disk image in IOS 15.8

### ISSUE THREAD

**Issue by prajwal271** [doronz88/pymobiledevice3#1145]
```
Traceback (most recent call last):
  File "pymobiledevice3\__main__.py", line 170, in <module>
  File "pymobiledevice3\__main__.py", line 100, in main
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1688, in invoke
  File "click\core.py", line 1688, in invoke
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "pymobiledevice3\cli\cli_common.py", line 146, in wrap_callback_calling
  File "C:\Program Files\SQA-Agent\libs\Ios_tool\rsdrunner\_internal\pymobiledevice3\cli\mounter.py", line 120, in mounter_auto_mount
    auto_mount(service_provider, xcode=xcode, version=version)
  File "C:\Program Files\SQA-Agent\libs\Ios_tool\rsdrunner\_internal\pymobiledevice3\services\mobile_image_mounter.py", line 360, in auto_mount
    auto_mount_developer(lockdown, xcode=xcode, version=version)
  File "C:\Program Files\SQA-Agent\libs\Ios_tool\rsdrunner\_internal\pymobiledevice3\services\mobile_image_mounter.py", line 335, in auto_mount_developer
    image_mounter.mount(image_path, signature)
  File "C:\Program Files\SQA-Agent\libs\Ios_tool\rsdrunner\_internal\pymobiledevice3\services\mobile_image_mounter.py", line 188, in mount
    self.mount_image(self.IMAGE_TYPE, signature)
  File "C:\Program Files\SQA-Agent\libs\Ios_tool\rsdrunner\_internal\pymobiledevice3\services\mobile_image_mounter.py", line 102, in mount_image
    raise PyMobileDevice3Exception(f'command MountImage failed with: {response}')
pymobiledevice3.exceptions.PyMobileDevice3Exception: command MountImage failed with: {'DetailedError': 'Error Domain=com.apple.MobileStorage.ErrorDomain Code=-2 "Failed to mount /private/var/run/mobile_image_mounter/831B85AFB90469917BF89EE59B6CF7CC9E642B061D33421B8D730AF7A7984E4DC385FBAB01A8C47CD40689931E912911E1FA21B5B7D725ABB16FE10F0E4F0D7A/80D879A1645D9351F17F41C74B5B044659CAD72CE3C5495C67FFCB703385741B443C4C3BB30BDBDF4ABFEA0E656C0D568CF272427E72FE5ECE80AFEBB2F60F2E/n2HOCo.dmg." UserInfo={NSLocalizedDescription=Failed to mount /private/var/run/mobile_image_mounter/831B85AFB90469917BF89EE59B6CF7CC9E642B061D33421B8D730AF7A7984E4DC385FBAB01A8C47CD40689931E912911E1FA21B5B7D725ABB16FE10F0E4F0D7A/80D879A1645D9351F17F41C74B5B044659CAD72CE3C5495C67FFCB703385741B443C4C3BB30BDBDF4ABFEA0E656C0D568CF272427E72FE5ECE80AFEBB2F60F2E/n2HOCo.dmg., NSUnderlyingError=0x10250c9d0 {Error Domain=com.apple.MobileStorage.ErrorDomain Code=-2 "Invalid value for MountPath: Error Domain=com.apple.MobileStorage.ErrorDomain Code=-2 "Failed to mount /private/var/run/mobile_image_mounter/831B85AFB90469917BF89EE59B6CF7CC9E642B061D33421B8D730AF7A7984E4DC385FBAB01A8C47CD40689931E912911E1FA21B5B7D725ABB16FE10F0E4F0D7A/80D879A1645D9351F17F41C74B5B044659CAD72CE3C5495C67FFCB703385741B443C4C3BB30BDBDF4ABFEA0E656C0D568CF272427E72FE5ECE80AFEBB2F60F2E/n2HOCo.dmg at /Developer." UserInfo={NSLocalizedDescription=Failed to mount /private/var/run/mobile_image_mounter/831B85AFB90469917BF89EE59B6CF7CC9E642B061D33421B8D730AF7A7984E4DC385FBAB01A8C47CD40689931E912911E1FA21B5B7D725ABB16FE10F0E4F0D7A/80D879A1645D9351F17F41C74B5B044659CAD72CE3C5495C67FFCB703385741B443C4C3BB30BDBDF4ABFEA0E656C0D568CF272427E72FE5ECE80AFEBB2F60F2E/n2HOCo.dmg at /Developer.}" UserInfo={NSLocalizedDescription=Invalid value for MountPath: Error Domain=com.apple.MobileStorage.ErrorDomain Code=-2 "Failed to mount /private/var/run/mobile_image_mounter/831B85AFB90469917BF89EE59B6CF7CC9E642B061D33421B8D730AF7A7984E4DC385FBAB01A8C47CD40689931E912911E1FA21B5B7D725ABB16FE10F0E4F0D7A/80D879A1645D9351F17F41C74B5B044659CAD72CE3C5495C67FFCB703385741B443C4C3BB30BDBDF4ABFEA0E656C0D568CF272427E72FE5ECE80AFEBB2F60F2E/n2HOCo.dmg at /Developer." UserInfo={NSLocalizedDescription=Failed to mount /private/var/run/mobile_image_mounter/831B85AFB90469917BF89EE59B6CF7CC9E642B061D33421B8D730AF7A7984E4DC385FBAB01A8C47CD40689931E912911E1FA21B5B7D725ABB16FE10F0E4F0D7A/80D879A1645D9351F17F41C74B5B044659CAD72CE3C5495C67FFCB703385741B443C4C3BB30BDBDF4ABFEA0E656C0D568CF272427E72FE5ECE80AFEBB2F60F2E/n2HOCo.dmg at /Developer.}}}}', 'Error': 'ImageMountFailed'}
```

**Comment by prosch88** [comment]
Use the 15.6 Image

**Comment by doronz88** [comment]
Sounds like the device doesn't support the supplied DDI.
