### ISSUE TITLE
FEATURE REQUEST: usbmuxd2 support

### ISSUE THREAD

**Issue by fish4terrisa-MSDSM** [doronz88/pymobiledevice3#1147]
Usbmuxd2 is a new kind of usbmuxd.
It seems that when usbmuxd2 is connected with the device(I can run idevice_id to get the id, and use ideviceinfo to get device info, use idevicesyslog to get the log...etc.)
However, pymobiledevice3 cannot connect to the device.
It always give the error:
```
pymobiledevice3.exceptions.ConnectionFailedError: got an error message: {'MessageType': 'Result', 'Number': 3}
```
A full error log with `sudo pymobiledevice3 usbmux list` ( I can use ideviceinfo and idevice_id when I'm running this command ):
```python
Traceback (most recent call last):
  File "/usr/bin/pymobiledevice3", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/pymobiledevice3/__main__.py", line 100, in main
    cli()
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pymobiledevice3/cli/usbmux.py", line 65, in usbmux_list
    lockdown = create_using_usbmux(udid, autopair=False, connection_type=device.connection_type,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pymobiledevice3/lockdown.py", line 716, in create_using_usbmux
    service = ServiceConnection.create_using_usbmux(serial, port, connection_type=connection_type,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pymobiledevice3/service_connection.py", line 94, in create_using_usbmux
    sock = target_device.connect(port, usbmux_address=usbmux_address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 88, in connect
    return mux.connect(self, port)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 221, in connect
    self._connect(device.devid, socket.htons(port))
  File "/usr/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 379, in _connect
    self._send_receive({'MessageType': 'Connect', 'DeviceID': device_id, 'PortNumber': port})
  File "/usr/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 402, in _send_receive
    raise self._raise_mux_exception(response['Number'], f'got an error message: {response}')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 242, in _raise_mux_exception
    raise exception(message)
pymobiledevice3.exceptions.ConnectionFailedError: got an error message: {'MessageType': 'Result', 'Number': 3}
```
Does anyone know how to fix it?
Usbmuxd2 is the only kind of usbmuxd that can connect my ipad pro m4 with ios 17.4 through tailscale...

**Comment by doronz88** [comment]
Unfortunately, `usbmuxd2` does not support the `Connect` protocol message. The correct fix would be to submit a PR to `usbmuxd2` to support it.

You can however add support for pymobile to support it since you managed to build usbmuxd2 so feel free to PR whichever project

**Comment by jordus100** [comment]
@fish4terrisa-MSDSM I also struggled with a very similar problem until I discovered that `pymobiledevice3` is able to connect to `lockdownd` wirelessly on my iPhone on its own without `usbmuxd2`. You can try enabling wireless lockdown connections and then `pymobiledevice3 tunneld` should be able to discover the iOS device and connect to it.

**Comment by Jaykob** [comment]
This would be anyhow very welcoming, as we still need usbmuxd for the initial pairing, right?

**Comment by doronz88** [comment]
PRs are welcome

**Comment by doronz88** [comment]
Looks like this issue should be closed by now:
https://github.com/tihmstar/usbmuxd2/issues/41
