### ISSUE TITLE
remote tunneld error code 1168

### ISSUE THREAD

**Issue by e790a8** [doronz88/pymobiledevice3#1152]
**Test environment**
PC：Windows10
iPhone：14 Pro Max（17.6）
DLL File：
[IPHLPAPI.zip](https://github.com/user-attachments/files/16540470/IPHLPAPI.zip)

**Describe the bug**

(venv) D:\App\JetBrains\Python\app-uitest-case>pymobiledevice3 remote tunneld
INFO:     Started server process [1244]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)
2024-08-08 16:22:25 DST013245 pymobiledevice3.tunneld[1244] ERROR got exception from start-tunnel-task-usbmux-00008120001A0DDC3C38C01E-USB: Traceback (most recent call last):
  File "d:\app\jetbrains\python\app-uitest-case\venv\lib\site-packages\pymobiledevice3\tunneld.py", line 199, in start_tunnel_task
    async with start_tunnel(protocol_handler, protocol=protocol) as tun:
  File "D:\Users\yongkunhuang\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "d:\app\jetbrains\python\app-uitest-case\venv\lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 1018, in start_tunnel
    async with protocol_handler.start_tcp_tunnel() as service:
  File "D:\Users\yongkunhuang\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "d:\app\jetbrains\python\app-uitest-case\venv\lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 932, in start_tcp_tunnel
    tunnel.start_tunnel(handshake_response['clientParameters']['address'],
  File "d:\app\jetbrains\python\app-uitest-case\venv\lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 298, in start_tunnel
    super().start_tunnel(address, mtu)
  File "d:\app\jetbrains\python\app-uitest-case\venv\lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 180, in start_tunnel
    self.tun.addr = address
  File "d:\app\jetbrains\python\app-uitest-case\venv\lib\site-packages\pytun_pmd3\wintun.py", line 277, in addr
    result = subprocess.run(f"netsh interface ipv6 set address interface={self.interface_index} address={value}/64",
  File "d:\app\jetbrains\python\app-uitest-case\venv\lib\site-packages\pytun_pmd3\wintun.py", line 263, in interface_index
    return self.ip_interface_entry.InterfaceIndex
  File "d:\app\jetbrains\python\app-uitest-case\venv\lib\site-packages\pytun_pmd3\wintun.py", line 242, in ip_interface_entry
    raise PyWinTunException(f"Failed to get IP interface entry, error code: {result}")
pytun_pmd3.exceptions.PyWinTunException: Failed to get IP interface entry, error code: 1168

**Comment by doronz88** [comment]
Did you make sure to execute it in with system priv?

**Comment by e790a8** [comment]
It's a problem with network adapter ipv6
![image](https://github.com/user-attachments/assets/0dfe2221-febf-4d31-bb3a-fe03b1567422)
![image](https://github.com/user-attachments/assets/a5af0f1a-8dea-4653-a6d6-18a93c85929a)
change to AF_INET，result is 0

What is so special about the network adapters created by wintun?
PC ipv6 show not found：
![image](https://github.com/user-attachments/assets/3db1dd7c-e849-4ca4-b59a-cf9f75e33cff)
Vmware success：
![image](https://github.com/user-attachments/assets/4610463e-eb6a-40c9-b272-8a69755274a7)

I don't understand windows very well
How can I find out the cause

**Comment by AnNEDoMini** [comment]
In my case, such error on Win workstations was solved by enabling ipv6

**Comment by lezhi12** [comment]
how did you solve this problem? my ipv6  is enabled(win10 ),but still has the same  problem iOS 18.3
