### ISSUE TITLE
pymobiledevice3 restore exit

### ISSUE THREAD

**Issue by E3lleyyaa** [doronz88/pymobiledevice3#1183]
1. pymobiledevice3 restore enter -all fine device goes from normal to restore mode.
2.pymobiledevice3 restore update - 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\38063\Desktop\pymobiledevice3\pymobiledevice3\__main__.py", line 188, in <module>
    main()
  File "C:\Users\38063\Desktop\pymobiledevice3\pymobiledevice3\__main__.py", line 110, in main
    cli()
  File "C:\Users\38063\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\38063\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\38063\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\38063\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1686, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\38063\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "C:\Users\38063\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\38063\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\38063\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\38063\Desktop\pymobiledevice3\pymobiledevice3\cli\restore.py", line 72, in device
    return IRecv(ecid=ecid)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\38063\Desktop\pymobiledevice3\pymobiledevice3\irecv.py", line 68, in __init__
    self._reinit(ecid=ecid, timeout=timeout, is_recovery=is_recovery)
  File "C:\Users\38063\Desktop\pymobiledevice3\pymobiledevice3\irecv.py", line 241, in _reinit
    self._find(ecid=ecid, timeout=timeout, is_recovery=is_recovery)
  File "C:\Users\38063\Desktop\pymobiledevice3\pymobiledevice3\irecv.py", line 265, in _find
    for device in find(find_all=True):
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\38063\AppData\Roaming\Python\Python312\site-packages\usb\core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

3.pymobiledevice3 restore exit 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\38063\Desktop\pymobiledevice3\pymobiledevice3\__main__.py", line 188, in <module>
    main()
  File "C:\Users\38063\Desktop\pymobiledevice3\pymobiledevice3\__main__.py", line 110, in main
    cli()
  File "C:\Users\38063\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\38063\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\38063\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\38063\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\38063\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\38063\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\38063\Desktop\pymobiledevice3\pymobiledevice3\cli\restore.py", line 172, in restore_exit
    irecv = IRecv()
            ^^^^^^^
  File "C:\Users\38063\Desktop\pymobiledevice3\pymobiledevice3\irecv.py", line 68, in __init__
    self._reinit(ecid=ecid, timeout=timeout, is_recovery=is_recovery)
  File "C:\Users\38063\Desktop\pymobiledevice3\pymobiledevice3\irecv.py", line 241, in _reinit
    self._find(ecid=ecid, timeout=timeout, is_recovery=is_recovery)
  File "C:\Users\38063\Desktop\pymobiledevice3\pymobiledevice3\irecv.py", line 265, in _find
    for device in find(find_all=True):
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\38063\AppData\Roaming\Python\Python312\site-packages\usb\core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

**Comment by doronz88** [comment]
https://github.com/doronz88/pymobiledevice3?tab=readme-ov-file#libusb-dependency
