### ISSUE TITLE
Error code 205 Underlying error: Error deserializing properties

### ISSUE THREAD

**Issue by Lautarob1** [doronz88/pymobiledevice3#1187]
**Test environment**
- Dell XPS laptop Windows 11 pro ( 10.0.22631 N/A Build 22631) (intel core 7, 64 GB RAM)
- iPhone 13 max pro 128 GB running iOS 17.6.1

**Describe the bug**
while trying to make a backup, I got the following error messages:
(.venv) D:\SmartPhone>pymobiledevice3 backup2 backup c:\tests
  0%|                                                                                        | 0.0/100 [00:12<?, ?it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "d:\SmartPhone\.venv\Scripts\pymobiledevice3.exe\__main__.py", line 7, in <module>
  File "d:\SmartPhone\.venv\Lib\site-packages\pymobiledevice3\__main__.py", line 110, in main
    cli()
  File "d:\SmartPhone\.venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\SmartPhone\.venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "d:\SmartPhone\.venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\SmartPhone\.venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\SmartPhone\.venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\SmartPhone\.venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\SmartPhone\.venv\Lib\site-packages\pymobiledevice3\cli\cli_common.py", line 150, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "d:\SmartPhone\.venv\Lib\site-packages\pymobiledevice3\cli\backup.py", line 46, in backup
    backup_client.backup(full=full, backup_directory=backup_directory, progress_callback=update_bar)
  File "d:\SmartPhone\.venv\Lib\site-packages\pymobiledevice3\services\mobilebackup2.py", line 91, in backup
    dl.dl_loop(progress_callback)
  File "d:\SmartPhone\.venv\Lib\site-packages\pymobiledevice3\services\device_link.py", line 61, in dl_loop
    raise PyMobileDevice3Exception(f'Device link error: {message[1]}')
pymobiledevice3.exceptions.PyMobileDevice3Exception: Device link error: {'ErrorCode': 205, 'ErrorDescription': 'Error reading backup properties (MBErrorDomain/205). Underlying error: Error deserializing properties: Cannot parse a NULL or zero-length data (MBErrorDomain/11).', 'MessageName': 'Response'}

**To Reproduce**
1. Go to 'pymobiledevice3 backup2 backup c:\tests'
2. See error

**Expected behavior**
It should list files being backed up until backup gets completed

**Logs**
(all I can see was included above (terminal response)

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
First backup should be a full backup:
```shell
pymobiledevice3 backup2 backup . --full
```
Only then you can backup a delta

**Comment by Lautarob1** [comment]
Thank you!. It worked perfectly well after adding option --full
