### ISSUE TITLE
Restore problems

### ISSUE THREAD

**Issue by E3lleyyaa** [doronz88/pymobiledevice3#1188]
**Test environment**
- MacOS.
-  Iphone 14/ 17.6.1.

**Describe the bug**
When I try to exit recovery mode or run a firmware upgrade in recovery mode, I get these errors. I saw your reply about libusb, and I got that error on Windows. Now, I’ve decided to try it on Mac. Before that, I installed the dependencies as mentioned in the guide.

`python3 pymobiledevice3 usbmux list
[
    {
        "BuildVersion": "21G101",
        "ConnectionType": "USB",
        "DeviceClass": "iPhone",
        "DeviceName": "EDITED",
        "Identifier": "EDITED,
        "ProductType": "iPhone14,7",
        "ProductVersion": "17.6.1",
        "UniqueDeviceID": "EDITED"
    }
]`

**To Reproduce**
1. python3 pymobiledevice3 restore exit or  python3 pymobiledevice3 restore update

**Logs**
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/demien/Desktop/pymobiledevice3/pymobiledevice3/__main__.py", line 188, in <module>
    main()
  File "/Users/demien/Desktop/pymobiledevice3/pymobiledevice3/__main__.py", line 110, in main
    cli()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pymobiledevice3/cli/restore.py", line 172, in restore_exit
    irecv = IRecv()
            ^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pymobiledevice3/irecv.py", line 68, in __init__
    self._reinit(ecid=ecid, timeout=timeout, is_recovery=is_recovery)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pymobiledevice3/irecv.py", line 241, in _reinit
    self._find(ecid=ecid, timeout=timeout, is_recovery=is_recovery)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pymobiledevice3/irecv.py", line 265, in _find
    for device in find(find_all=True):
                  ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/usb/core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available`

**Additional context**
Proofs that I have already installed  libusb
<img width="657" alt="Знімок екрана 2024-09-07 о 12 28 12" src="https://github.com/user-attachments/assets/4cbb4f48-1dd8-46fd-bfc2-96cf51aefc3f">
<img width="657" alt="Знімок екрана 2024-09-07 о 12 28 43" src="https://github.com/user-attachments/assets/bcb12f7d-3630-4ef3-b930-20875ad6ea69">

**Comment by E3lleyyaa** [comment]
@doronz88

**Comment by doronz88** [comment]
Apparently your libusb isn't recognized by `pyusb`.
Feel free to report them an issue.
