### ISSUE TITLE
PersonalizedImageMounter.mount() missing 1 required positional argument: 'info_plist'

### ISSUE THREAD

**Issue by rob-X1** [doronz88/pymobiledevice3#1231]
**Test environment**
- MacOS Sonoma 14.7, Xcode installed and set-up
- Python 3.12 (via homebrew)
- iPhone SE 3rd gen iOS17.7

**Describe the bug**
Since v4.14.x the command `mounter auto-mount` no longer works

**To Reproduce**
- Execute `python3 -m pymobiledevice3 mounter auto-mount`

```

Traceback (most recent call last):
  File "/Users/user/tmp/venv/bin/pymobiledevice3", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/user/tmp/venv/lib/python3.12/site-packages/pymobiledevice3/__main__.py", line 169, in main
    cli()
  File "/Users/user/tmp/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/tmp/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/user/tmp/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/tmp/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/tmp/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/tmp/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/tmp/venv/lib/python3.12/site-packages/pymobiledevice3/cli/cli_common.py", line 158, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "/Users/user/tmp/venv/lib/python3.12/site-packages/pymobiledevice3/cli/mounter.py", line 142, in mounter_auto_mount
    asyncio.run(mounter_auto_mount_task(service_provider, xcode, version), debug=True)
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/user/tmp/venv/lib/python3.12/site-packages/pymobiledevice3/cli/mounter.py", line 121, in mounter_auto_mount_task
    await auto_mount(service_provider, xcode=xcode, version=version)
  File "/Users/user/tmp/venv/lib/python3.12/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 366, in auto_mount
    await auto_mount_personalized(lockdown)
  File "/Users/user/tmp/venv/lib/python3.12/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 359, in auto_mount_personalized
    await PersonalizedImageMounter(lockdown=lockdown).mount(image, build_manifest, trustcache)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PersonalizedImageMounter.mount() missing 1 required positional argument: 'info_plist'
```

**Comment by doronz88** [comment]
Thanks for the report! Will be fixed and released asap!
