### ISSUE TITLE
For iOS18.0.1, pymobiledevice3 mounter auto-mount doesn't work

### ISSUE THREAD

**Issue by 2088669827** [doronz88/pymobiledevice3#1238]
**Test environment**
- macOS 14.4.1
- iPhone 16pro max，iOS18.0.1

**Describe the bug**
1. open the developer mode
2. execute the command: pymobiledevice3 mounter auto-mount

**Logs**
Traceback (most recent call last):
  File "/Users/huangguihua/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 162, in query_personalization_manifest
    return response['ImageSignature']
KeyError: 'ImageSignature'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangguihua/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 208, in mount
    manifest = self.query_personalization_manifest('DeveloperDiskImage', hashlib.sha384(image).digest())
  File "/Users/huangguihua/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 164, in query_personalization_manifest
    raise MissingManifestError()
pymobiledevice3.exceptions.MissingManifestError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangguihua/Library/Python/3.9/bin/pymobiledevice3", line 8, in <module>
    sys.exit(main())
  File "/Users/huangguihua/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/__main__.py", line 100, in main
    cli()
  File "/Library/Python/3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Library/Python/3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/huangguihua/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/cli_common.py", line 146, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "/Users/huangguihua/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/mounter.py", line 120, in mounter_auto_mount
    auto_mount(service_provider, xcode=xcode, version=version)
  File "/Users/huangguihua/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 362, in auto_mount
    auto_mount_personalized(lockdown)
  File "/Users/huangguihua/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 355, in auto_mount_personalized
    PersonalizedImageMounter(lockdown=lockdown).mount(image, build_manifest, trustcache)
  File "/Users/huangguihua/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 211, in mount
    manifest = self.get_manifest_from_tss(plistlib.loads(build_manifest.read_bytes()))
  File "/Users/huangguihua/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 242, in get_manifest_from_tss
    raise NoSuchBuildIdentityError(f'Could not find the manifest for board {board_id} and chip {chip_id}')
pymobiledevice3.exceptions.NoSuchBuildIdentityError: Could not find the manifest for board 14 and chip 33088

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Make sure you are using the latest `pymobiledevice3`

**Comment by Lizihao002023** [comment]
so cool
