### ISSUE TITLE
iOS 17.5 remote tunneld failed in  windows admin shell 

### ISSUE THREAD

**Issue by lezhi12** [doronz88/pymobiledevice3#1275]
**Test environment**
- windows 10 administrator shell .
- iPhone 11 iOS 17.5.1.

**Describe the bug**
1.run  "pymibiledevice3 remote tunneld" failed. 
2. it success until this morning. but failed afternoon, I don't change anything neither on Windows nor on iPhone 

**To Reproduce**
1. connect iPhone  to  windows 
2. run  "pymibiledevice3 remote tunneld" in an admin shell 
3.see error “pytun_pmd3.exceptions.PyWinTunException: Failed to get IP interface entry, error code: 1168”

**Expected behavior**
tunnel should be created successfully 

**Logs**

(mobiledevice3_venv) E:\hanhao\python_venv\mobiledevice3_venv\Scripts>pymobiledevice3 remote tunneld
INFO: Started server process [20720]
INFO: Waiting for application startup.
INFO: Application startup complete.
INFO: Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)
2024-11-11 15:49:09 DESKTOP-RT0KKU0 pymobiledevice3.tunneld[20720] ERROR got exception from start-tunnel-task-usbmux-00008030-001935A03EF9402E-USB: Traceback (most recent call last):
File "E:\hanhao\python_venv\mobiledevice3_venv\Lib\site-packages\pymobiledevice3\tunneld.py", line 200, in start_tunnel_task
async with start_tunnel(protocol_handler, protocol=protocol) as tun:
File "D:\software\Python\Lib\contextlib.py", line 204, in __aenter__
return await anext(self.gen)
^^^^^^^^^^^^^^^^^^^^^
File "E:\hanhao\python_venv\mobiledevice3_venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 1025, in start_tunnel
async with protocol_handler.start_tcp_tunnel() as service:
File "D:\software\Python\Lib\contextlib.py", line 204, in __aenter__
return await anext(self.gen)
^^^^^^^^^^^^^^^^^^^^^
File "E:\hanhao\python_venv\mobiledevice3_venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 939, in start_tcp_tunnel
tunnel.start_tunnel(handshake_response['clientParameters']['address'],
File "E:\hanhao\python_venv\mobiledevice3_venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 299, in start_tunnel
super().start_tunnel(address, mtu)
File "E:\hanhao\python_venv\mobiledevice3_venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 181, in start_tunnel
self.tun.addr = address
^^^^^^^^^^^^^
File "E:\hanhao\python_venv\mobiledevice3_venv\Lib\site-packages\pytun_pmd3\wintun.py", line 277, in addr
result = subprocess.run(f"netsh interface ipv6 set address interface={self.interface_index} address={value}/64",
^^^^^^^^^^^^^^^^^^^^
File "E:\hanhao\python_venv\mobiledevice3_venv\Lib\site-packages\pytun_pmd3\wintun.py", line 263, in interface_index
return self.ip_interface_entry.InterfaceIndex
^^^^^^^^^^^^^^^^^^^^^^^
File "E:\hanhao\python_venv\mobiledevice3_venv\Lib\site-packages\pytun_pmd3\wintun.py", line 242, in ip_interface_entry
raise PyWinTunException(f"Failed to get IP interface entry, error code: {result}")
pytun_pmd3.exceptions.PyWinTunException: Failed to get IP interface entry, error code: 1168

**Additional context**

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by AnNEDoMini** [comment]
enable ipv6 on your PC
