### ISSUE TITLE
Cannot mount iPad mini 2024 after update to IOS 18.1.1

### ISSUE THREAD

**Issue by v-ostark** [doronz88/pymobiledevice3#1292]
This worked fine on IOS 18.0.1, but after update to 18.1.1 I suddenly get this:

**Test environment**
- Linux Alpine
- Ipad mini 2024，iOS18.1.1.

**Describe the bug**
Cannot mount.

**Logs**

```
File "/root/venv/lib/python3.12/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 162, in query_personalization_manifest
    return response['ImageSignature']
           ~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'ImageSignature'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/venv/lib/python3.12/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 208, in mount
    manifest = self.query_personalization_manifest('DeveloperDiskImage', hashlib.sha384(image).digest())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 164, in query_personalization_manifest
    raise MissingManifestError()
pymobiledevice3.exceptions.MissingManifestError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.12/socketserver.py", line 349, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/root/venv/lib/python3.12/site-packages/JitStreamer/__init__.py", line 159, in do_GET
    refresh_devs()
  File "/root/venv/lib/python3.12/site-packages/JitStreamer/__init__.py", line 129, in refresh_devs
    asyncio.run(auto_mount_personalized(dev))
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 355, in auto_mount_personalized
    await PersonalizedImageMounter(lockdown=lockdown).mount(image, build_manifest, trustcache)
  File "/root/venv/lib/python3.12/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 211, in mount
    manifest = await self.get_manifest_from_tss(plistlib.loads(build_manifest.read_bytes()))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 242, in get_manifest_from_tss
    raise NoSuchBuildIdentityError(f'Could not find the manifest for board {board_id} and chip {chip_id}')
pymobiledevice3.exceptions.NoSuchBuildIdentityError: Could not find the manifest for board 8 and chip 33072
```

**Comment by doronz88** [comment]
Are you using latest pymobiledevice3?

**Comment by doronz88** [comment]
Feel free to reopen
