### ISSUE TITLE
No such file or directory at 'SafeStreamSocket(address, family)'

### ISSUE THREAD

**Issue by Ra2-IFV** [doronz88/pymobiledevice3#1302]
**Test environment**

pymobiledevice3 `4.16.3`, Arch Linux

- Target device model and iOS version.

iphone 8
ios 15

**Describe the bug**
```
Traceback (most recent call last):
  File "/SideJITServer/.venv/bin/pymobiledevice3", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/SideJITServer/.venv/lib/python3.12/site-packages/pymobiledevice3/__main__.py", line 177, in main
    cli()
  File "/SideJITServer/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SideJITServer/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/SideJITServer/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SideJITServer/.venv/lib/python3.12/site-packages/click/core.py", line 1686, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SideJITServer/.venv/lib/python3.12/site-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "/SideJITServer/.venv/lib/python3.12/site-packages/click/core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SideJITServer/.venv/lib/python3.12/site-packages/click/core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SideJITServer/.venv/lib/python3.12/site-packages/click/core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SideJITServer/.venv/lib/python3.12/site-packages/pymobiledevice3/cli/cli_common.py", line 211, in udid
    devices = select_devices_by_connection_type(connection_type='USB', usbmux_address=self.usbmux_address)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SideJITServer/.venv/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 452, in select_devices_by_connection_type
    for device in list_devices(usbmux_address=usbmux_address):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SideJITServer/.venv/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 414, in list_devices
    mux = create_mux(usbmux_address=usbmux_address)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SideJITServer/.venv/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 410, in create_mux
    return MuxConnection.create(usbmux_address=usbmux_address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SideJITServer/.venv/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 174, in create
    sock = MuxConnection.create_usbmux_socket(usbmux_address=usbmux_address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SideJITServer/.venv/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 167, in create_usbmux_socket
    return SafeStreamSocket(address, family)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SideJITServer/.venv/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 111, in __init__
    self.sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```

**To Reproduce**

`source .venv/bin/activate`
`pymobiledevice3 activation activate`

**Comment by doronz88** [comment]
You'll need to install and run `usbmuxd`.
I'll document it also in main README.

**Comment by Ra2-IFV** [comment]
~~Hum perhaps I can help with this~~
d4890d1dc6d11cf2736088cd98cfe0ce868e020c
