### ISSUE TITLE
pymobiledevice3 backup2 "list" and "info" sub-commands are missing "password" option, which is necessary for encrypted backups

### ISSUE THREAD

**Issue by nabuah** [doronz88/pymobiledevice3#1314]
**Test environment**
- MacOS Sonoma 14.7.
- iPhone 12, iOS 17.2.1.
- Python 3.13.0.
- pymobiledevice3 version: 4.16.4

**Describe the bug**
When trying to list or get info of the encrypted backup, there is no option to provide a password parameter in the CLI, and as a result - both commands fail

**To Reproduce**
1. Get an encrypted backup
2. Run "pymobiledevice3 backup2 list <BACKUP_DIR>" or "pymobiledevice3 backup2 info <BACKUP_DIR>" command

**Expected behavior**
Both subcommands should have a "-p/--password" optional argument like in "extract" subcommand, in order to work on encrypted backups

**Logs**
````
pymobiledevice3 backup2 info .
Traceback (most recent call last):
  File "/Users/slavat/projects/playground/.venv/bin/pymobiledevice3", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Users/slavat/projects/playground/.venv/lib/python3.13/site-packages/pymobiledevice3/__main__.py", line 177, in main
    cli()
    ~~~^^
  File "/Users/slavat/projects/playground/.venv/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/slavat/projects/playground/.venv/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/slavat/projects/playground/.venv/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/slavat/projects/playground/.venv/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/slavat/projects/playground/.venv/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slavat/projects/playground/.venv/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/slavat/projects/playground/.venv/lib/python3.13/site-packages/pymobiledevice3/cli/cli_common.py", line 158, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slavat/projects/playground/.venv/lib/python3.13/site-packages/pymobiledevice3/cli/backup.py", line 86, in info
    print(backup_client.info(backup_directory=backup_directory, source=source))
          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slavat/projects/playground/.venv/lib/python3.13/site-packages/pymobiledevice3/services/mobilebackup2.py", line 168, in info
    result = dl.dl_loop()
  File "/Users/slavat/projects/playground/.venv/lib/python3.13/site-packages/pymobiledevice3/services/device_link.py", line 61, in dl_loop
    raise PyMobileDevice3Exception(f'Device link error: {message[1]}')
pymobiledevice3.exceptions.PyMobileDevice3Exception: Device link error: {'ErrorCode': 207, 'ErrorDescription': 'Invalid password when restoring encrypted backup (MBErrorDomain/207). Underlying error: MKBKeyBagUnlock error (-3) (MBErrorDomain/207).', 'MessageName': 'Response'}
````

````
pymobiledevice3 backup2 info --help
Usage: pymobiledevice3 backup2 info [OPTIONS] BACKUP_DIRECTORY

  Print information about a backup.

Options:
  --rsd <TEXT INTEGER>...  RSD hostname and port number (as provided by a `start-tunnel` subcommand).
                           NOTE: This argument is mutually exclusive with  arguments: [rsd_service_provider_using_tunneld].
  --tunnel TEXT            Either an empty string to force tunneld device selection, or a UDID of a tunneld discovered device.
                           The string may be suffixed with :PORT in case tunneld is not serving at the default port.
                           This option may also be transferred as an environment variable: PYMOBILEDEVICE3_TUNNEL
                           NOTE: This argument is mutually exclusive with  arguments: [rsd_service_provider_manually].
  --usbmux TEXT            usbmuxd listener address (in the form of either /path/to/unix/socket OR HOST:PORT). Can be specified via PYMOBILEDEVICE3_USBMUX envvar
  --udid TEXT              Device unique identifier. You may pass PYMOBILEDEVICE3_UDID environment variable to pass this option as well
  -v, --verbose
  -v, --verbose
  --color / --no-color     colorize output
  --source TEXT            The UDID of the source device.
  -h, --help               Show this message and exit.
````

**Additional context**

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
The password is a global device setting and not performed within the specific backup. If the device has a backup password, it will created encrypted backups, otherwise it won't. You can only use the info subcommand on decrypted backups, or you can just decrypt them yourself without any device using `pyiosbackup2`
