### ISSUE TITLE
Unable to mount DeveloperDiskImage

### ISSUE THREAD

**Issue by ElleBy** [doronz88/pymobiledevice3#152]
**Test environment**
- Big Sur 11.6.1
- iPhone 8 13.3.1

**Describe the bug**
When trying to mount the DeveloperDiskImage using 'pymobiledevice3 mounter mount' the following error occurs: ```KeyError: 'ImageSignature'```

**To Reproduce**
1. Connect a device via USB
2. Run pymobiledevice3 mounter mount

**Expected behavior**
Should mount the developer image

**Logs**
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/EB/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/__main__.py", line 46, in <module>
    cli()
  File "/Users/EB/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/__main__.py", line 42, in cli
    cli_commands()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/EB/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/mounter.py", line 135, in mounter_mount
    image_mounter.mount(image_type, signature)
  File "/Users/EB/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 66, in mount
    if self.is_image_mounted(image_type):
  File "/Users/EB/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 44, in is_image_mounted
    self.lookup_image(image_type)
  File "/Users/EB/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 35, in lookup_image
    signature = response['ImageSignature']
KeyError: 'ImageSignature'
```

**Comment by doronz88** [comment]
Thanks for the report! @ElleBy 

Reproduced the bug on iOS 13.3 and published a fix. Just released a new version with the fix:
[v1.13.1](https://github.com/doronz88/pymobiledevice3/releases/tag/v1.13.1)


Please update us if the issue is resolved.

**Comment by ElleBy** [comment]
Works perfectly now, thanks!
