### ISSUE TITLE
`backup` does not work on FreeBSD

### ISSUE THREAD

**Issue by CRKatri** [doronz88/pymobiledevice3#238]
**Test environment**
- Host OS version.
FreeBSD
- Target device model and iOS version.
iPhone Xr, iOS 15.4 dev beta 3

**Describe the bug**
Attempting to perform a backup will fail after a couple seconds.

**To Reproduce**
1. `pymobiledevice3 backup2 backup ./directory`
2. wait

**Expected behavior**
I expected a backup to be performed.

**Logs**
```
> pymobiledevice3 backup2 backup -v ./XR
2022-02-23 19:18:24 FreeBSDY540 pymobiledevice3.lockdown[7199] INFO Using iTunes pair record: <REDACTED-UDID>.plist
  0%|          | 0.0/100 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/usr/home/cameron/.local/bin/pymobiledevice3", line 8, in <module>
    sys.exit(cli())
  File "/usr/home/cameron/.local/lib/python3.8/site-packages/pymobiledevice3/__main__.py", line 50, in cli
    cli_commands()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/home/cameron/.local/lib/python3.8/site-packages/pymobiledevice3/cli/backup.py", line 47, in backup
    backup_client.backup(full=full, backup_directory=backup_directory, progress_callback=update_bar)
  File "/usr/home/cameron/.local/lib/python3.8/site-packages/pymobiledevice3/services/mobilebackup2.py", line 81, in backup
    dl.dl_loop(progress_callback)
  File "/usr/home/cameron/.local/lib/python3.8/site-packages/pymobiledevice3/services/device_link.py", line 59, in dl_loop
    raise PyMobileDevice3Exception(f'Device link error: {message[1]}')
pymobiledevice3.exceptions.PyMobileDevice3Exception: Device link error: {'ErrorCode': 205, 'ErrorDescription': 'Error reading backup properties (MBErrorDomain/205). Underlying error: Error deserializing properties: Cannot parse a NULL or zero-length data (MBErrorDomain/11).', 'MessageName': 'Response'}
```

**Comment by doronz88** [comment]
This is actually from the device. The backup2 protocol backups only deltas from a previous one - Meaning the first backup must be a full backup:

```shell
pymobiledevice3 backup2 backup --full ./directory
```
