### ISSUE TITLE
No iTunes pairing record found

### ISSUE THREAD

**Issue by exiva** [doronz88/pymobiledevice3#26]
Getting errors of no iTunes Pairing record found, even though it's paired with the system (shows up in Finder/Music) using macOS Big Sur 11.3. Do I need to disable SIP or something?

```
2021-04-30 14:09:02 MacBook-Pro.local root[29316] WARNING No iTunes pairing record found for device eb3480da40d4568698db8e6509447e67122bxxxx
2021-04-30 14:09:02 MacBook-Pro.local pymobiledevice3.lockdown[29316] WARNING Getting pair record from usbmuxd```

**Comment by doronz88** [comment]
Does it work anyway using the fallback to `usbmuxd`? Also, this requires access to `lockdown` folder:
https://blog.elcomsoft.com/2018/07/accessing-lockdown-files-on-macos/
Please update me so I can update the README.

**Comment by exiva** [comment]
> Does it work anyway using the fallback to usbmuxd?

No. This is the output I get.

```
2021-04-30 20:24:02 MacBook-Pro.local root[33959] WARNING No iTunes pairing record found for device eb3480da40d4568698db8e6509447e67122bxxxx
2021-04-30 20:24:02 MacBook-Pro.local pymobiledevice3.lockdown[33959] WARNING Getting pair record from usbmuxd
Traceback (most recent call last):
  File "/Users/travis/.local/share/virtualenvs/gasguage-KKmo3rgi/bin/pymobiledevice3", line 8, in <module>
    sys.exit(cli())
  File "/Users/travis/.local/share/virtualenvs/gasguage-KKmo3rgi/lib/python3.9/site-packages/pymobiledevice3/__main__.py", line 36, in cli
    cli_commands()
  File "/Users/travis/.local/share/virtualenvs/gasguage-KKmo3rgi/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/travis/.local/share/virtualenvs/gasguage-KKmo3rgi/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/travis/.local/share/virtualenvs/gasguage-KKmo3rgi/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/travis/.local/share/virtualenvs/gasguage-KKmo3rgi/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/travis/.local/share/virtualenvs/gasguage-KKmo3rgi/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/travis/.local/share/virtualenvs/gasguage-KKmo3rgi/lib/python3.9/site-packages/pymobiledevice3/cli/screenshot.py", line 17, in screenshot
    out.write(ScreenshotService(lockdown=lockdown).take_screenshot())
  File "/Users/travis/.local/share/virtualenvs/gasguage-KKmo3rgi/lib/python3.9/site-packages/pymobiledevice3/services/screenshot.py", line 13, in __init__
    self.service = self.lockdown.start_service(self.SERVICE_NAME)
  File "/Users/travis/.local/share/virtualenvs/gasguage-KKmo3rgi/lib/python3.9/site-packages/pymobiledevice3/lockdown.py", line 302, in start_service
    raise StartServiceError(response.get("Error"))
pymobiledevice3.exceptions.StartServiceError: InvalidService
```

I have libusbmuxd installed via brew.

It doesn't appear you can chmod lockdown on big sur, not without disabling SIP. I'll try that later.

```chmod: Unable to change file mode on /private/var/db/lockdown: Operation not permitted```

**Comment by exiva** [comment]
I should add, I have libimobiledevice installed, and those tools work fine.

**Comment by doronz88** [comment]
Actually according the the backtrace it seems the fallback to usbmuxd worked just fine. It's just that the service isn't running on the target ios device. This is the screenshot service that uses a service from the DeveloperDiskImage. Please make sure it's mounted using:

```shell
pymobiledevice3 mounter list
```

If not, you can do this using:
```shell
pymobiledevice3 mounter mount
```

This will attempt to find the correct DeveloperDiskImage and mount it for you.
Please let me know if its fixed. If so, I'll add more descriptive help message for the required services.

btw, what ios version are you using? I tested this on iOS 14.0-14.3.

**Comment by exiva** [comment]
Hm, weird. Seemed to spring into life once I did mounter list. 🤔 I'll ry some more and see what happens.

iOS 14.5

**Comment by doronz88** [comment]
Anyway this service can only be accessed using the DeveloperDiskImage. Maybe one on the commands you entered just before triggered the mount. 

I will move the screenshot option into the developer subcommand to reduce confusion and add documentation about this commands in the help section with a more descriptive exception explaining about the mount requirement for this commands. Thanks for the update and please let me know if there's something else :)

**Comment by doronz88** [comment]
The following changes have been made to clarify the usage of the sceenshot service:
https://github.com/doronz88/pymobiledevice3/pull/27/files

I consider this issue as solved and closing. Feel free to reopen if you still encounter problems :)
