### ISSUE TITLE
Failed to restore on Windows - Got an error sending RestoreLogo

### ISSUE THREAD

**Issue by deyvs02** [doronz88/pymobiledevice3#279]
iphone 7
ios 15.5
After the device is connected and starts the flashing process, the error occurs

```
**2022-06-20 07:58:58 DESKTOP-N7PN00F pymobiledevice3.restore.tss[256] INFO response successfully received
2022-06-20 07:58:58 DESKTOP-N7PN00F pymobiledevice3.restore.ipsw.component[256] DEBUG NOTE: No path for component iBEC in TSS, will fetch from build_identity
2022-06-20 07:58:58 DESKTOP-N7PN00F pymobiledevice3.restore.ipsw.component[256] DEBUG Extracting iBEC.d10.RELEASE.im4p (Firmware/dfu/iBEC.d10.RELEASE.im4p)
2022-06-20 07:58:58 DESKTOP-N7PN00F pymobiledevice3.restore.img4[256] INFO Personalizing IMG4 component iBEC...
2022-06-20 07:58:58 DESKTOP-N7PN00F pymobiledevice3.restore.img4[256] DEBUG Tag found
2022-06-20 07:58:58 DESKTOP-N7PN00F pymobiledevice3.restore.recovery[256] INFO Sending iBEC (555165 bytes)...
  0%|                                                                                           | 0/17 [00:00<?, ?it/s]
2022-06-20 07:58:58 DESKTOP-N7PN00F pymobiledevice3.restore.recovery[256] DEBUG waiting for device to reconnect...
2022-06-20 07:58:58 DESKTOP-N7PN00F pymobiledevice3.irecv[256] DEBUG set_configuration: 1
2022-06-20 07:58:58 DESKTOP-N7PN00F pymobiledevice3.irecv[256] DEBUG set_interface_altsetting: 0 0
2022-06-20 07:58:58 DESKTOP-N7PN00F pymobiledevice3.restore.recovery[256] DEBUG connected mode: Mode.RECOVERY_MODE_2
2022-06-20 07:58:58 DESKTOP-N7PN00F pymobiledevice3.restore.recovery[256] INFO device booted into recovery
2022-06-20 07:58:58 DESKTOP-N7PN00F pymobiledevice3.restore.recovery[256] INFO iBoot build-version=bytearray(b'iBoot-7459.120.62.0.3\x00')
2022-06-20 07:58:58 DESKTOP-N7PN00F pymobiledevice3.restore.recovery[256] INFO iBoot build-style=bytearray(b'RELEASE\x00')
2022-06-20 07:58:58 DESKTOP-N7PN00F pymobiledevice3.restore.ipsw.component[256] DEBUG NOTE: No path for component RestoreLogo in TSS, will fetch from build_identity
2022-06-20 07:58:58 DESKTOP-N7PN00F pymobiledevice3.restore.ipsw.component[256] DEBUG Extracting applelogo@2x~iphone.im4p (Firmware/all_flash/applelogo@2x~iphone.im4p)
2022-06-20 07:58:58 DESKTOP-N7PN00F pymobiledevice3.restore.img4[256] INFO Personalizing IMG4 component RestoreLogo...
2022-06-20 07:58:58 DESKTOP-N7PN00F pymobiledevice3.restore.img4[256] DEBUG Tag found
2022-06-20 07:58:58 DESKTOP-N7PN00F pymobiledevice3.restore.recovery[256] INFO Sending RestoreLogo (13547 bytes)...
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "F:\Downloads\walton\pymobiledevice3-master\pymobiledevice3-master\pymobiledevice3\cli\restore.py", line 157, in restore_update
    Restore(ipsw, device, tss=tss, behavior=behavior, ignore_fdr=ignore_fdr).update()
  File "F:\Downloads\walton\pymobiledevice3-master\pymobiledevice3-master\pymobiledevice3\restore\restore.py", line 1231, in update
    self.recovery.boot_ramdisk()
  File "F:\Downloads\walton\pymobiledevice3-master\pymobiledevice3-master\pymobiledevice3\restore\recovery.py", line 462, in boot_ramdisk
    self.enter_restore()
  File "F:\Downloads\walton\pymobiledevice3-master\pymobiledevice3-master\pymobiledevice3\restore\recovery.py", line 363, in enter_restore
    self.send_applelogo()
  File "F:\Downloads\walton\pymobiledevice3-master\pymobiledevice3-master\pymobiledevice3\restore\recovery.py", line 274, in send_applelogo
    self.send_component(component)
  File "F:\Downloads\walton\pymobiledevice3-master\pymobiledevice3-master\pymobiledevice3\restore\recovery.py", line 252, in send_component
    self.device.irecv.send_buffer(data)
  File "F:\Downloads\walton\pymobiledevice3-master\pymobiledevice3-master\pymobiledevice3\irecv.py", line 156, in send_buffer
    n = self._device.write(0x04, chunk, timeout=USB_TIMEOUT)
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\usb\core.py", line 986, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\usb\core.py", line 229, in setup_request
    self.managed_claim_interface(device, intf)
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\usb\core.py", line 178, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\usb\backend\libusb0.py", line 537, in claim_interface    _check(_lib.usb_claim_interface(dev_handle, intf))
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\usb\backend\libusb0.py", line 447, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'libusb0-dll:err [claim_interface] could not claim interface 0, invalid configuration 0\n'
Traceback (most recent call last):
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\Downloads\walton\pymobiledevice3-master\pymobiledevice3-master\pymobiledevice3\__main__.py", line 62, in <module>
    cli()
  File "F:\Downloads\walton\pymobiledevice3-master\pymobiledevice3-master\pymobiledevice3\__main__.py", line 52, in cli
    cli_commands()
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "F:\Downloads\walton\pymobiledevice3-master\pymobiledevice3-master\pymobiledevice3\cli\restore.py", line 157, in restore_update
    Restore(ipsw, device, tss=tss, behavior=behavior, ignore_fdr=ignore_fdr).update()
  File "F:\Downloads\walton\pymobiledevice3-master\pymobiledevice3-master\pymobiledevice3\restore\restore.py", line 1231, in update
    self.recovery.boot_ramdisk()
  File "F:\Downloads\walton\pymobiledevice3-master\pymobiledevice3-master\pymobiledevice3\restore\recovery.py", line 462, in boot_ramdisk
    self.enter_restore()
  File "F:\Downloads\walton\pymobiledevice3-master\pymobiledevice3-master\pymobiledevice3\restore\recovery.py", line 363, in enter_restore
    self.send_applelogo()
  File "F:\Downloads\walton\pymobiledevice3-master\pymobiledevice3-master\pymobiledevice3\restore\recovery.py", line 274, in send_applelogo
    self.send_component(component)
  File "F:\Downloads\walton\pymobiledevice3-master\pymobiledevice3-master\pymobiledevice3\restore\recovery.py", line 252, in send_component
    self.device.irecv.send_buffer(data)
  File "F:\Downloads\walton\pymobiledevice3-master\pymobiledevice3-master\pymobiledevice3\irecv.py", line 156, in send_buffer
    n = self._device.write(0x04, chunk, timeout=USB_TIMEOUT)
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\usb\core.py", line 986, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\usb\core.py", line 229, in setup_request
    self.managed_claim_interface(device, intf)
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\usb\core.py", line 178, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\usb\backend\libusb0.py", line 537, in claim_interface    _check(_lib.usb_claim_interface(dev_handle, intf))
  File "C:\FDTool\MTK\SP_Flash_Tool\Adb\Python39\lib\site-packages\usb\backend\libusb0.py", line 447, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'libusb0-dll:err [claim_interface] could not claim interface 0, invalid configuration 0\n'**
```

**Comment by doronz88** [comment]
Does the error occurs persistently? did you try running as administrator? this still seems `libusb` related.

**Comment by deyvs02** [comment]
Persistent error, libusb filters installed for the device
iphone SE
iphone 7

**Comment by doronz88** [comment]
I'm only certain this is a windows specific error. Did you try running it as administrator?

**Comment by deyvs02** [comment]
yes, I ran as **administrator**

**Comment by doronz88** [comment]
Closing due to inactivity — this 2022 Windows restore failure was never reproducible beyond running as admin, and the restore stack has changed substantially since. Please open a new issue if it reproduces on a current release.
