### ISSUE TITLE
Adding devmodctl to lockdown to enable developer mode for iOS 16

### ISSUE THREAD

**Issue by Valkhes** [doronz88/pymobiledevice3#301]
Hello,

In iOS 16, coming in a few months, the way to activate developer mode on an iPhone is changing. We will now have to go to Settings > Privacy & Security > Developer mode on the device, and activate a toggle, as explained in this article :

https://medium.com/@ant_one/enable-developer-mode-on-ios-16-20dd25b58fc0

A new tool will be available on macOS to enable the developer mode in cmdline, which is devmodctl.

On libimobiledevice github, there is a thread about iOS 16 here : https://github.com/libimobiledevice/libimobiledevice/issues/1333

Someone decided to add in the lockdown commands the tool to be able to enable developer mode using libimobiledevice, as seen here ( not in python but still able to see the implementation) : 
https://gist.github.com/nikias/262bd709c1651e0139eb9e3a2e2d33f4

I think this could also be a great addition to pymobiledevice3 to be able to activate developer mode for iOS 16. I think it may also be necessary to be in macOS Ventura to use this feature, as devmodctl is only available with Ventura for the moment.

Thanks a lot!

**Comment by doronz88** [comment]
```shell
pymobiledevice3 amfi enable-developer-mode
```

**Comment by Valkhes** [comment]
Thanks for the answer, I missed this command !

**Comment by truonggiang0710** [comment]
unsuccessfully on the iPhone 8 Plus
"/pymobiledevice3-master/pymobiledevice3/services/amfi.py", line 65, in enable_developer_mode_post_restart
    if not resp['success']:"

**Comment by doronz88** [comment]
Please provide a full backtrace so we can tell what the error is

**Comment by truonggiang0710** [comment]
@doronz88 it's here
```
python3 -m pymobiledevice3 amfi enable-developer-mode
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/MAC/Desktop/pymobiledevice3-master/pymobiledevice3/__main__.py", line 76, in <module>
    cli()
  File "/Users/MAC/Desktop/pymobiledevice3-master/pymobiledevice3/__main__.py", line 54, in cli
    cli_commands()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/MAC/Desktop/pymobiledevice3-master/pymobiledevice3/cli/amfi.py", line 26, in enable_developer_mode
    AmfiService(lockdown).enable_developer_mode()
  File "/Users/MAC/Desktop/pymobiledevice3-master/pymobiledevice3/services/amfi.py", line 59, in enable_developer_mode
    self.enable_developer_mode_post_restart()
  File "/Users/MAC/Desktop/pymobiledevice3-master/pymobiledevice3/services/amfi.py", line 65, in enable_developer_mode_post_restart
    if not resp['success']:
KeyError: 'success'
```

**Comment by doronz88** [comment]
Can you print what is returned instead into resp?
Also, is device password protected?

**Comment by truonggiang0710** [comment]
@doronz88 it shows: `{'Error': 'An unknown error has occured'}`
Full log as the below:
```
python3 -m pymobiledevice3 amfi enable-developer-mode
Debug {'Error': 'An unknown error has occured'}
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/MAC/Desktop/pymobiledevice3-master/pymobiledevice3/__main__.py", line 76, in <module>
    cli()
  File "/Users/MAC/Desktop/pymobiledevice3-master/pymobiledevice3/__main__.py", line 54, in cli
    cli_commands()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/MAC/Desktop/pymobiledevice3-master/pymobiledevice3/cli/amfi.py", line 26, in enable_developer_mode
    AmfiService(lockdown).enable_developer_mode()
  File "/Users/MAC/Desktop/pymobiledevice3-master/pymobiledevice3/services/amfi.py", line 59, in enable_developer_mode
    self.enable_developer_mode_post_restart()
  File "/Users/MAC/Desktop/pymobiledevice3-master/pymobiledevice3/services/amfi.py", line 67, in enable_developer_mode_post_restart
    if not resp['success']:
KeyError: 'success'
```

**Comment by truonggiang0710** [comment]
My phone is activated, it's on the Hello screen.

**Comment by doronz88** [comment]
Please verify the PR I just opened for treating this error:
https://github.com/doronz88/pymobiledevice3/pull/319

Basically, there's nothing we can actually do but better handling this exception. When device is on the "Hello screen", this means that `com.apple.purplebuddy` hasn't finished setting up the device yet and therefore this cannot be enabled automatically.

**Comment by truonggiang0710** [comment]
OK let me try.
