### ISSUE TITLE
MuxException: Invalid packet type received: Container

### ISSUE THREAD

**Issue by gershom-mx** [doronz88/pymobiledevice3#346]
Running on Linux Mint 21, using iOS 15.6. I have libimobiledevice running and have paired and used successfully. Using [usbmuxd2](https://github.com/tihmstar/usbmuxd2) for wifi capability.

I get the following error when running:
```
from pymobiledevice3.lockdown import LockdownClient
from pymobiledevice3.services.syslog import SyslogService
lockdown = LockdownClient()
```
```
Traceback (most recent call last):
  File '<stdin>', line 1, in <module>
  File "/home/x/.local/lib/python3.10/site-packages/pymobiledevice3/lockdown.py", line 126, in __init__
    self.service = ServiceConnection.create(self.medium, self.identifier, self.SERVICE_PORT,
  File "/home/x/.local/lib/python3.10/site-packages/pymobiledevice3/service_connection.py", line 104, in create
    return ServiceConnection.create_using_usbmux(identifier, port, connection_type=connection_type)
  File "/home/x/.local/lib/python3.10/site-packages/pymobiledevice3/service_connection.py", line 87, in create_using_usbmux
    target_device = select_device(udid, connection_type=connection_type)
  File "/home/x/.local/lib/python3.10/site-packages/pymobiledevice3/usbmux.py", line 381, in select_device
    for device in list_devices():
  File "/home/x/.local/lib/python3.10/site-packages/pymobiledevice3/usbmux.py", line 369, in list_devices
    mux.get_device_list(0.1)
  File "/home/x/.local/lib/python3.10/site-packages/pymobiledevice3/usbmux.py", line 227, in get_device_list
    self._receive_device_state_update()
  File "/home/x/.local/lib/python3.10/site-packages/pymobiledevice3/usbmux.py", line 293, in _receive_device_state_update
    raise MuxException(f'Invalid packet type received: {response}')
pymobiledevice3.exceptions.MuxException: Invalid packet type received: Container:
    header = Container:
        version = (enum) BINARY 0
        message = (enum) PLIST 8
        tag = 0
    data = b'<?xml version="1'... (truncated, total 840)
```

Am pretty new to python, so not very sure about where to start? Any ideas?

**Comment by doronz88** [comment]
Seems like usbmuxd2 is implementing the usbmuxd protocol in some non-standard way.
Can you install the package locally and add a print of the received data? The response packet is currently truncated

**Comment by gershom-mx** [comment]
Thank you for your response! Is this what is needed?
```
b'<?xml version="1.0" encoding="UTF-8"?>\n
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">\n
<dict>
  <key>MessageType</key>
    <string>Attached</string>
    <key>DeviceID</key>
    <integer>3</integer>
    <key>Properties</key>
      <dict>
        <key>DeviceID</key>
        <integer>3</integer>
        <key>ConnectionType</key>
        <string>Network</string>
        <key>EscapedFullServiceName</key>
        <string>84:ab:1a:94:f1:6c@fe80::86ab:1aff:fe94:f16c._apple-mobdev2._tcp</string>
       <key>NetworkAddress</key>
       <data>
       EAIAAMCoAGkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
       AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
      </data>
      <key>SerialNumber</key>
      <string>00008030-001E19C40369846E</string>
  </dict>
</dict>
</plist>'
```
If usbmuxd2 is the problem, would I lose wifi capability if I uninstalled it? Thank you!

**Comment by doronz88** [comment]
OK, I see what the problem is, which is a bit funny. The responses are with version `BINARY`, but the actual content is sent in the newer PLIST `version` as can be seen in your traceback:

```
    header = Container:
        version = (enum) BINARY 0
        message = (enum) PLIST 8
```

**Comment by doronz88** [comment]
@johnfgoodman can you verify if this PR solves the issue?
https://github.com/doronz88/pymobiledevice3/pull/347

I'm now checking the actual responses types instead of relying on the one the server put in the `version` field.
This is still a bug with usbmuxd2, but this tweak should also handle bad protocol implementations.

**Comment by doronz88** [comment]
@johnfgoodman I finally looked at `usbmuxd2` sources to figure the cause of the problem. They use the `msgtype` field to respond with the protocol version, instead of the version field. #348 should fix that. Can you verify?

**Comment by doronz88** [comment]
Closing this after @johnfgoodman reported the PR to fix the issue. It is now merged.

Thanks!
