### ISSUE TITLE
pymobiledevice3 can't run in command line, It will crash.

### ISSUE THREAD

**Issue by prife** [doronz88/pymobiledevice3#403]
**Test environment**
- Host OS version.
    - ProductName:    macOS（m1 macmin）
    - ProductVersion: 12.6.1
    - BuildVersion:   21G217
    - python 3.10.6

- Target device model and iOS version.
    - no need

**Describe the bug**

pymobiledevice3 can't run in command line, It will crash.

**To Reproduce**

1. python3 -m pip install pymobiledevice3
2. pymobiledevice3 -h 

```
$ pymobiledevice3 -h 

Traceback (most recent call last):
  File "/Users/wetest/.pyenv/versions/3.10.6/bin/pymobiledevice3", line 5, in <module>
    from pymobiledevice3.__main__ import cli
  File "/Users/wetest/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pymobiledevice3/__main__.py", line 14, in <module>
    from pymobiledevice3.cli.crash import cli as crash_cli
  File "/Users/wetest/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pymobiledevice3/cli/crash.py", line 5, in <module>
    from pymobiledevice3.services.crash_reports import CrashReportsManager, CrashReportsShell
  File "/Users/wetest/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pymobiledevice3/services/crash_reports.py", line 6, in <module>
    from pycrashreport.crash_report import get_crash_report_from_buf
  File "/Users/wetest/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pycrashreport/crash_report.py", line 11, in <module>
    from la_panic.panic_parser.kernel_panic import KernelPanic
  File "/Users/wetest/.pyenv/versions/3.10.6/lib/python3.10/site-packages/la_panic/panic_parser/kernel_panic.py", line 6, in <module>
    from la_panic.panic_parser.backtrace import Backtrace
  File "/Users/wetest/.pyenv/versions/3.10.6/lib/python3.10/site-packages/la_panic/panic_parser/backtrace.py", line 4, in <module>
    from la_panic.panic_parser.addresses.address_formater import reformat_register_value_to_fit
ModuleNotFoundError: No module named 'la_panic.panic_parser.addresses'
```

**Comment by prife** [comment]
la_panic 0.4.7 in pypi is invalid, there is no  la_panic.panic_parser.addresses. It seems that the author of la_panic submit a bad package.

```
pip install la-panic==0.4.6
```

will solve this issue.

**Comment by doronz88** [comment]
@prife thanks for letting us know! `la-panic` is technically a dependency of `pycrashreport`, which I'm the maintainer of. I'll make a release with your suggested fix but I also contacted `la-panic` author with the problem to not encounter it in the future.

**Comment by doronz88** [comment]
You can checkout the latest release (1.36.6) with the fix:
https://github.com/doronz88/pymobiledevice3/releases/tag/v1.36.6

And again, thanks for the update!

**Comment by prife** [comment]
v1.36.6 works, thanks for your hard working!
