### ISSUE TITLE
DtSimulateLocation init: InvalidService

### ISSUE THREAD

**Issue by yiguanxianyu** [doronz88/pymobiledevice3#412]
**Test environment**
- Host OS version. Windows 11 22H2
- Target device model and iOS version. iPad Air 3 iPadOS 15.7.2

**Describe the bug**
This error occurs if 
`image_mounter.mount('Developer', signature)` 
and
`location_simulator = DtSimulateLocation(lockdown=device_lockdown_client)`
are run in the same script.

**To Reproduce**
```python
from pymobiledevice3.lockdown import LockdownClient
from pymobiledevice3.services.mobile_image_mounter import MobileImageMounterService
from pymobiledevice3.services.simulate_location import DtSimulateLocation
from pymobiledevice3.usbmux import list_devices
from pathlib import Path

device = list_devices()[0]
device_lockdown_client = LockdownClient(device.serial)

image_mounter = MobileImageMounterService(lockdown=device_lockdown_client)
image = './Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/15.7/DeveloperDiskImage.dmg'
signature = image + '.signature'

image = Path(image).read_bytes()
signature = Path(signature).read_bytes()

image_mounter.upload_image('Developer', image, signature)
image_mounter.mount('Developer', signature)

location_simulator = DtSimulateLocation(lockdown=device_lockdown_client)
```

**Output**
```
Traceback (most recent call last):
  File "c:\Users\xianyu\Downloads\Compressed\PKUAutoRun-main\test.py", line 21, in <module>
    location_simulator = DtSimulateLocation(lockdown=device_lockdown_client)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Software\miniconda3\envs\pkuautorun\Lib\site-packages\pymobiledevice3\services\simulate_location.py", line 14, in __init__
    super().__init__(lockdown, self.SERVICE_NAME)
  File "C:\Software\miniconda3\envs\pkuautorun\Lib\site-packages\pymobiledevice3\services\base_service.py", line 19, in __init__
    service = start_service(service_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Software\miniconda3\envs\pkuautorun\Lib\site-packages\pymobiledevice3\lockdown.py", line 47, in _reconnect_on_remote_close
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Software\miniconda3\envs\pkuautorun\Lib\site-packages\pymobiledevice3\lockdown.py", line 522, in start_service
    attr = self.get_service_connection_attributes(name, escrow_bag=escrow_bag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Software\miniconda3\envs\pkuautorun\Lib\site-packages\pymobiledevice3\lockdown.py", line 509, in get_service_connection_attributes
    response = self._request('StartService', options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Software\miniconda3\envs\pkuautorun\Lib\site-packages\pymobiledevice3\lockdown.py", line 590, in _request
    raise exception_errors.get(error, LockdownError)(error)
pymobiledevice3.exceptions.InvalidServiceError: InvalidService
```

**Comment by doronz88** [comment]
I'm guessing that `lockdownd` hasn't yet reached the point it runs the services from the newly mounted DeveloperDiskImage. Did you try wait a little before trying to connect? If this solves the issue, then you should busy-wait till the service starts up

**Comment by yiguanxianyu** [comment]
You're right, I slept for 1s and it worked.
