### ISSUE TITLE
syslog collect crash

### ISSUE THREAD

**Issue by zytzjx** [doronz88/pymobiledevice3#478]
**Test environment**
- Windows 11(22621.1848)
- iPhone 14, iPhone7
- Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32

**Describe the bug**
Exception

**To Reproduce**
run this command(cmd.exe run as admin)
pymobiledevice3.exe syslog collect c:\Users\qa\Desktop\

**Logs**
Traceback (most recent call last):
  File "D:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Python310\Scripts\pymobiledevice3.exe\__main__.py", line 7, in <module>
  File "D:\Python310\lib\site-packages\pymobiledevice3\__main__.py", line 55, in cli
    cli_commands()
  File "D:\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Python310\lib\site-packages\pymobiledevice3\cli\syslog.py", line 176, in syslog_collect
    OsTraceService(lockdown=lockdown).collect(out, size_limit=size_limit, age_limit=age_limit, start_time=start_time)
  File "D:\Python310\lib\site-packages\pymobiledevice3\services\os_trace.py", line 119, in collect
    TarFile(tar.name).extractall(out)
  File "D:\Python310\lib\tarfile.py", line 1494, in __init__
    fileobj = bltn_open(name, self._mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\JEFFER~1\\AppData\\Local\\Temp\\tmpooeaz3ca'

**Comment by doronz88** [comment]
Please read the command help before reporting an issue.
You specified a dirname instead of a filename (which should have a logarchive file extension)
