### ISSUE TITLE
sysmon timeouts

### ISSUE THREAD

**Issue by ufx** [doronz88/pymobiledevice3#510]
**Test environment**
Host: macOS Ventura 13.4.1
Device: iOS 17 beta 4

**Describe the bug**
The `developer dvt sysmon process monitor 0` service fails with a timeout using the QUIC tunnel.

**To Reproduce**
1. Start a QUIC tunnel with `sudo python3 -m pymobiledevice3 remote start-quic-tunnel`.
2. Run `python3 -m pymobiledevice3 developer dvt sysmon process monitor 0 --rsd <rsd from above>`.
3. Observe timeout after a short wait.

**Expected behavior**
Monitor output emits.

**Logs**
```% python3 -m pymobiledevice3 developer dvt sysmon process monitor 0 --rsd fdba:992c:ecdd::1 57509
Traceback (most recent call last):
  File "/Users/chris/code/pymobiledevice3/pymobiledevice3/services/remote_server.py", line 344, in _recv_packet_fragments
    message = self.channel_messages[channel].get()
  File "/Users/chris/code/pymobiledevice3/pymobiledevice3/services/remote_server.py", line 173, in get
    return self._messages.get_nowait()
  File "/Applications/Xcode-beta.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/queue.py", line 199, in get_nowait
    return self.get(block=False)
  File "/Applications/Xcode-beta.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/queue.py", line 168, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Xcode-beta.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode-beta.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/chris/code/pymobiledevice3/pymobiledevice3/__main__.py", line 102, in <module>
    cli()
  File "/Users/chris/code/pymobiledevice3/pymobiledevice3/__main__.py", line 61, in cli
    cli_commands()
  File "/Users/chris/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chris/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/chris/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chris/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chris/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  [Previous line repeated 2 more times]
  File "/Users/chris/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chris/Library/Python/3.9/lib/python/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/chris/code/pymobiledevice3/pymobiledevice3/cli/developer.py", line 258, in sysmon_process_monitor
    with Sysmontap(dvt) as sysmon:
  File "/Users/chris/code/pymobiledevice3/pymobiledevice3/services/remote_server.py", line 387, in __enter__
    self.channel.receive_plist()
  File "/Users/chris/code/pymobiledevice3/pymobiledevice3/services/remote_server.py", line 143, in receive_plist
    return self._service.recv_plist(self)[0]
  File "/Users/chris/code/pymobiledevice3/pymobiledevice3/services/remote_server.py", line 313, in recv_plist
    data, aux = self.recv_message(channel)
  File "/Users/chris/code/pymobiledevice3/pymobiledevice3/services/remote_server.py", line 325, in recv_message
    packet_stream = self._recv_packet_fragments(channel)
  File "/Users/chris/code/pymobiledevice3/pymobiledevice3/services/remote_server.py", line 349, in _recv_packet_fragments
    data = self.service.recvall(dtx_message_header_struct.sizeof())
  File "/Users/chris/code/pymobiledevice3/pymobiledevice3/service_connection.py", line 134, in recvall
    chunk = self.recv(size - len(data))
  File "/Users/chris/code/pymobiledevice3/pymobiledevice3/service_connection.py", line 119, in recv
    return self.socket.recv(length)
TimeoutError: [Errno 60] Operation timed out
```

Thank you for your work on this, it's really helpful.

**Comment by doronz88** [comment]
Should be fixed as part of [v2.3.0](https://github.com/doronz88/pymobiledevice3/releases/tag/v2.3.0). Feel free to reopen if this error persists.
