### ISSUE TITLE
QUIC tunnel not staying up (iOS 17)

### ISSUE THREAD

**Issue by onlyzyz** [doronz88/pymobiledevice3#540]
**Test environment**
- Host OS version: MacOS 13.5.1, Python 3.8.8(Anaconda)
- Target device model and iOS version: iPhone 13 Pro with iOS 17 developer beta7(21A5312c)

**Describe the bug**
I installed pymobiledevice3(pip3) and openssl@3(brew), then created trusted tunnel and mounted DeveloperDiskImage, still can't launch app by its bundle name, but "pymobiledevice3 syslog live" can work

**To Reproduce**
1. Using SideStore to sideload LiveContainer app(free developer account)
2. Plug in my iPhone to Mac, they connect to the same WIFI
3. Open terminal and type `pymobiledevice3 developer dvt launch --rsd fdf5:cc6d:4d54::1 60079 -- com.kdt.livecontainer.8XRXBT4AMN`
4. Cannot open app. See Logs below

**Expected behavior**
Launch an app by its bundle name(I want to enable JIT).

**Logs**
```
(base) xxx@xxxdeMacBook-Pro ~ % pymobiledevice3 developer dvt launch --rsd fd04:e1c6:a471::1 60077 
com.kdt.livecontainer.8XRXBT4AMN Traceback (most recent call last): File 
"/Users/xxx/opt/anaconda3/bin/pymobiledevice3", line 8, in <module> sys.exit(cli()) File 
"/Users/xxx/opt/anaconda3/lib/python3.8/site-packages/pymobiledevice3/__main__.py", line 61, in cli cli_commands() File 
"/Users/xxx/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1157, in __call__ return self.main(*args, 
**kwargs) File "/Users/xxx/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1078, in main rv = 
self.invoke(ctx) File "/Users/xxx/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1688, in invoke return 
_process_result(sub_ctx.command.invoke(sub_ctx)) File "/Users/xxx/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1688, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File 
"/Users/xxx/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1686, in invoke sub_ctx = cmd.make_context(cmd_name, args, parent=ctx) File "/Users/xxx/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 943, in make_context self.parse_args(ctx, args) File "/Users/xxx/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1408, in parse_args value, args = param.handle_parse_result(ctx, opts, args) File "/Users/xxx/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 2400, in handle_parse_result value = self.process_value(ctx, value) File "/Users/xxx/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 2362, in process_value value = self.callback(ctx, self, value) File "/Users/xxx/opt/anaconda3/lib/python3.8/site-packages/pymobiledevice3/cli/cli_common.py", line 130, in rsd with RemoteServiceDiscoveryService(value) as rsd: File "/Users/xxx/opt/anaconda3/lib/python3.8/site-packages/pymobiledevice3/remote/remote_service_discovery.py", line 83, in __enter__ self.connect() File "/Users/xxx/opt/anaconda3/lib/python3.8/site-packages/pymobiledevice3/remote/remote_service_discovery.py", line 36, in connect self.service.connect() File "/Users/xxx/opt/anaconda3/lib/python3.8/site-packages/pymobiledevice3/remote/remotexpc.py", line 50, in connect self.sock = create_connection(self.address) File "/Users/xxx/opt/anaconda3/lib/python3.8/socket.py", line 808, in create_connection raise err File "/Users/xxx/opt/anaconda3/lib/python3.8/socket.py", line 796, in create_connection sock.connect(sa) OSError: [Errno 65] No route to host
```

**Additional context**
I've tried `pymobiledevice3 developer dvt screenshot --rsd fdf5:cc6d:4d54::1 60079 -- /path/to/screen.png` and got same error(`OSError: [Errno 65] No route to host`)

**Comment by doronz88** [comment]
Going by your error, the tunnel isn't open. Could it be you closed it before running the commnand? Also, verify it appears on ifconfig

**Comment by onlyzyz** [comment]
Thank you for your reply. Actually I didn't close the tunnel, I opened another terminal to run the next command. 
Right now I tried start a new quic tunnel and run ifconfig , but cannot find utun3. I think there must be something wrong with creating a new utun interface, any suggestions?
<img width="1144" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/127100328/659f4b58-1141-4d39-9380-eceb6a29dd3d">

**Comment by doronz88** [comment]
i couldn't reproduce a flow where the tunnel isn't created. it's very strange you even got an interface name without it being created in the first place. my only guess is to look at the macos logs and search for whatever is removing it

**Comment by onlyzyz** [comment]
Logs like "log stream --debug --info --predicate 'eventMessage LIKE "*Tunnel established*" OR eventMessage LIKE "*for server port*"'"?

**Comment by doronz88** [comment]
this was used to get the xcode tunnel details. you can connect through it just for sanity test, but i meant something like:
```shell
log stream --debug --info --predicate 'eventMessage LIKE "utun3"
```

**Comment by onlyzyz** [comment]
Utun3 changes to utun4, I opened console and searched for"utun4", here is all relevant logs, it seems nothing helpful there.
<img width="577" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/127100328/11d69187-260f-41ef-8704-b881f546710c">
15:46:49.388756+0800	kernel	if_updown: utun4 is not attached 15:46:49.388823+0800	kernel	ifnet_attach: Waiting for all kernel threads created for interface utun4 to get scheduled at least once. 15:46:49.388835+0800	kernel	ifnet_attach: All kernel threads created for interface utun4 have been scheduled at least once. Proceeding. 15:46:49.389070+0800	airportd	Driver Discovery: <airport[221]> _interfaceAdded: utun4 added. 15:46:49.417947+0800	airportd	Driver Discovery: <airport[221]> _interfaceAdded: utun4 is not an AirPort interface. 15:46:49.431298+0800	kernel	_dlil_attach_flowswitch_nexus: not attaching flowswitch to utun4 15:46:49.438693+0800	mDNSResponder	*** Network Configuration Change *** SC key: State:/Network/Interface/utun4/IPv6 15:46:49.456029+0800	mDNSResponder	*** Network Configuration Change *** SC key: State:/Network/Interface/utun4/IPv6 15:48:30.331784+0800	kernel	if_updown: utun4 is not attached 15:48:30.332248+0800	airportd	Driver Discovery: <airport[221]> _interfaceAdded: utun4 added. 15:48:30.331887+0800	kernel	utun4: attached with 0 suspended link-layer multicast membership(s) 15:48:30.331899+0800	kernel	ifnet_attach: Waiting for all kernel threads created for interface utun4 to get scheduled at least once. 15:48:30.331935+0800	kernel	ifnet_attach: All kernel threads created for interface utun4 have been scheduled at least once. Proceeding. 15:48:30.364017+0800	airportd	Driver Discovery: <airport[221]> _interfaceAdded: utun4 is not an AirPort interface. 15:48:30.366720+0800	kernel	_dlil_attach_flowswitch_nexus: not attaching flowswitch to utun4 15:48:30.370109+0800	mDNSResponder	*** Network Configuration Change *** SC key: State:/Network/Interface/utun4/IPv6 15:48:30.380845+0800	mDNSResponder	*** Network Configuration Change *** SC key: State:/Network/Interface/utun4/IPv6 15:52:54.943762+0800	kernel	if_updown: utun4 is not attached 15:52:54.943818+0800	kernel	utun4: attached with 0 suspended link-layer multicast membership(s) 15:52:54.943825+0800	kernel	ifnet_attach: All kernel threads created for interface utun4 have been scheduled at least once. Proceeding. 15:52:54.944050+0800	airportd	Driver Discovery: <airport[221]> _interfaceAdded: utun4 added. 15:52:54.955079+0800	kernel	_dlil_attach_flowswitch_nexus: not attaching flowswitch to utun4 15:52:54.958972+0800	mDNSResponder	*** Network Configuration Change *** SC key: State:/Network/Interface/utun4/IPv6 15:52:54.965554+0800	airportd	Driver Discovery: <airport[221]> _interfaceAdded: utun4 is not an AirPort interface. 15:52:54.966248+0800	mDNSResponder	*** Network Configuration Change *** SC key: State:/Network/Interface/utun4/IPv6 16:02:04.386913+0800	kernel	if_updown: utun4 is not attached 16:02:04.386981+0800	kernel	utun4: attached with 0 suspended link-layer multicast membership(s) 16:02:04.386986+0800	kernel	ifnet_attach: All kernel threads created for interface utun4 have been scheduled at least once. Proceeding. 16:02:04.387191+0800	airportd	Driver Discovery: <airport[221]> _interfaceAdded: utun4 added. 16:02:04.402287+0800	kernel	_dlil_attach_flowswitch_nexus: not attaching flowswitch to utun4 16:02:04.408812+0800	mDNSResponder	*** Network Configuration Change *** SC key: State:/Network/Interface/utun4/IPv6 16:02:04.417615+0800	airportd	Driver Discovery: <airport[221]> _interfaceAdded: utun4 is not an AirPort interface. 16:02:04.426732+0800	mDNSResponder	*** Network Configuration Change *** SC key: State:/Network/Interface/utun4/IPv6 16:09:09.054883+0800	kernel	if_updown: utun4 is not attached 16:09:09.054956+0800	kernel	utun4: attached with 0 suspended link-layer multicast membership(s) 16:09:09.054963+0800	kernel	ifnet_attach: Waiting for all kernel threads created for interface utun4 to get scheduled at least once. 16:09:09.054977+0800	kernel	ifnet_attach: All kernel threads created for interface utun4 have been scheduled at least once. Proceeding. 16:09:09.055246+0800	airportd	Driver Discovery: <airport[221]> _interfaceAdded: utun4 added. 16:09:09.077275+0800	kernel	_dlil_attach_flowswitch_nexus: not attaching flowswitch to utun4 16:09:09.083911+0800	airportd	Driver Discovery: <airport[221]> _interfaceAdded: utun4 is not an AirPort interface. 16:09:09.087919+0800	mDNSResponder	*** Network Configuration Change *** SC key: State:/Network/Interface/utun4/IPv6 16:09:09.098366+0800	mDNSResponder	*** Network Configuration Change *** SC key: State:/Network/Interface/utun4/IPv6

**Comment by doronz88** [comment]
@onlyzyz it's really very difficult to read the logs you're pasting. please use markdown formatting. this just looks like some random blob garbage instead of logs.
anyhow, i don't know why the interface is not up. it'll require further research. not something i can figure out without debugging.

**Comment by onlyzyz** [comment]
I'm so sorry, that was totally my fault.
This time was utun8.
<img width="1233" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/127100328/2c683964-b3bf-4430-8a28-427c98cad599">
Logs:
|Time                                  |Process|Message                                              |
|:------------------------:|:----:|:------------------------------|
|19:45:12.327027+0800|	kernel|if_updown: utun8 is not attached|
|19:45:12.327086+0800|	kernel|	utun8: attached with 0 suspended link-layer multicast membership(s)|
|19:45:12.327092+0800|	kernel|	ifnet_attach: Waiting for all kernel threads created for interface utun8 to get scheduled at least once.|
|19:45:12.327102+0800|	kernel|	ifnet_attach: All kernel threads created for interface utun8 have been scheduled at least once. Proceeding.|
|19:45:12.327270+0800|	airportd|	Driver Discovery: <airport[221]> _interfaceAdded: utun8 added.|
|19:45:12.355905+0800|	kernel|	_dlil_attach_flowswitch_nexus: not attaching flowswitch to utun8|
19:45:12.363085+0800|	mDNSResponder|	`***` Network Configuration Change `***` SC key: State:/Network/Interface/utun8/IPv6|
|19:45:12.374497+0800|	airportd|	Driver Discovery: <airport[221]> _interfaceAdded: utun8 is not an AirPort interface.|
|19:45:12.393333+0800|	mDNSResponder|	`***` Network Configuration Change `***` SC key: State:/Network/Interface/utun8/IPv6|

**Comment by doronz88** [comment]
I didn't mean you have to go through the trouble of formatting all of them into a table. Its enough to just use the "```" syntax. For reference, this is my output:
```
Filtering the log data using "composedMessage LIKE "*utun5*""
Timestamp                       Thread     Type        Activity             PID    TTL
2023-08-20 19:30:45.917210+0300 0x408d99   Default     0x0                  0      0    kernel: if_updown: utun5 is not attached
2023-08-20 19:30:45.917273+0300 0x408d99   Default     0x0                  0      0    kernel: utun5: attached with 0 suspended link-layer multicast membership(s)
2023-08-20 19:30:45.917280+0300 0x408d99   Default     0x0                  0      0    kernel: ifnet_attach: Waiting for all kernel threads created for interface utun5 to get scheduled at least once.
2023-08-20 19:30:45.917447+0300 0x408d99   Default     0x0                  0      0    kernel: ifnet_attach: All kernel threads created for interface utun5 have been scheduled at least once. Proceeding.
2023-08-20 19:30:45.919414+0300 0x956      Default     0x0                  180    0    airportd: (IO80211) [com.apple.WiFiManager:] Driver Discovery: <airport[180]> _interfaceAdded: utun5 added.
2023-08-20 19:30:45.918670+0300 0x408b2c   Info        0x0                  103    0    configd: [com.apple.SystemConfiguration:KernelEventMonitor] Process interface attach: utun5
2023-08-20 19:30:45.922872+0300 0x408c22   Debug       0x0                  103    0    configd: [com.apple.SystemConfiguration:SCDynamicStore] copy    :  9755 : State:/Network/Interface/utun5/Link
2023-08-20 19:30:45.922995+0300 0x408b2c   Debug       0x0                  103    0    configd: [com.apple.SystemConfiguration:KernelEventMonitor] Update interface link status: utun5: <removed>
2023-08-20 19:30:45.923196+0300 0x408c22   Debug       0x0                  103    0    configd: [com.apple.SystemConfiguration:SCDynamicStore] copy    :  9755 : State:/Network/Interface/utun5/LinkQuality
2023-08-20 19:30:45.923317+0300 0x408b2c   Debug       0x0                  103    0    configd: [com.apple.SystemConfiguration:KernelEventMonitor] Update interface link quality: utun5: <unknown>
2023-08-20 19:30:45.925587+0300 0x408c22   Debug       0x0                  103    0    configd: [com.apple.SystemConfiguration:SCDynamicStore] *remove :  9755 : State:/Network/Interface/utun5/Link
2023-08-20 19:30:45.925636+0300 0x408c22   Debug       0x0                  103    0    configd: [com.apple.SystemConfiguration:SCDynamicStore] *remove :  9755 : State:/Network/Interface/utun5/LinkQuality
2023-08-20 19:30:45.927343+0300 0x408de3   Default     0x0                  0      0    kernel: _dlil_attach_flowswitch_nexus: not attaching flowswitch to utun5
2023-08-20 19:30:45.927361+0300 0x408de3   Info        0x0                  0      0    kernel: Reinit'd ND information for interface utun5
2023-08-20 19:30:45.927364+0300 0x408de3   Info        0x0                  0      0    kernel: Reinit'd ND information for interface utun5
2023-08-20 19:30:45.936278+0300 0x408de5   Info        0x0                  103    0    configd: [com.apple.SystemConfiguration:KernelEventMonitor] Process protocol attach: utun5 (pf=30, n=1)
2023-08-20 19:30:45.939714+0300 0x408de5   Info        0x0                  103    0    configd: [com.apple.SystemConfiguration:KernelEventMonitor] Process IPv6 address change: utun5: 4
2023-08-20 19:30:45.940249+0300 0x408c22   Debug       0x0                  103    0    configd: [com.apple.SystemConfiguration:SCDynamicStore] copy    :  9755 : State:/Network/Interface/utun5/IPv6
2023-08-20 19:30:45.944314+0300 0x408de5   Debug       0x0                  103    0    configd: [com.apple.SystemConfiguration:KernelEventMonitor] Update interface configuration: State:/Network/Interface/utun5/IPv6: {
    Addresses =     (
        "fe80::ca89:f3ff:feee:9b7f",
        "fd1b:11be:38a1::2"
    );
    DestAddresses =     (
        "::ffff:ffff:ffff:ffff:0:0",
        "0:0:ffff:ffff::"
    );
    Flags =     (
        0,
        0
    );
    PrefixLength =     (
        64,
        64
    );
}
2023-08-20 19:30:45.946369+0300 0x408c22   Debug       0x0                  103    0    configd: [com.apple.SystemConfiguration:SCDynamicStore] *set    :  9755 : State:/Network/Interface/utun5/IPv6
2023-08-20 19:30:45.948216+0300 0x408b2c   Info        0x0                  103    0    configd: [com.apple.SystemConfiguration:LinkConfiguration] LowDataMode not supported with utun5
2023-08-20 19:30:45.951419+0300 0x408bee   Debug       0x0                  478    0    sharingd: (CoreUtils) [com.apple.CoreUtils:CUNetInterfaceMonitor] Network interfaces changed: [ "State:/Network/Interface/utun5/IPv6" ]
2023-08-20 19:30:45.952823+0300 0x408c1c   Debug       0x0                  155    0    AirPlayXPCHelper: (CoreUtils) [com.apple.CoreUtils:CUNetInterfaceMonitor] Network interfaces changed: [ "State:/Network/Interface/utun5/IPv6" ]
2023-08-20 19:30:45.951535+0300 0x408bf7   Debug       0x0                  420    0    rapportd: (CoreUtils) [com.apple.CoreUtils:CUNetInterfaceMonitor] Network interfaces changed: [ "State:/Network/Interface/utun5/IPv6" ]
2023-08-20 19:30:45.954610+0300 0xb52      Default     0x0                  295    0    mDNSResponder: [com.apple.mDNSResponder:Default] *** Network Configuration Change *** SC key: State:/Network/Interface/utun5/IPv6
2023-08-20 19:30:45.985385+0300 0x956      Default     0x0                  180    0    airportd: (IO80211) [com.apple.WiFiManager:] Driver Discovery: <airport[180]> _interfaceAdded: utun5 is not an AirPort interface.
2023-08-20 19:30:46.044815+0300 0x408de4   Debug       0x0                  103    0    configd: [com.apple.SystemConfiguration:SCDynamicStore] copy    : 54275 : State:/Network/Interface/utun5/AirPort
2023-08-20 19:30:46.044892+0300 0xbc6      Debug       0x0                  295    0    mDNSResponder: [com.apple.mDNSResponder:SPS] NetWakeInterface: returning false for utun5
2023-08-20 19:30:46.045084+0300 0x408de4   Debug       0x0                  103    0    configd: [com.apple.SystemConfiguration:SCDynamicStore] copy    : 54275 : State:/Network/Interface/utun5/AirPort
2023-08-20 19:30:46.045145+0300 0xbc6      Debug       0x0                  295    0    mDNSResponder: [com.apple.mDNSResponder:SPS] NetWakeInterface: returning false for utun5
2023-08-20 19:30:46.045485+0300 0xbc6      Default     0x0                  295    0    mDNSResponder: [com.apple.mDNSResponder:NAT] ClearInactiveInterfaces: Deleting utun5(28) <mask.hash: 'XI6Xjo6iGZxOUYSkr7CRgg=='> InterfaceID 0x1c(0x126877a00) <mask.hash: 'IZ+bbWWClUiNkqExJVoKZw=='>/64 Age 64 (Primary)
2023-08-20 19:30:46.045533+0300 0xbc6      Default     0x0                  295    0    mDNSResponder: [com.apple.mDNSResponder:NAT] ClearInactiveInterfaces: Deleting utun5(28) <mask.hash: 'XI6Xjo6iGZxOUYSkr7CRgg=='> InterfaceID 0x1c(0x126887000) <mask.hash: 'NRy9XeOV+2S2+Po6OVvKCw=='>/64 Age 64 (Primary)
2023-08-20 19:30:46.045557+0300 0xbc6      Default     0x0                  295    0    mDNSResponder: [com.apple.mDNSResponder:NAT] ClearInactiveInterfaces: Holding utun5(31) <mask.hash: 'XI6Xjo6iGZxOUYSkr7CRgg=='> InterfaceID 0x1f(0x125080800) <mask.hash: 'OO6MyOG8g09j95bv0tISuQ=='>/64 Age 34 (Primary)
2023-08-20 19:30:46.045586+0300 0xbc6      Default     0x0                  295    0    mDNSResponder: [com.apple.mDNSResponder:NAT] ClearInactiveInterfaces: Holding utun5(31) <mask.hash: 'XI6Xjo6iGZxOUYSkr7CRgg=='> InterfaceID 0x1f(0x1250b9800) <mask.hash: 'EuiAJkh2x+V3txzvuqiUBg=='>/64 Age 29 (Primary)
2023-08-20 19:30:46.045616+0300 0xbc6      Default     0x0                  295    0    mDNSResponder: [com.apple.mDNSResponder:mDNS] Interface not represented in list; marking active and retriggering queries - ifid: 31, ifname: utun5, ifaddr: <mask.hash: 'IZ+bbWWClUiNkqExJVoKZw=='>
2023-08-20 19:30:46.045689+0300 0xbc6      Default     0x0                  295    0    mDNSResponder: [com.apple.mDNSResponder:Default] SetupActiveInterfaces: Registered utun5 (31) BSSID <mask.hash: 'XI6Xjo6iGZxOUYSkr7CRgg=='> Struct addr 0x126879c00, primary 0x126879c00, <mask.hash: 'IZ+bbWWClUiNkqExJVoKZw=='>/64 (Flashing) (Occulting) (Primary)
2023-08-20 19:30:46.045711+0300 0xbc6      Default     0x0                  295    0    mDNSResponder: [com.apple.mDNSResponder:mDNS] Interface already represented in list - ifid: 31, ifname: utun5, ifaddr: <mask.hash: '6HvBj4B3D2NNb1kPPUjKwg=='>
2023-08-20 19:30:46.045750+0300 0xbc6      Default     0x0                  295    0    mDNSResponder: [com.apple.mDNSResponder:Default] SetupActiveInterfaces: Registered utun5 (31) BSSID <mask.hash: 'XI6Xjo6iGZxOUYSkr7CRgg=='> Struct addr 0x125084c00, primary 0x126879c00, <mask.hash: '6HvBj4B3D2NNb1kPPUjKwg=='>/64
2023-08-20 19:30:46.377925+0300 0x408b2c   Debug       0x0                  103    0    configd: [com.apple.SystemConfiguration:SCDynamicStore] *copy   : 131099 : State:/Network/Interface/utun5/IPv6
```

As you can see, you should be getting a `Update interface configuration` multiline message reporting the interface configuration. Could it be you missed some of the messages? 

This all still sounds like you have something that actively removes the interface after its being created.

**Comment by doronz88** [comment]
Actually, from your screenshot it looks like you have quite a lot of `utunX` interfaces. Could it be they were actually created and are the output of a previous run? Please verify if you see a new interface each time. Also, I think discussing this on [Discord](https://discord.gg/52mZGC3JXJ) will be easier

**Comment by doronz88** [comment]
I think I got the problem reproduced. I think it's python3.8 only. Can you verify?
Also, I believe latest release should produce an error instead

**Comment by doronz88** [comment]
Found the bug and got a working fix. This also requires a PR to be merged to `qh3`
