### ISSUE TITLE
TypeError when running pymobiledevice3 in CMD on Windows: readline.__doc__ return None

### ISSUE THREAD

**Issue by skyispainted** [doronz88/pymobiledevice3#555]
**Test environment**
- Windows10 22H2
- Python 3.8

**Describe the bug**
When I attempt to run the `pymobiledevice3` command, I encounter this error which appears to be related to the readline module.

**To Reproduce**
1. Run the command: `pymobiledevice3 -h`.

**Expected behavior**
I expected to successfully run the pymobiledevice3 command and retrieve information without encountering an error.

**Logs**
```
$ pymobiledevice3 -h
Traceback (most recent call last):
  File "C:\Users\Admin\miniconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\miniconda3\Scripts\pymobiledevice3.exe\__main__.py", line 4, in <module>
  File "C:\project\pymobiledevice3\pymobiledevice3\__main__.py", line 9, in <module>
    from pymobiledevice3.cli.afc import cli as afc_cli
  File "C:\project\pymobiledevice3\pymobiledevice3\cli\afc.py", line 5, in <module>
    from pymobiledevice3.services.afc import AfcService, AfcShell
  File "C:\project\pymobiledevice3\pymobiledevice3\services\afc.py", line 18, in <module>
    from cmd2 import Cmd, Cmd2ArgumentParser, with_argparser
  File "C:\Users\Admin\miniconda3\lib\site-packages\cmd2\__init__.py", line 53, in <module>
    from .cmd2 import Cmd
  File "C:\Users\Admin\miniconda3\lib\site-packages\cmd2\cmd2.py", line 125, in <module>
    from .rl_utils import (
  File "C:\Users\Admin\miniconda3\lib\site-packages\cmd2\rl_utils.py", line 144, in <module>
    if 'libedit' not in readline.__doc__:
TypeError: argument of type 'NoneType' is not iterable
```

**Additional context**

**Comment by skyispainted** [comment]
fixed by following https://github.com/python-cmd2/cmd2/issues/1212#issuecomment-1061848278
