### ISSUE TITLE
Mount developer image failed

### ISSUE THREAD

**Issue by tinybug** [doronz88/pymobiledevice3#564]
Hi, @doronz88 could you figure out why I get this error when I run `pymobiledevice3 mounter auto-mount`? 
I use iOS 17 run on the iPhone 12.

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 158, in query_personalization_manifest
    return response['ImageSignature']
KeyError: 'ImageSignature'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 206, in mount
    manifest = self.query_personalization_manifest('DeveloperDiskImage', hashlib.sha384(image).digest())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 160, in query_personalization_manifest
    raise MissingManifestError()
pymobiledevice3.exceptions.MissingManifestError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin//pymobiledevice3", line 8, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymobiledevice3/__main__.py", line 61, in cli
    cli_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymobiledevice3/cli/cli_common.py", line 78, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymobiledevice3/cli/mounter.py", line 121, in mounter_auto_mount
    auto_mount(service_provider, xcode=xcode, version=version)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 357, in auto_mount
    auto_mount_personalized(lockdown)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 350, in auto_mount_personalized
    PersonalizedImageMounter(lockdown=lockdown).mount(image, build_manifest, trustcache)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 209, in mount
    manifest = self.get_manifest_from_tss(plistlib.loads(build_manifest.read_bytes()))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 290, in get_manifest_from_tss
    response = request.send_receive()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymobiledevice3/restore/tss.py", line 771, in send_receive
    message = content.split(b'MESSAGE=', 1)[1].split(b'&', 1)[0].decode()
IndexError: list index out of range
```

This is what I get response in this function `query_personalization_manifest` https://github.com/doronz88/pymobiledevice3/blob/79750b78ba4a36fe2e208066588c94d7a7c424bc/pymobiledevice3/services/mobile_image_mounter.py#L149C24-L149C24

`
{'DetailedError': 'Error Domain=com.apple.MobileStorage.ErrorDomain Code=-2 "Failed to copy personalization manifest." UserInfo={NSLocalizedDescription=Failed to copy personalization manifest., NSUnderlyingError=0xdaea08cd0 {Error Domain=com.apple.MobileStorage.ErrorDomain Code=-2 "Failed to retrieve personalization manifest: Error Domain=com.apple.MobileStorage.ErrorDomain Code=-2 "Failed to find a cached manifest (im4m) for variant DeveloperDiskImage (personalization required)." UserInfo={NSLocalizedDescription=Failed to find a cached manifest (im4m) for variant DeveloperDiskImage (personalization required)., NSUnderlyingError=0xedeb041d0 {Error Domain=com.apple.MobileStorage.ErrorDomain Code=-2 "/private/var/containers/Shared/SystemGroup/2EA41DAD-A847-4323-8C38-9D7D9AD4BC1F/backingStore/DeveloperDiskImage/2B27BC2B935260D93787BE28660E4D6A3D177E738CA05A63E0FA18FBEB4F4615DCA315D03FBA564D6DA564B6AA6637DB.im4m does not exist." UserInfo={NSLocalizedDescription=/private/var/containers/Shared/SystemGroup/2EA41DAD-A847-4323-8C38-9D7D9AD4BC1F/backingStore/DeveloperDiskImage/2B27BC2B935260D93787BE28660E4D6A3D177E738CA05A63E0FA18FBEB4F4615DCA315D03FBA564D6DA564B6AA6637DB.im4m does not exist.}}}" UserInfo={NSLocalizedDescription=Failed to retrieve personalization manifest: Error Domain=com.apple.MobileStorage.ErrorDomain Code=-2 "Failed to find a cached manifest (im4m) for variant DeveloperDiskImage (personalization required)." UserInfo={NSLocalizedDescription=Failed to find a cached manifest (im4m) for variant DeveloperDiskImage (personalization required)., NSUnderlyingError=0xedeb041d0 {Error Domain=com.apple.MobileStorage.ErrorDomain Code=-2 "/private/var/containers/Shared/SystemGroup/2EA41DAD-A847-4323-8C38-9D7D9AD4BC1F/backingStore/DeveloperDiskImage/2B27BC2B935260D93787BE28660E4D6A3D177E738CA05A63E0FA18FBEB4F4615DCA315D03FBA564D6DA564B6AA6637DB.im4m does not exist." UserInfo={NSLocalizedDescription=/private/var/containers/Shared/SystemGroup/2EA41DAD-A847-4323-8C38-9D7D9AD4BC1F/backingStore/DeveloperDiskImage/2B27BC2B935260D93787BE28660E4D6A3D177E738CA05A63E0FA18FBEB4F4615DCA315D03FBA564D6DA564B6AA6637DB.im4m does not exist.}}}}}}', 'Error': 'InternalError'}
`

Thanks for your time to help.

**Comment by doronz88** [comment]
The second error you are getting is of a completely handled exception and it just iforms you that you don't have a manifest on-device.

The first error I wasn't able to reproduce, but it seems you are getting some weird HTTP error, as can be seen in the backtrace:

```
    message = content.split(b'MESSAGE=', 1)[1].split(b'&', 1)[0].decode()
```

Please print what `content` you are getting there

**Comment by tinybug** [comment]
Hi, @doronz88 Thanks for your answer. I use proxy on my mac, it makes the HTTP request error, it's getting normal when I close the proxy.

Many thanks for your hard work!
