### ISSUE TITLE
error while unbacking a backup

### ISSUE THREAD

**Issue by Silent-WindOPs** [doronz88/pymobiledevice3#573]
**Test environment**
- Pop!_OS 22.04 LTS"
- Iphone 12 V 16.6.1

**Describe the bug**
After taking a backup i try using the unback. it will create the folder _unback_ with the following sub dir 
var/db
var/installed/
var/keychains
var/Managed Preferences
var/mobile
var/MobileDevice
var/networkd
var/protected
var/root

After it will error out
  
 

**To Reproduce**
use the unback on a backup 

**Expected behavior**
finish the unbacking 

**Logs**
Traceback (most recent call last):
  File "pymobiledevice3", line 10, in <module>
    sys.exit(cli())
  File "/python3.10/site-packages/pymobiledevice3/__main__.py", line 61, in cli
    cli_commands()
  File "/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/lib/python3.10/site-packages/pymobiledevice3/cli/cli_common.py", line 78, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "/lib/python3.10/site-packages/pymobiledevice3/cli/backup.py", line 107, in unback
    backup_client.unback(backup_directory=backup_directory, password=password, source=source)
  File "/lib/python3.10/site-packages/pymobiledevice3/services/mobilebackup2.py", line 179, in unback
    with self.device_link(backup_dir) as dl:
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/lib/python3.10/site-packages/pymobiledevice3/services/mobilebackup2.py", line 361, in device_link
    dl.disconnect()
  File "/lib/python3.10/site-packages/pymobiledevice3/services/device_link.py", line 185, in disconnect
    self.service.send_plist(['DLMessageDisconnect', '___EmptyParameterString___'])
  File "/python3.10/site-packages/pymobiledevice3/service_connection.py", line 174, in send_plist
    return self.sendall(build_plist(d, endianity, fmt))
  File "/python3.10/site-packages/pymobiledevice3/service_connection.py", line 125, in sendall
    raise ConnectionTerminatedError from e
pymobiledevice3.exceptions.ConnectionTerminatedError

**Additional context**

**Comment by doronz88** [comment]
What were you trying to do? Restore the backup? What command exactly did you use?

**Comment by Silent-WindOPs** [comment]
i am trying to Convert all files in the backup to the correct directory hierarchy
pymobiledevice3 backup2 unback "path to the backup " " backuppass "

**Comment by matan1008** [comment]
Thanks for your feedback!
I was able to reproduce the issue :)
From the syslog, it seems that the process on the device crashes (Apple's bug?):
```
2023-08-22 14:43:06.603689 BackupAgent2{Foundation}[334] <Notice>: *** Assertion failure in -[MBDomain rootPath], MBDomain.m:507
2023-08-22 14:43:06.604212 BackupAgent2{CoreFoundation}[334] <Notice>: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Domain has no root path (uninstalled app?): SysContainerDomain-com.apple.adid'
*** First throw call stack:
(0x187438cb4 0x1804e03d0 0x181bd656c 0x1cd8cbd7c 0x104d788e0 0x104d81e40 0x104d6f6a0 0x104d6f464 0x18e8feeac 0x18e90e428 0x104d6f014 0x104d81cf4 0x104d575d4 0x104d569b8 0x20aaca340 0x20aacb41c 0x1874cc21c 0x1874c6148 0x1874c7e38 0x1874a9658 0x1874ae3ec 0x1874f0ea4 0x104d55e34 0x104d555f8 0x1a69aedec)
2023-08-22 14:43:06.604751 kernel{kernel}[0] <Notice>: BackupAgent2[334] Corpse allowed 1 of 5
2023-08-22 14:43:06.607929 ReportCrash{ReportCrash}[328] <Info>: osa_update: Pid 334 'BackupAgent2' CORPSE: Parsing KCData
2023-08-22 14:43:06.608395 ReportCrash{ReportCrash}[328] <Info>: osa_update: Pid 334 'BackupAgent2' CORPSE: Extracting
2023-08-22 14:43:07.446277 ReportCrash{ReportCrash}[328] <Info>: osa_update: Pid 334 'BackupAgent2' CORPSE: Capture Complete
2023-08-22 14:43:07.446358 ReportCrash{ReportCrash}[328] <Notice>: Formulating fatal 309 report for corpse[334] BackupAgent2
```

Alternatively, you can use [pyiosbackup](https://github.com/matan1008/pyiosbackup) which doesn't require a connected device

**Comment by Silent-WindOPs** [comment]
Thank you for your suggestion
