### ISSUE TITLE
house_arrest command

### ISSUE THREAD

**Issue by luc-git** [doronz88/pymobiledevice3#582]
I think it could be a good idea to add house_arrest command to be able to access file sharing apps files and directories

**Comment by doronz88** [comment]
You mean like: `pymobiledevice3 apps afc`?

**Comment by luc-git** [comment]
Oh yes sorry my bad but 

`python -m pymobiledevice3 apps afc com.keepassium.ios`

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\luc\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymobiledevice3\__main__.py", line 104, in <module>
    cli()
  File "C:\Users\luc\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymobiledevice3\__main__.py", line 61, in cli
    cli_commands()
  File "C:\Users\luc\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luc\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\luc\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luc\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luc\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luc\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luc\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymobiledevice3\cli\cli_common.py", line 78, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
TypeError: afc() got an unexpected keyword argument 'service_provider'
```

**Comment by doronz88** [comment]
It was a bug done by the ios17 refactor. Please check again with the PR I just opened, or wait till I merge it to master.

**Comment by luc-git** [comment]
It works thanks but 
`ERROR org.mozilla.ios.Firefox: InstallationLookupFailed`

to solve that you need to edit

https://github.com/doronz88/pymobiledevice3/blob/2cc278b41afcf44d2e580c9512f183c5dd7112d6/pymobiledevice3/services/house_arrest.py#L25

`cmd=VendContainer` to `cmd=VendDocuments`

but I have this error now : `EXCEPTION of type 'AfcException' occurred with message: [Errno PERM_DENIED] opcode: READ_DIR failed with status: PERM_DENIED`

**Comment by luc-git** [comment]
The explanation of why "VendContainer" doesn't works:

https://github.com/libimobiledevice/ifuse/issues/24#issuecomment-95279195

**Comment by luc-git** [comment]
So you can't list files of an appstore installed app

**Comment by doronz88** [comment]
From my understanding, they both shouldn't work on an AppStore app. Did you test the `VendDocuments` to see if this works?

**Comment by luc-git** [comment]
Yes I tested with `VendDocuments` and this throws error:

`EXCEPTION of type 'AfcException' occurred with message: [Errno PERM_DENIED] opcode: READ_DIR failed with status: PERM_DENIED`

**Comment by doronz88** [comment]
I actually didn't even know looking at the data of AppStore apps was a thing. Do you have a point of reference where this does work?

**Comment by doronz88** [comment]
I do get the following error message which leads me to believe this isn't supposed to work:

```
2023-09-27 23:06:14.858485 kernel{Sandbox}[0] <Error>: Sandbox: mobile_house_arrest(42876) deny(1) file-read-data /private/var/mobile/Containers/Data/Application/2EE79BE5-C510-4C11-873C-7F124CFBA4D9
```

**Comment by luc-git** [comment]
> I actually didn't even know looking at the data of AppStore apps was a thing. Do you have a point of reference where this does work?

I tested with https://github.com/libimobiledevice/ifuse/tree/master

it works with `ifuse --documents`

https://github.com/libimobiledevice/ifuse/blob/814a0e38050850937debd697fcfe6eca3de1b66f/src/ifuse.c#L628

https://github.com/libimobiledevice/ifuse/blob/814a0e38050850937debd697fcfe6eca3de1b66f/src/ifuse.c#L876

**Comment by doronz88** [comment]
From my understanding, this command from the AFC shell after the `VenDocuments` should fix it: `cd Documents`

**Comment by luc-git** [comment]
> From my understanding, this command from the AFC shell after the `VenDocuments` should fix it: `cd Documents`

Yes it works ok so all problems are fixed

**Comment by doronz88** [comment]
Good, I'll create a PR for it. Pretty funny you can still `cd` to other directories such as the `Library`, though `ls` cannot show them

**Comment by doronz88** [comment]
Can you verify the PR I just created achieves the desired behavior?
