### ISSUE TITLE
Failed to mount developer disk image

### ISSUE THREAD

**Issue by haoyu1999** [doronz88/pymobiledevice3#589]
**Test environment**
iPhone 15 Pro, iOS 17.0
pymobiledevice3==2.11.0

**Describe the bug**
Failed to mount developer disk image

**To Reproduce**
```
sudo python3 -m pymobiledevice3 mounter auto-mount --rsd fd64:xxxx:xxxx::1 6xxx2
```

**Logs**
```
./lib/python3.8/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "./lib/python3.8/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 155, in query_personalization_manifest
    return response['ImageSignature']
KeyError: 'ImageSignature'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./lib/python3.8/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 203, in mount
    manifest = self.query_personalization_manifest('DeveloperDiskImage', hashlib.sha384(image).digest())
  File "./lib/python3.8/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 157, in query_personalization_manifest
    raise MissingManifestError()
pymobiledevice3.exceptions.MissingManifestError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./lib/python3.8/site-packages/pymobiledevice3/__main__.py", line 104, in <module>
    cli()
  File "./lib/python3.8/site-packages/pymobiledevice3/__main__.py", line 61, in cli
    cli_commands()
  File "./lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "./lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "./lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "./lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "./lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "./lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "./lib/python3.8/site-packages/pymobiledevice3/cli/cli_common.py", line 78, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "./lib/python3.8/site-packages/pymobiledevice3/cli/mounter.py", line 122, in mounter_auto_mount
    auto_mount(service_provider, xcode=xcode, version=version)
  File "./lib/python3.8/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 354, in auto_mount
    auto_mount_personalized(lockdown)
  File "./lib/python3.8/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 347, in auto_mount_personalized
    PersonalizedImageMounter(lockdown=lockdown).mount(image, build_manifest, trustcache)
  File "./lib/python3.8/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 206, in mount
    manifest = self.get_manifest_from_tss(plistlib.loads(build_manifest.read_bytes()))
  File "./lib/python3.8/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 236, in get_manifest_from_tss
    manifest = build_identity['Manifest']
TypeError: 'NoneType' object is not subscriptable
```

**Additional context**
In `get_manifest_from_tss`, I have `board_id` = 4 and `chip_id` = 33072, but no matching `build_identity` was found in `build_manifest['BuildIdentities']`, thus `build_identity` is `None`.

**Comment by doronz88** [comment]
Updated the DeveloperDiskImage from latest XCode with all iPhone 15 variants. Should work now

**Comment by haoyu1999** [comment]
I've upgraded pymobiledevice3 but still doesn't work.

**Comment by haoyu1999** [comment]
Works after deleting cached files in home directory.
