### ISSUE TITLE
 Connection error on IOS 17

### ISSUE THREAD

**Issue by james-w-c** [doronz88/pymobiledevice3#598]
I got everything to work, but after I run the **sudo python3 main.py command** The website doesn't load, and on terminal it says connectionerror even though i have wiifi. anyone know a solution? this is specifically what i get:

Traceback (most recent call last):
File "/Users/james/kinesis/main.py", line 84, in
create_tunnel()
File "/Users/james/kinesis/main.py", line 79, in create_tunnel
asyncio.run(start_quic_tunnel(rsd))
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
return runner.run(main)
^^^^^^^^^^^^^^^^
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
return self._loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "/Users/james/kinesis/main.py", line 53, in start_quic_tunnel
async with service.start_quic_tunnel(private_key) as tunnel_result:
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 204, in aenter
return await anext(self.gen)
^^^^^^^^^^^^^^^^^^^^^
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 242, in start_quic_tunnel
async with aioquic_connect(
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 204, in aenter
return await anext(self.gen)
^^^^^^^^^^^^^^^^^^^^^
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/qh3/asyncio/client.py", line 97, in connect
await protocol.wait_connected()
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/qh3/asyncio/protocol.py", line 127, in wait_connected
await asyncio.shield(self._connected_waiter)
ConnectionError

**Comment by doronz88** [comment]
I don't even know what are you running

**Comment by ajlchiban** [comment]
Connection!??? Chosen for me

**Comment by doronz88** [comment]
Closing — this is failing inside a custom `main.py`, not bare-bones pymobiledevice3, and couldn't be reproduced from the information given. Please open a new issue with a minimal pymobiledevice3 CLI/code repro if the problem persists.
