### ISSUE TITLE
Springboard orientation TypeError

### ISSUE THREAD

**Issue by derkrasseleo** [doronz88/pymobiledevice3#607]
**Test environment**
- Arch Linux (6.5.7-arch1-1)
- iPhone XR model and iOS 17

**Describe the bug**
See log.

**To Reproduce**
`pymobiledevice3 springboard orientation`

**Expected behavior**
Get the orientation.

**Logs**
```
Traceback (most recent call last):
  File "/home/leo/.local/bin/pymobiledevice3", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/leo/.local/pipx/venvs/pymobiledevice3/lib/python3.11/site-packages/pymobiledevice3/__main__.py", line 61, in cli
    cli_commands()
  File "/home/leo/.local/pipx/venvs/pymobiledevice3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/.local/pipx/venvs/pymobiledevice3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/leo/.local/pipx/venvs/pymobiledevice3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/.local/pipx/venvs/pymobiledevice3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/.local/pipx/venvs/pymobiledevice3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/.local/pipx/venvs/pymobiledevice3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/.local/pipx/venvs/pymobiledevice3/lib/python3.11/site-packages/pymobiledevice3/cli/cli_common.py", line 78, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
TypeError: springboard_orientation() got an unexpected keyword argument 'service_provider'
```

**Comment by doronz88** [comment]
Thanks for the report!
A PR to fix that issue is very soon to be merged

**Comment by derkrasseleo** [comment]
Can confirm the fix! Thank you!
