### ISSUE TITLE
Cannot create quic tunne, StreamClosedError: Got RstStreamFrame(stream_id=1, flags=[]): error_code=5

### ISSUE THREAD

**Issue by XhivaW** [doronz88/pymobiledevice3#623]
**Test environment**
- Host OS version : Macbook Pro(M1 pro) / MacOs 14.0 (23A344)
- Target device model and iOS version : iPhone 13 mini / iOS 16.0.3 with develop mode off

**Describe the bug**
failed when trying `start-quic-tunnel` command
raise error as below:
```bash
> sudo python -u -m pymobiledevice3 remote start-quic-tunnel
Password:
2023-10-19 08:57:48 Shiva.local pymobiledevice3.remote.core_device_tunnel_service[7966] INFO Waiting user pairing consent
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/__main__.py", line 104, in <module>
    cli()
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/__main__.py", line 61, in cli
    cli_commands()
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/cli/remote.py", line 132, in cli_start_quic_tunnel
    asyncio.run(tunnel_task(rsd, secrets, script_mode), debug=True)
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/cli/remote.py", line 76, in tunnel_task
    async with start_quic_tunnel(service_provider, secrets=secrets) as tunnel_result:
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 577, in start_quic_tunnel
    with create_core_device_tunnel_service(service_provider, autopair=True) as service:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 568, in create_core_device_tunnel_service
    service.connect(autopair=autopair)
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 210, in connect
    self._pair()
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 286, in _pair
    self._create_remote_unlock()
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 421, in _create_remote_unlock
    response = self._send_receive_encrypted_request({'request': {'_0': {'createRemoteUnlockKey': {}}}})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 499, in _send_receive_encrypted_request
    response = self.service.send_receive_request({
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/remotexpc.py", line 104, in send_receive_request
    return self.receive_response()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/remotexpc.py", line 88, in receive_response
    frame = self._receive_next_data_frame()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/remotexpc.py", line 155, in _receive_next_data_frame
    raise StreamClosedError(f'Got {frame}')
pymobiledevice3.exceptions.StreamClosedError: Got RstStreamFrame(stream_id=1, flags=[]): error_code=5
```

**To Reproduce**

1. connect macbook and iphone with official typec-lightning cable
2. run `sudo python -u -m pymobiledevice3 remote start-quic-tunne`
3. See error

**Expected behavior**
create quic tunnel successfully

**Comment by XhivaW** [comment]
just found this [reply](https://github.com/doronz88/pymobiledevice3/issues/502#issuecomment-1653354458)

so it's necessary to have Xcode installed?

**Comment by XhivaW** [comment]
> just found this [reply](https://github.com/doronz88/pymobiledevice3/issues/502#issuecomment-1653354458)
> 
> so it's necessary to have Xcode installed?

negative
still get same error with Xcode installed ans running

**Comment by doronz88** [comment]
- Xcode is unrelated
- You are using iOS 16 - so you shouldn't use the quic-tunnel (very half-baked). It's meant for iOS 17 only.

**Comment by XhivaW** [comment]
> * Xcode is unrelated
> * You are using iOS 16 - so you shouldn't use the quic-tunnel (very half-baked). It's meant for iOS 17 only.

thx for reply
does the package support iOS 16? if so, which method should I use? I've checked docs but have no clue
