### ISSUE TITLE
OSError: [Errno 65] No route to host

### ISSUE THREAD

**Issue by morellexf13** [doronz88/pymobiledevice3#658]
I have this problem where I keep getting `OSError: [Errno 65] No route to host` when creating tunnels just on intel-based macs, the M1 model doesn't present this problem.

Example:
```
juan@MacBook-Air-de-Juan remote-xpc-tunnel % sudo ./remote-xpc-tunnel --device-udid 00008020-001E710414A1002E --tunnels 6 --close-tunnels-signal-file /Users/juan/Library/Apptim/remote-xpc-tunnel/close_addresses.signal --rsd-destination-path /Users/juan/Library/Apptim/remote-xpc-tunnel/rsd_addresses.json
2023-11-07 17:51:47 MacBook-Air-de-Juan.local root[14071] INFO Remote XPC Tunnel:  Running with root privileges
2023-11-07 17:51:47 MacBook-Air-de-Juan.local zeroconf[14071] WARNING Error with socket 5 (('fe80::aede:48ff:fe00:1122', 5353, 0, 5))): [Errno 65] No route to host
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 1056, in sendto
    self._sock.sendto(data, addr)
OSError: [Errno 65] No route to host
2023-11-07 17:51:49 MacBook-Air-de-Juan.local asyncio[14071] WARNING Executing <Task pending name='Task-48' coro=<RemoteXPC.start_quic_tunnel() running at remote-xpc-tunnel.py:71> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/futures.py:384, Task.task_wakeup()] created at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py:424> cb=[gather.<locals>._done_callback() at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py:718] created at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py:638> took 0.379 seconds
2023-11-07 17:51:50 MacBook-Air-de-Juan.local asyncio[14071] WARNING Executing <Task pending name='Task-49' coro=<RemoteXPC.start_quic_tunnel() running at remote-xpc-tunnel.py:71> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/futures.py:384, Task.task_wakeup()] created at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py:424> cb=[gather.<locals>._done_callback() at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py:718] created at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py:638> took 0.591 seconds
2023-11-07 17:51:50 MacBook-Air-de-Juan.local asyncio[14071] WARNING Executing <Task pending name='Task-50' coro=<RemoteXPC.start_quic_tunnel() running at remote-xpc-tunnel.py:71> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/futures.py:384, Task.task_wakeup()] created at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py:424> cb=[gather.<locals>._done_callback() at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py:718] created at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py:638> took 0.309 seconds
2023-11-07 17:51:51 MacBook-Air-de-Juan.local asyncio[14071] WARNING Executing <Task pending name='Task-51' coro=<RemoteXPC.start_quic_tunnel() running at remote-xpc-tunnel.py:71> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/futures.py:384, Task.task_wakeup()] created at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py:424> cb=[gather.<locals>._done_callback() at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py:718] created at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py:638> took 1.200 seconds
2023-11-07 17:51:52 MacBook-Air-de-Juan.local asyncio[14071] WARNING Executing <Task pending name='Task-52' coro=<RemoteXPC.start_quic_tunnel() running at remote-xpc-tunnel.py:71> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/futures.py:384, Task.task_wakeup()] created at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py:424> cb=[gather.<locals>._done_callback() at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py:718] created at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py:638> took 0.402 seconds
2023-11-07 17:51:53 MacBook-Air-de-Juan.local asyncio[14071] WARNING Executing <Task pending name='Task-53' coro=<RemoteXPC.start_quic_tunnel() running at remote-xpc-tunnel.py:71> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/futures.py:384, Task.task_wakeup()] created at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py:424> cb=[gather.<locals>._done_callback() at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py:718] created at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py:638> took 0.758 seconds
2023-11-07 17:51:53 MacBook-Air-de-Juan.local root[14071] INFO Remote XPC Tunnel:  --rsd fdb7:fa83:48b5::1 61029
2023-11-07 17:51:53 MacBook-Air-de-Juan.local root[14071] INFO Remote XPC Tunnel:  --rsd fd25:ea1:ebd2::1 61030
2023-11-07 17:51:53 MacBook-Air-de-Juan.local root[14071] INFO Remote XPC Tunnel:  --rsd fd3d:6867:1412::1 61031
2023-11-07 17:51:53 MacBook-Air-de-Juan.local root[14071] INFO Remote XPC Tunnel:  --rsd fdb6:8d5f:81f4::1 61032
2023-11-07 17:51:53 MacBook-Air-de-Juan.local root[14071] INFO Remote XPC Tunnel:  --rsd fdf5:1273:5535::1 61033
2023-11-07 17:51:53 MacBook-Air-de-Juan.local root[14071] INFO Remote XPC Tunnel:  --rsd fd29:92db:1b96::1 61034
```
The tunnels are created successfully but I have that traceback before and that affects the way I'm using this logic (freezed and called by using osascript).

Any hint?

PS: Python version being used is 3.10 for all the macbooks.

**Comment by netanelc305** [comment]
Hi , 

Have you tried [`Tunneld`](https://github.com/doronz88/pymobiledevice3#tunneld)?

**Comment by morellexf13** [comment]
> Hi ,
> 
> Have you tried [`Tunneld`](https://github.com/doronz88/pymobiledevice3#tunneld)?

Is there any way to list multiple tunnel addresses here? I need to use 6 different tunnels at the same time for the same device

<img width="789" alt="Captura de pantalla 2023-11-09 a la(s) 16 34 51" src="https://github.com/doronz88/pymobiledevice3/assets/73654994/04ea0230-c00d-4b2f-b635-e6c1e093d12c">

**Comment by netanelc305** [comment]
`Tunneld` currently supports only one tunnel per device, but you can feel free to submit PR.

**Comment by morellexf13** [comment]
> `Tunneld` currently supports only one tunnel per device, but you can feel free to submit PR.

Could you provide me a hint on how to obtain multiple addresses in the current code?

**Comment by tommy9517** [comment]
Hi, I also face this issue. 

```
Traceback (most recent call last):
  File "/usr/local/bin/pymobiledevice3", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/__main__.py", line 101, in main
    cli()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1686, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/cli/cli_common.py", line 52, in handle_parse_result
    return super().handle_parse_result(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/cli/cli_common.py", line 200, in rsd
    with RemoteServiceDiscoveryService(value) as rsd:
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/remote/remote_service_discovery.py", line 119, in __enter__
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/remote/remote_service_discovery.py", line 48, in connect
    self.service.connect()
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/remote/remotexpc.py", line 50, in connect
    self.sock = create_connection(self.address)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
OSError: [Errno 65] No route to host
```

I have tried Tunneld by this command `sudo python3 -m pymobiledevice3 remote tunneld` but when it was complete, there was no response after I inputted anything. So I pressed ctrl+c to leave, and it showed `Application shutdown complete` 

```
INFO:     Started server process [8606]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:5555 (Press CTRL+C to quit)
2023-12-08 10:16:40 userde-MBP pymobiledevice3.tunneld[8606] INFO Creating tunnel for fe80::dc54:eeff:fe31:2051%13
2023-12-08 10:16:40 userde-MBP pymobiledevice3.tunneld[8606] INFO Created tunnel --rsd fdd1:590d:cd26::1 58803
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
2023-12-08 10:16:52 userde-MBP pymobiledevice3.tunneld[8606] INFO Closing tunneld tasks...
INFO:     Application shutdown complete.
INFO:     Finished server process [8606]
```

I feel very confused about this issue. Can somebody give me some suggestions to solve this issue?

**Comment by Valkhes** [comment]
I get a similar issue on Intel too.
I have some ARM mac, but never saw this issue yet (that may be just because I use more the Intel mac).

It's not happening every time, but over time using a tunnel, sometimes when I need to recreate a RemoteServiceDiscoveryService, it happens.

When it happens, just stopping tunneld and relaunching to get a new tunnel help me fix this issue.
This is still quite annoying to have to relaunch the tunneld service, which seems to be closed.
I'm transitioning from QUIC to TCP too, I'm wondering if it may help with this issue. (could be a QUIC instability)

**Comment by doronz88** [comment]
Tunneld is designed to report errors while querying network adapters. That is the expected and normal behavior since it tries to browse all network adapters, which may include sometimes invalid ones.

It's a problem only if its failing to establish or remove tuunels. This logging of exceptions is only meant for debugging
