### ISSUE TITLE
_validate_pairingKeyError

### ISSUE THREAD

**Issue by trouble-bao** [doronz88/pymobiledevice3#662]
**Test environment**
- Mac13.4.1
- iphone12mini 17.2beta

**To Reproduce**
Trying to do something related to `start-quic-tunnel`

**Expected behavior**
will have to get the rsd host and port

**Logs**
Error Output: Traceback (most recent call last):  File "__main__.py", line 118, in <module>  File "__main__.py", line 76, in cli  File "click\core.py", line 1157, in __call__  File "click\core.py", line 1078, in main  File "click\core.py", line 1688, in invoke  File "click\core.py", line 1688, in invoke  File "click\core.py", line 1434, in invoke  File "click\core.py", line 783, in invoke  File "pymobiledevice3\cli\remote.py", line 270, in cli_start_quic_tunnel  File "asyncio\runners.py", line 44, in run  File "asyncio\base_events.py", line 641, in run_until_complete  File "pymobiledevice3\cli\remote.py", line 183, in tunnel_task  File "contextlib.py", line 199, in __aenter__  File "pymobiledevice3\remote\core_device_tunnel_service.py", line 650, in start_quic_tunnel  File "pymobiledevice3\remote\core_device_tunnel_service.py", line 637, in create_core_device_tunnel_service  File "pymobiledevice3\remote\core_device_tunnel_service.py", line 276, in connect  File "pymobiledevice3\remote\core_device_tunnel_service.py", line 509, in _validate_pairingKeyError: EnumIntegerString.new(3, 'PUBLIC_KEY')[1448] Failed to execute script '__main__' due to unhandled exception!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
This project has no `main.py` file. How did you produce this error?
This also means you were very misleading in your "describe the bug" so I corrected it

**Comment by trouble-bao** [comment]
> This project has no `main.py` file. How did you produce this error?

i copy __main__.py change the name, then i use the zsh to execute python3 main.py remote start-quic-tunnel

**Comment by doronz88** [comment]
Python doesn't work that way

**Comment by trouble-bao** [comment]
> Python doesn't work that way
but my another iphone is Ok iphonxr 17.1

**Comment by doronz88** [comment]
That is not a reproduceable bug. If you made changes to reproduce a bug, you should test it wasn't your change to produce it

**Comment by trouble-bao** [comment]
> That is not a reproduceable bug. If you made changes to reproduce a bug, you should test it wasn't your change to produce it

i only change the filename, and i clone new project to test that is also to produce this bug

  File "/Users/test/Documents/pythonCode/pymobiledevice3/__main__.py", line 104, in <module>
    cli()
  File "/Users/test/Documents/pythonCode/pymobiledevice3/__main__.py", line 60, in cli
    cli_commands()
  File "/Users/test/Library/Python/3.11/lib/python/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test/Library/Python/3.11/lib/python/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/test/Library/Python/3.11/lib/python/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test/Library/Python/3.11/lib/python/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test/Library/Python/3.11/lib/python/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test/Library/Python/3.11/lib/python/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test/Documents/pythonCode/pymobiledevice3/pymobiledevice3/cli/remote.py", line 131, in cli_start_quic_tunnel
    asyncio.run(start_quic_tunnel(rsd, secrets), debug=True)
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/test/Documents/pythonCode/pymobiledevice3/pymobiledevice3/cli/remote.py", line 74, in start_quic_tunnel
    with create_core_device_tunnel_service(service_provider, autopair=True) as service:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test/Documents/pythonCode/pymobiledevice3/pymobiledevice3/remote/core_device_tunnel_service.py", line 585, in create_core_device_tunnel_service
    service.connect(autopair=autopair)
  File "/Users/test/Documents/pythonCode/pymobiledevice3/pymobiledevice3/remote/core_device_tunnel_service.py", line 208, in connect
    if not self._validate_pairing():
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test/Documents/pythonCode/pymobiledevice3/pymobiledevice3/remote/core_device_tunnel_service.py", line 448, in _validate_pairing
    peer_public_key = X25519PublicKey.from_public_bytes(data[PairingDataComponentType.PUBLIC_KEY])
                                                        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: EnumIntegerString.new(3, 'PUBLIC_KEY')
