### ISSUE TITLE
Getting `KeyError` while accessing `PUBLIC_KEY` during QUIC tunnel

### ISSUE THREAD

**Issue by yanye666** [doronz88/pymobiledevice3#663]
nohup sudo python3 -u -m pymobiledevice3 remote start-quic-tunnel

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/__main__.py", line 125, in <module>
    cli()
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/__main__.py", line 77, in cli
    cli_commands()
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/cli/cli_common.py", line 101, in wrapper
    func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/cli/remote.py", line 159, in cli_start_quic_tunnel
    asyncio.run(tunnel_task(rsd, secrets, script_mode, max_idle_timeout=max_idle_timeout), debug=True)
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/cli/remote.py", line 97, in tunnel_task
    async with start_quic_tunnel(service_provider, secrets=secrets, max_idle_timeout=max_idle_timeout) as tunnel_result:
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 591, in start_quic_tunnel
    with create_core_device_tunnel_service(service_provider, autopair=True) as service:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 581, in create_core_device_tunnel_service
    service.connect(autopair=autopair)
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 212, in connect
    if not self._validate_pairing():
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 453, in _validate_pairing
    peer_public_key = X25519PublicKey.from_public_bytes(data[PairingDataComponentType.PUBLIC_KEY])
                                                        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: EnumIntegerString.new(3, 'PUBLIC_KEY')
```

**Comment by doronz88** [comment]
What iOS? Python? macOS?

**Comment by yanye666** [comment]
The system is macOS 14.2 Beta(23C5030f)
IOS 17

**Comment by trouble-bao** [comment]
> The system is macOS 14.2 Beta(23C5030f) IOS 17

my stystem macos 13.4.1 ios17.2beta. This error also occurred

**Comment by doronz88** [comment]
Unfortunately, I cannot reproduce this issue. You're welcome to try and provide steps to reproduce or create a PR that fixes it

**Comment by yanye666** [comment]
> nohup sudo python3 -u -m pymobiledevice3 remote start-quic-tunnel

execute 

nohup sudo python3 -u -m pymobiledevice3 remote start-quic-tunnel

**Comment by doronz88** [comment]
> > nohup sudo python3 -u -m pymobiledevice3 remote start-quic-tunnel
> 
> execute 
> 
> nohup sudo python3 -u -m pymobiledevice3 remote start-quic-tunnel
> 
> 

Please avoid spamming. The feature and this command works on every mac and ios I tested. Please provide actual steps or we cannot progress

**Comment by yanye666** [comment]
> > > nohup sudo python3 -u -m pymobiledevice3 remote start-quic-tunnel
> > 
> > 
> > execute
> > nohup sudo python3 -u -m pymobiledevice3 remote start-quic-tunnel
> 
> Please avoid spamming. The feature and this command works on every mac and ios I tested. Please provide actual steps or we cannot progress

I'm sorry, my steps are that simple.

1. Link to my iphone

2: execute this command
python3 -m pip install -U pymobiledevice3
sudo python3 -m pymobiledevice3 remote start-quic-tunnel
![image](https://github.com/doronz88/pymobiledevice3/assets/42414099/5079ffb8-11f0-45ec-a7f2-d78e5def3b85)

**Comment by RManLuo** [comment]
> The system is macOS 14.2 Beta(23C5030f) IOS 17

 Maybe you can try to downgrade to the official version instead of the beta version?

**Comment by doronz88** [comment]
What iOS device we you using? could it be iPhone 15 specific?

**Comment by yanye666** [comment]
> What iOS device we you using? could it be iPhone 15 specific?

iPhone 13promax  ios 17.2
