### ISSUE TITLE
usb.core.NoBackendError: No backend available

### ISSUE THREAD

**Issue by simonwanghub** [doronz88/pymobiledevice3#678]
PS C:\Windows\Scripts> pymobiledevice3.exe restore update -v "C:\Windows\Scripts\AppleTV5,3_17.1_21K69_Restore.ipsw"
2023-11-17 13:38:31 DESKTOP-QO0L4Q5 pymobiledevice3.cli.restore[8600] DEBUG searching among connected devices via lockdownd
2023-11-17 13:38:31 DESKTOP-QO0L4Q5 pymobiledevice3.cli.restore[8600] DEBUG found device
2023-11-17 13:38:31 DESKTOP-QO0L4Q5 pymobiledevice3.restore.restore[8600] INFO connected device: <ecid: 5143378497930278 hardware_model: j42dap image4-support: True>
2023-11-17 13:38:31 DESKTOP-QO0L4Q5 pymobiledevice3.restore.restore[8600] DEBUG scanning BuildManifest.plist for the correct BuildIdentity
2023-11-17 13:38:31 DESKTOP-QO0L4Q5 pymobiledevice3.restore.recovery[8600] INFO connected device: <ecid: 5143378497930278 hardware_model: j42dap image4-support: True>
2023-11-17 13:38:31 DESKTOP-QO0L4Q5 pymobiledevice3.restore.recovery[8600] DEBUG scanning BuildManifest.plist for the correct BuildIdentity
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.recovery[8600] INFO fetching TSS record
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry Ap,SystemVolumeCanonicalMetadata
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry AppleLogo
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry DeviceTree
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry KernelCache
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry LLB2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry OS
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry RecoveryMode
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry RestoreDeviceTree
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry RestoreKernelCache
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry RestoreLogo
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry RestoreRamDisk
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry RestoreSEP
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry RestoreTrustCache
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry SEP2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry StaticTrustCache
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry SystemVolume
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry ftap
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry ftsp
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry iBEC
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry iBSS
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry iBoot
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry rfta
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Applying restore request rules for entry rfts
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding ESEC=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG Adding EPRO=True to TSS entry
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] INFO Sending TSS request...
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] DEBUG {'@HostPlatformInfo': 'mac', '@VersionInfo': 'libauthinstall-973.0.1', '@UUID': 'DDD4D3AA-7FBE-4159-9DCE-7CE34027CF5A', 'ApECID': 5143378497930278, 'UniqueBuildID': b'e\t\xbf(\xb1-\xc4fu\xef\x04\x96\x18{]\xddd\xe9Q\x9f', 'ApChipID': 28672, 'ApBoardID': 52, 'ApSecurityDomain': 1, 'Ap,SystemVolumeCanonicalMetadata': {'Digest': b'\x7f\xd5\x9f\x82\x0eP\xbd`U\xc2\x1c\xf52\xa4\xa2\xc9\xc44;\xf7', 'Trusted': True, 'EPRO': True, 'ESEC': True}, 'AppleLogo': {'Digest': b'\xfd\xa3h\x97&\\k\x1a\xf1\x988\xce\x1dh^WE\xef\xd0\xc1', 'Trusted': True, 'EPRO': True, 'ESEC': True}, 'DeviceTree': {'Digest': b'\x01B\xe7:\xa6n\x81\x1b\x85Uu\ri\x01\xe6\x01\t\x92\xc6\xf3', 'Trusted': True, 'EPRO': True, 'ESEC': True}, 'KernelCache': {'Digest': b'g\xf7r\xe3\xdc\xef5\xb4\x05\xaa\xd0\x8f\xd5T\x9a\xb8\xdcG\x9d\xeb', 'Trusted': True, 'EPRO': True, 'ESEC': True}, 'LLB': {'BuildString': 'iBoot-10151.40.175~44', 'Digest': b'\xebB\x1a\xce\xec$\xeb\xfct\xa3\x99k\x8d\xda\xfd\xc00|\xa9\x83', 'Trusted': True, 'EPRO': True, 'ESEC': True}, 'OS': {'Digest': b"n\xba\x1aQ8'\xa1\x8f\xd9\xe6\xbc\xa1S@\xc3\xcac\r\xd5b", 'Trusted': True, 'EPRO': True, 'ESEC': True}, 'RecoveryMode': {'Digest': b'\xa8e=\x97c\x8d\x17\x14\xe5Pt\xff\x04\xff\x93k\x138^~', 'Trusted': True, 'EPRO': True, 'ESEC': True}, 'RestoreDeviceTree': {'Digest': b'=M\x9f\xf7\xd5\xf4\xc6\x9e\xf2!O\x97\xee\xc6\xe4\x02\x94\xca\xa6q', 'Trusted': True, 'EPRO': True, 'ESEC': True}, 'RestoreKernelCache': {'Digest': b'\x7fZ#\xda\x8bc\xab\xa4\xe4\x02\x14\xd9hy\x1e\x91\xcb#\xf1F', 'Trusted': True, 'EPRO': True, 'ESEC': True}, 'RestoreLogo': {'Digest': b'\xbcg\xe7Z\x1b\x1d\x10\xb8\xac\x91\xa0\x99F)1\xf3&\xc2\x00\x8b', 'Trusted': True, 'EPRO': True, 'ESEC': True}, 'RestoreRamDisk': {'Digest': b'G\xf1Q\ts\x97\x16\x03f\x00jZ\xd0\x9f\xab\xb6k\x1cB~', 'Trusted': True, 'EPRO': True, 'ESEC': True}, 'RestoreSEP': {'Digest': b'z\xe3u\xec\x9a\xe5\xf7\xa3\xe4S\xc2\xae%\xb5\x8b\x00i\x8e\x87M', 'Trusted': True, 'ESEC': True, 'EPRO': True}, 'RestoreTrustCache': {'Digest': b"\x06x\xc1\xfe\x19\xec\xcf\t'\xec\xa3\xac\xd4;j:k\xdd\xc8\x1d", 'Trusted': True, 'EPRO': True, 'ESEC': True}, 'SEP': {'Digest': b'\xe5D\xcb4\xc6\x05\xf0\x88\x03\xf3\xa3H\x1b\xf6\xac\xae\xc5\xe0\xfa\xce', 'Trusted': True, 'ESEC': True, 'EPRO': True}, 'StaticTrustCache': {'Digest': b'o\x81p\x9a)\xbe\xbc_>\x1e\x0c\xf1\xf1s>\xc1\x123d\x91', 'Trusted': True, 'EPRO': True, 'ESEC': True}, 'SystemVolume': {'Digest': b'JU\x15\x8d\x0e;\xfc\x92\xd3\xe2\x9c\x15\x16U\xbe\xec\x94\x1b\xef#', 'Trusted': True, 'EPRO': True, 'ESEC': True}, 'ftap': {'Trusted': True, 'EPRO': True, 'ESEC': True, 'Digest': b''}, 'ftsp': {'Trusted': True, 'ESEC': True, 'EPRO': True, 'Digest': b''}, 'iBEC': {'BuildString': 'iBoot-10151.40.175~44', 'Digest': b'\x9c\xd8o\xaf"\xa0>\xd4\x9e\x1fQ\xf7\xda\x1dp\x8f\xd0\x9cI\xab', 'Trusted': True, 'EPRO': True, 'ESEC': True}, 'iBSS': {'BuildString': 'iBoot-10151.40.175~44', 'Digest': b'\xae\xe4I:\xc3{ZY)\xcc\xf6\xf1\xc7\xa3\x14c\x01\x8b\xe4p', 'Trusted': True, 'EPRO': True, 'ESEC': True}, 'iBoot': {'Digest': b'\xc3\x1d\x8d\xe0\xf7\x1c\xf64\x92\t\x8e8C\x10\x97V{\xdf\xf0\xa0', 'Trusted': True, 'EPRO': True, 'ESEC': True}, 'rfta': {'Trusted': True, 'EPRO': True, 'ESEC': True, 'Digest': b''}, 'rfts': {'Trusted': True, 'ESEC': True, 'EPRO': True, 'Digest': b''}, 'ApNonce': b'\xe6\xa4>\xfe\x08\xa5\xbd\xf8\x9d\x10.(|*\xd7hK\xc5\xaeA', 'ApSecurityMode': True, 'ApProductionMode': True, 'SepNonce': b'\x01\x11?\x80\x88[\xf3\xb1\x85\x13~\x13f(\xd1_\xce\x0e[\x10', 'UID_MODE': False, '@ApImg4Ticket': True, '@BBTicket': True}
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.tss[8600] INFO response successfully received
2023-11-17 13:38:32 DESKTOP-QO0L4Q5 pymobiledevice3.restore.recovery[8600] INFO going into Recovery
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\pymobiledevice3\cli\restore.py", line 193, in restore_update
    Restore(ipsw, device, tss=tss, behavior=behavior, ignore_fdr=ignore_fdr).update()
  File "C:\Python\lib\site-packages\pymobiledevice3\restore\restore.py", line 1237, in update
    self.recovery.boot_ramdisk()
  File "C:\Python\lib\site-packages\pymobiledevice3\restore\recovery.py", line 456, in boot_ramdisk
    self.device.irecv = IRecv(self.device.ecid)
  File "C:\Python\lib\site-packages\pymobiledevice3\irecv.py", line 68, in __init__
    self._reinit(ecid=ecid, timeout=timeout, is_recovery=is_recovery)
  File "C:\Python\lib\site-packages\pymobiledevice3\irecv.py", line 240, in _reinit
    self._find(ecid=ecid, timeout=timeout, is_recovery=is_recovery)
  File "C:\Python\lib\site-packages\pymobiledevice3\irecv.py", line 264, in _find
    for device in find(find_all=True):
  File "C:\Python\lib\site-packages\usb\core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\pymobiledevice3.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "C:\Python\lib\site-packages\pymobiledevice3\__main__.py", line 61, in cli
    cli_commands()
  File "C:\Python\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Python\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Python\lib\site-packages\pymobiledevice3\cli\restore.py", line 193, in restore_update
    Restore(ipsw, device, tss=tss, behavior=behavior, ignore_fdr=ignore_fdr).update()
  File "C:\Python\lib\site-packages\pymobiledevice3\restore\restore.py", line 1237, in update
    self.recovery.boot_ramdisk()
  File "C:\Python\lib\site-packages\pymobiledevice3\restore\recovery.py", line 456, in boot_ramdisk
    self.device.irecv = IRecv(self.device.ecid)
  File "C:\Python\lib\site-packages\pymobiledevice3\irecv.py", line 68, in __init__
    self._reinit(ecid=ecid, timeout=timeout, is_recovery=is_recovery)
  File "C:\Python\lib\site-packages\pymobiledevice3\irecv.py", line 240, in _reinit
    self._find(ecid=ecid, timeout=timeout, is_recovery=is_recovery)
  File "C:\Python\lib\site-packages\pymobiledevice3\irecv.py", line 264, in _find
    for device in find(find_all=True):
  File "C:\Python\lib\site-packages\usb\core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

**Comment by doronz88** [comment]
As the error says, it could not find a USB backend. You're missing libusb drivers.
You can further read on here:
https://github.com/pyusb/pyusb

**Comment by simonwanghub** [comment]
It seems that it can't find USB after entering recovery mode. Everything is fine on my own macos.

**Comment by doronz88** [comment]
Added clarification the project's README regarding the installation of libusb
