### ISSUE TITLE
Error when executing "pymobiledevice3 usbmux list" [stream.tell() failed]

### ISSUE THREAD

**Issue by hscumbie** [doronz88/pymobiledevice3#705]
**Test environment**
- MacOS Sonoma 14.1.1 on MBA 2017 Running in Parallels VM
- iPhone 14 Pro Max running iOS 17.1.1
- Tried both Python3.9 and 3.12

**Describe the bug**
When running `pymobiledevice3 usbmux list` I get the following stack trace:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/construct/core.py", line 213, in stream_tell
    return stream.tell()
           ^^^^^^^^^^^
AttributeError: 'SafeStreamSocket' object has no attribute 'tell'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/pymobiledevice3", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pymobiledevice3/cli/usbmux.py", line 57, in usbmux_list
    for device in usbmux.list_devices(usbmux_address=usbmux_address):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 409, in list_devices
    mux = create_mux(usbmux_address=usbmux_address)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 405, in create_mux
    return MuxConnection.create(usbmux_address=usbmux_address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 180, in create
    response = usbmuxd_response.parse_stream(sock)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/construct/core.py", line 416, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/construct/core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/construct/core.py", line 4869, in _parse
    substream = BytesIOWithOffsets.from_reading(stream, length, path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/construct/core.py", line 241, in from_reading
    offset = stream_tell(stream, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/construct/core.py", line 215, in stream_tell
    raise StreamError("stream.tell() failed", path=path)
construct.core.StreamError: Error in path (parsing)
stream.tell() failed
`````

**To Reproduce**
1. Connect iPhone to MBA and set to pass through to Sonoma VM
2. Verify Sonoma VM sees the iPhone (By checking in finder that it shows up)
3. Launch terminal window and execute `pymobiledevice3 usbmux list`

**Additional context**
I'm using this to hopefully have the ability to enable JIT for the AltStore and its apps for faster emulation. Since my iPhone is on iOS 17, I see that this library is integral for getting JIT to work.

**Comment by vToMy** [comment]
Downgrade `construct` dependency. It seems the newest version broke something.

**Comment by sbgillett** [comment]
Also seeing this behaviour in `2.30.0`. It appears `construct 2.10.70` is the problem. The offending PR is [github.com/construct/construct/pull/1015](https://github.com/construct/construct/pull/1015). Downgrading `construct` to `2.10.69` resolves the problem for now.

**Comment by hscumbie** [comment]
@vToMy @sbgillett Downgrading `construct` to `2.10.69` fixed my issue as well. Thanks for the feedback.

**Comment by doronz88** [comment]
Added a PR that fixes this issue. Soon to be merged
