### ISSUE TITLE
Can't Execute auto-mount

### ISSUE THREAD

**Issue by JhinInn** [doronz88/pymobiledevice3#706]
**Test environment**
- macOS Ventura 13.3.
- iPhone 14 Pro, iOS 17.1.

**Describe the bug**
I executed `sudo pymobiledevice3 mounter auto-mount` 
and get this error below
```
Traceback (most recent call last):
  File "/Users/shion/opt/anaconda3/lib/python3.9/site-packages/construct/core.py", line 213, in stream_tell
    return stream.tell()
AttributeError: 'SafeStreamSocket' object has no attribute 'tell'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shion/opt/anaconda3/bin/pymobiledevice3", line 8, in <module>
    sys.exit(cli())
  File "/Users/shion/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/shion/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/shion/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/shion/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1686, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/Users/shion/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "/Users/shion/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/Users/shion/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/Users/shion/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
  File "/Users/shion/opt/anaconda3/lib/python3.9/site-packages/pymobiledevice3/cli/cli_common.py", line 177, in udid
    devices = select_devices_by_connection_type(connection_type='USB', usbmux_address=self.usbmux_address)
  File "/Users/shion/opt/anaconda3/lib/python3.9/site-packages/pymobiledevice3/usbmux.py", line 447, in select_devices_by_connection_type
    for device in list_devices(usbmux_address=usbmux_address):
  File "/Users/shion/opt/anaconda3/lib/python3.9/site-packages/pymobiledevice3/usbmux.py", line 409, in list_devices
    mux = create_mux(usbmux_address=usbmux_address)
  File "/Users/shion/opt/anaconda3/lib/python3.9/site-packages/pymobiledevice3/usbmux.py", line 405, in create_mux
    return MuxConnection.create(usbmux_address=usbmux_address)
  File "/Users/shion/opt/anaconda3/lib/python3.9/site-packages/pymobiledevice3/usbmux.py", line 180, in create
    response = usbmuxd_response.parse_stream(sock)
  File "/Users/shion/opt/anaconda3/lib/python3.9/site-packages/construct/core.py", line 416, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/Users/shion/opt/anaconda3/lib/python3.9/site-packages/construct/core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
  File "/Users/shion/opt/anaconda3/lib/python3.9/site-packages/construct/core.py", line 4869, in _parse
    substream = BytesIOWithOffsets.from_reading(stream, length, path)
  File "/Users/shion/opt/anaconda3/lib/python3.9/site-packages/construct/core.py", line 241, in from_reading
    offset = stream_tell(stream, path)
  File "/Users/shion/opt/anaconda3/lib/python3.9/site-packages/construct/core.py", line 215, in stream_tell
    raise StreamError("stream.tell() failed", path=path)
construct.core.StreamError: Error in path (parsing)
stream.tell() failed
```

**Expected behavior**
I think I can mount developer image

**Comment by JhinInn** [comment]
I read another issue and downgraded `construct` to 2.10.69.
However, new exception `pymobiledevice3.exceptions.DeveloperModeIsNotEnabledError` happened. I'm going to find out what happened. 
Issue closed.

**Comment by hscumbie** [comment]
Could it be that Developer Mode is not enabled in `Settings > Privacy and Security > Developer Mode` on your iPhone?

**Comment by doronz88** [comment]
```shell
pymobiledevice3 amfi enable-developer-mode
```

**Comment by JhinInn** [comment]
> Could it be that Developer Mode is not enabled in `Settings > Privacy and Security > Developer Mode` on your iPhone?

I realized the bug happened because i didnt reset my screen password
