### ISSUE TITLE
Device link error when creating backup on Windows

### ISSUE THREAD

**Issue by northloopforensics** [doronz88/pymobiledevice3#721]
**Test environment**
- Host OS version. 
- -Windows 10 Pro Build 19041
-
- Target device model and iOS version.
14 ProMax using 17.0.1
iPad 6 using iPadOS 16.5.1

**Describe the bug**
Using the Python API I ran into the following error when trying to create a backup on my Windows machine.

```
Traceback (most recent call last):
  File "C:\Users\CR\Desktop\PYTHON\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\CR\Desktop\MITE_PYNSIST -DP-10\src\pages\02_iOS_Triage.py", line 583, in <module>
    ios_backup(backuplocation)
  File "C:\Users\CR\Desktop\MITE_PYNSIST -DP-10\src\pages\02_iOS_Triage.py", line 522, in ios_backup
    backup_client.change_password(backup_directory=store_location,new="1234")
  File "C:\Users\CR\Desktop\PYTHON\lib\site-packages\pymobiledevice3\services\mobilebackup2.py", line 228, in change_password
    dl.dl_loop()
  File "C:\Users\CR\Desktop\PYTHON\lib\site-packages\pymobiledevice3\services\device_link.py", line 60, in dl_loop
    raise PyMobileDevice3Exception(f'Device link error: {message[1]}')
pymobiledevice3.exceptions.PyMobileDevice3Exception: Device link error: {'ErrorCode': 207, 'ErrorDescription': 'Invalid password (MBErrorDomain/207)', 'MessageName': 'Response'}
```

I duplicated it using the CLI v2.32.0
```
Traceback (most recent call last):
  File "C:\Users\CR\Downloads\pymobiledevice3-2.32.0\pymobiledevice3\__main__.py", line 149, in <module>
    main()
  File "C:\Users\CR\Downloads\pymobiledevice3-2.32.0\pymobiledevice3\__main__.py", line 101, in main
    cli()
  File "C:\Users\CR\Desktop\PYTHON\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\CR\Desktop\PYTHON\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\CR\Desktop\PYTHON\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\CR\Desktop\PYTHON\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\CR\Desktop\PYTHON\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\CR\Desktop\PYTHON\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\CR\Desktop\PYTHON\lib\site-packages\pymobiledevice3\cli\cli_common.py", line 134, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "C:\Users\CR\Desktop\PYTHON\lib\site-packages\pymobiledevice3\cli\backup.py", line 47, in backup
    backup_client.backup(full=full, backup_directory=backup_directory, progress_callback=update_bar)
  File "C:\Users\CR\Desktop\PYTHON\lib\site-packages\pymobiledevice3\services\mobilebackup2.py", line 87, in backup
    dl.dl_loop(progress_callback)
  File "C:\Users\CR\Desktop\PYTHON\lib\site-packages\pymobiledevice3\services\device_link.py", line 60, in dl_loop
    raise PyMobileDevice3Exception(f'Device link error: {message[1]}')
pymobiledevice3.exceptions.PyMobileDevice3Exception: Device link error: {'ErrorCode': 205, 'ErrorDescription': 'Error reading backup properties (MBErrorDomain/205). Underlying error: Error deserializing properties: Cannot parse a NULL or zero-length data (MBErrorDomain/11).', 'MessageName': 'Response'}
```

**To Reproduce**
1. Attach and Trust device on system
2. Command - `python __main__.py backup2 backup "C:"`
3.  See error

**Expected behavior**
Generation of a backup in assigned location

**Logs**
Please see traces above.  As always, thank you for the excellent work on this project!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
The first backup must be used with the `--full` option
