### ISSUE TITLE
subprocess-exited-with-error

### ISSUE THREAD

**Issue by tommy9517** [doronz88/pymobiledevice3#725]
Operating System: Windows 10
Python Version: 3.11.5
pip version: 23.3.1

While attempting to install it on Windows, I encountered an error. Does anyone know how to fix it?

```
C:\Users\user>python3` -m pip install -U pymobiledevice3
Collecting pymobiledevice3
  Using cached pymobiledevice3-2.33.0-py3-none-any.whl.metadata (62 kB)
Collecting construct>=2.9.29 (from pymobiledevice3)
  Using cached construct-2.10.70-py3-none-any.whl.metadata (4.2 kB)
Collecting asn1 (from pymobiledevice3)
  Using cached asn1-2.7.0-py2.py3-none-any.whl (10 kB)
Collecting click (from pymobiledevice3)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting coloredlogs (from pymobiledevice3)
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting IPython (from pymobiledevice3)
  Using cached ipython-8.18.1-py3-none-any.whl.metadata (6.0 kB)
Collecting bpylist2>=4.0.1 (from pymobiledevice3)
  Using cached bpylist2-4.1.1-py3-none-any.whl.metadata (5.5 kB)
Collecting pygments (from pymobiledevice3)
  Using cached pygments-2.17.2-py3-none-any.whl.metadata (2.6 kB)
Collecting hexdump (from pymobiledevice3)
  Using cached hexdump-3.3.zip (12 kB)
  Preparing metadata (setup.py) ... done
Collecting arrow (from pymobiledevice3)
  Using cached arrow-1.3.0-py3-none-any.whl.metadata (7.5 kB)
Collecting daemonize (from pymobiledevice3)
  Using cached daemonize-2.5.0-py2.py3-none-any.whl (5.2 kB)
Collecting gpxpy<1.6.0 (from pymobiledevice3)
  Using cached gpxpy-1.5.0.tar.gz (111 kB)
  Preparing metadata (setup.py) ... done
Collecting pykdebugparser>=1.2.4 (from pymobiledevice3)
  Using cached pykdebugparser-1.2.4-py2.py3-none-any.whl (92 kB)
Collecting pyusb>=1.2.1 (from pymobiledevice3)
  Using cached pyusb-1.2.1-py3-none-any.whl (58 kB)
Collecting tqdm (from pymobiledevice3)
  Using cached tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
Collecting requests (from pymobiledevice3)
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting xonsh (from pymobiledevice3)
  Using cached xonsh-0.14.3-py311-none-any.whl.metadata (7.5 kB)
Collecting parameter-decorators (from pymobiledevice3)
  Using cached parameter_decorators-0.0.2-py2.py3-none-any.whl (30 kB)
Collecting packaging (from pymobiledevice3)
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pygnuutils>=0.0.7 (from pymobiledevice3)
  Using cached pygnuutils-0.1.1-py3-none-any.whl.metadata (43 kB)
Collecting cryptography>=41.0.1 (from pymobiledevice3)
  Using cached cryptography-41.0.7.tar.gz (630 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      Collecting setuptools>=61.0.0
        Using cached setuptools-69.0.2-py3-none-any.whl.metadata (6.3 kB)
      Collecting wheel
        Using cached wheel-0.42.0-py3-none-any.whl.metadata (2.2 kB)
      Collecting cffi>=1.12
        Using cached cffi-1.16.0.tar.gz (512 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
        error: subprocess-exited-with-error

        Getting requirements to build wheel did not run successfully.
        exit code: 1

        [27 lines of output]
        Traceback (most recent call last):
          File "C:\msys64\mingw64\lib\python3.11\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
            main()
          File "C:\msys64\mingw64\lib\python3.11\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\msys64\mingw64\lib\python3.11\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
            return hook(config_settings)
                   ^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\user\AppData\Local\Temp\pip-build-env-phxa8nsv\overlay\lib\python3.11\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\user\AppData\Local\Temp\pip-build-env-phxa8nsv\overlay\lib\python3.11\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
            self.run_setup()
          File "C:\Users\user\AppData\Local\Temp\pip-build-env-phxa8nsv\overlay\lib\python3.11\site-packages\setuptools\build_meta.py", line 311, in run_setup
            exec(code, locals())
          File "<string>", line 126, in <module>
          File "<string>", line 105, in uses_msvc
          File "C:\Users\user\AppData\Local\Temp\pip-build-env-phxa8nsv\overlay\lib\python3.11\site-packages\setuptools\_distutils\command\config.py", line 223, in try_compile
            self._compile(body, headers, include_dirs, lang)
          File "C:\Users\user\AppData\Local\Temp\pip-build-env-phxa8nsv\overlay\lib\python3.11\site-packages\setuptools\_distutils\command\config.py", line 128, in _compile
            self.compiler.compile([src], include_dirs=include_dirs)
          File "C:\Users\user\AppData\Local\Temp\pip-build-env-phxa8nsv\overlay\lib\python3.11\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
            self.initialize()
          File "C:\Users\user\AppData\Local\Temp\pip-build-env-phxa8nsv\overlay\lib\python3.11\site-packages\setuptools\_distutils\_msvccompiler.py", line 246, in initialize
            raise DistutilsPlatformError(
        distutils.errors.DistutilsPlatformError: --plat-name must be one of ('win32', 'win-amd64', 'win-arm32', 'win-arm64')
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error

      Getting requirements to build wheel did not run successfully.
      exit code: 1

      See above for output.

      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by doronz88** [comment]
This is an issue with pip related to your specific platform. Looks like your windows installation identifies as a non-standard abi name
