### ISSUE TITLE
SafeStreamSocket incompatiable with construct >= v2.10.70

### ISSUE THREAD

**Issue by AnNEDoMini** [doronz88/pymobiledevice3#728]
**Test environment**
- Mac, Win, linux
- Any

**Describe the bug**
Any call to pmd with construct construct >= v2.10.70 gives and exception
`AttributeError: 'SafeStreamSocket' object has no attribute 'tell'`

**To Reproduce**
1. install latest construct (v >= 2.10.70)
2. call python -m pymobiledevice3 usbmux list
3. See error

**Expected behavior**
Should work fine

**Logs**
```
Traceback (most recent call last):
  File "/home/nuc/.local/lib/python3.11/site-packages/construct/core.py", line 213, in stream_tell
    return stream.tell()
           ^^^^^^^^^^^
AttributeError: 'SafeStreamSocket' object has no attribute 'tell'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/nuc/Photobox/readModel.py", line 6, in <module>
    devices = usbmux.list_devices()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/nuc/.local/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 394, in list_devices
    mux = create_mux()
          ^^^^^^^^^^^^
  File "/home/nuc/.local/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 390, in create_mux
    return MuxConnection.create()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nuc/.local/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 165, in create
    response = usbmuxd_response.parse_stream(sock)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nuc/.local/lib/python3.11/site-packages/construct/core.py", line 416, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nuc/.local/lib/python3.11/site-packages/construct/core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nuc/.local/lib/python3.11/site-packages/construct/core.py", line 4869, in _parse
    substream = BytesIOWithOffsets.from_reading(stream, length, path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nuc/.local/lib/python3.11/site-packages/construct/core.py", line 241, in from_reading
    offset = stream_tell(stream, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nuc/.local/lib/python3.11/site-packages/construct/core.py", line 215, in stream_tell
    raise StreamError("stream.tell() failed", path=path)
construct.core.StreamError: Error in path (parsing)
stream.tell() failed
```
**Additional context**
Can't figure out how to properly fix this. One way is stupid one: add tell mothod to `SafeStreamSocket` class
```
def tell(self);
    return 0
```
Second one: rollback construct to v2.10.68

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Duplicate of #705 and already released https://github.com/doronz88/pymobiledevice3/releases/tag/v2.30.1 to handle that
