### ISSUE TITLE
Unable to retrieve data in parallel

### ISSUE THREAD

**Issue by cnyy99** [doronz88/pymobiledevice3#751]
**Test environment**
- Host OS version.
MacOS 13.5 (22G74)

- Target device model and iOS version.
iPhone12,8 13.5.1(17F80)

**Describe the bug**
Cannot run multiple data fetches at the same time, such as Graphics and Notifications

**To Reproduce**
Run the following code

```python3
def tes1(dvt):
    with Graphics(dvt) as graphics:
        for stats in graphics:
            logger.info(stats)


def tes2(dvt):
    with Notifications(dvt) as graphics:
        for stats in graphics:
            logger.info(stats)


def tes():
    lockdown = create_using_usbmux()
    dvt = DvtSecureSocketProxyService(lockdown=lockdown)
    dvt.__enter__()
    threading.Thread(target=tes1, args=(dvt,)).start()
    time.sleep(2)
    threading.Thread(target=tes2, args=(dvt,)).start()


if __name__ == '__main__':
    tes()
    time.sleep(30)

```
**Expected behavior**
Normal acquisition of multiple data at the same time
**Logs**
```
2023-12-26 18:33:34.871 | INFO     | __main__:tes1:106 - {'stdTextureCreationBytes': 0, 'XRVideoCardRunTimeStamp': 437, 'SplitSceneCount': 0, 'Device Utilization %': 0, 'finishGLWaitTime': 0, 'recoveryCount': 0, 'gartUsedBytes': 29868032, 'gartMapInBytesPerSample': 65536, 'IOGLBundleName': 'Built-In', 'CoreAnimationFramesPerSecond': 0, 'freeToAllocGPUAddressWaitTime': 0, 'TiledSceneBytes': 196608, 'Renderer Utilization %': 0, 'Tiler Utilization %': 0, 'oolTextureCreationBytes': 0, 'gartMapOutBytesPerSample': 65536, 'contextGLCount': 0, 'agpTextureCreationBytes': 0, 'CommandBufferRenderCount': 14298, 'iosurfaceTextureCreationBytes': 0, 'textureCount': 362, 'hardwareWaitTime': 0, 'agprefTextureCreationBytes': 65536}
2023-12-26 18:33:35.885 | INFO     | __main__:tes1:106 - {'stdTextureCreationBytes': 0, 'XRVideoCardRunTimeStamp': 1010540, 'SplitSceneCount': 0, 'Device Utilization %': 0, 'finishGLWaitTime': 0, 'recoveryCount': 0, 'gartUsedBytes': 29868032, 'gartMapInBytesPerSample': 0, 'IOGLBundleName': 'Built-In', 'CoreAnimationFramesPerSecond': 60, 'freeToAllocGPUAddressWaitTime': 0, 'TiledSceneBytes': 131072, 'Renderer Utilization %': 0, 'Tiler Utilization %': 0, 'oolTextureCreationBytes': 0, 'gartMapOutBytesPerSample': 0, 'contextGLCount': 0, 'agpTextureCreationBytes': 0, 'CommandBufferRenderCount': 60, 'iosurfaceTextureCreationBytes': 0, 'textureCount': 362, 'hardwareWaitTime': 0, 'agprefTextureCreationBytes': 0}
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/chennan/code/pymobiledevice3/pymobiledevice3/services/remote_server.py", line 347, in _recv_packet_fragments
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/chennan/code/pymobiledevice3/pymobiledevice3/services/remote_server.py", line 347, in _recv_packet_fragments
    message = self.channel_messages[channel].get()
  File "/Users/chennan/code/pymobiledevice3/pymobiledevice3/services/remote_server.py", line 176, in get
    message = self.channel_messages[channel].get()
  File "/Users/chennan/code/pymobiledevice3/pymobiledevice3/services/remote_server.py", line 176, in get
    return self._messages.get_nowait()
    return self._messages.get_nowait()
  File "/Users/chennan/.pyenv/versions/3.9.18/lib/python3.9/queue.py", line 199, in get_nowait
  File "/Users/chennan/.pyenv/versions/3.9.18/lib/python3.9/queue.py", line 199, in get_nowait
    return self.get(block=False)
  File "/Users/chennan/.pyenv/versions/3.9.18/lib/python3.9/queue.py", line 168, in get
    return self.get(block=False)
  File "/Users/chennan/.pyenv/versions/3.9.18/lib/python3.9/queue.py", line 168, in get
    raise Empty
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chennan/.pyenv/versions/3.9.18/lib/python3.9/threading.py", line 980, in _bootstrap_inner
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chennan/.pyenv/versions/3.9.18/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Users/chennan/.pyenv/versions/3.9.18/lib/python3.9/threading.py", line 917, in run
    self.run()
  File "/Users/chennan/.pyenv/versions/3.9.18/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/chennan/code/pymobiledevice3/test.py", line 105, in tes1
    self._target(*self._args, **self._kwargs)
  File "/Users/chennan/code/pymobiledevice3/test.py", line 110, in tes2
    for stats in graphics:
  File "/Users/chennan/code/pymobiledevice3/pymobiledevice3/services/dvt/instruments/graphics.py", line 20, in __iter__
    with Sysmontap(dvt) as graphics:
  File "/Users/chennan/code/pymobiledevice3/pymobiledevice3/services/dvt/instruments/sysmontap.py", line 13, in __init__
    yield self._channel.receive_plist()
  File "/Users/chennan/code/pymobiledevice3/pymobiledevice3/services/remote_server.py", line 146, in receive_plist
    self._device_info = DeviceInfo(dvt)
  File "/Users/chennan/code/pymobiledevice3/pymobiledevice3/services/dvt/instruments/device_info.py", line 13, in __init__
    return self._service.recv_plist(self)[0]
  File "/Users/chennan/code/pymobiledevice3/pymobiledevice3/services/remote_server.py", line 316, in recv_plist
    data, aux = self.recv_message(channel)
  File "/Users/chennan/code/pymobiledevice3/pymobiledevice3/services/remote_server.py", line 328, in recv_message
    packet_stream = self._recv_packet_fragments(channel)
  File "/Users/chennan/code/pymobiledevice3/pymobiledevice3/services/remote_server.py", line 353, in _recv_packet_fragments
    mheader = dtx_message_header_struct.parse(data)
  File "/Users/chennan/code/pymobiledevice3/venv/lib/python3.9/site-packages/construct/core.py", line 404, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/Users/chennan/code/pymobiledevice3/venv/lib/python3.9/site-packages/construct/core.py", line 416, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/Users/chennan/code/pymobiledevice3/venv/lib/python3.9/site-packages/construct/core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
  File "/Users/chennan/code/pymobiledevice3/venv/lib/python3.9/site-packages/construct/core.py", line 2236, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/Users/chennan/code/pymobiledevice3/venv/lib/python3.9/site-packages/construct/core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
  File "/Users/chennan/code/pymobiledevice3/venv/lib/python3.9/site-packages/construct/core.py", line 2770, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/Users/chennan/code/pymobiledevice3/venv/lib/python3.9/site-packages/construct/core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
  File "/Users/chennan/code/pymobiledevice3/venv/lib/python3.9/site-packages/construct/core.py", line 2845, in _parse
    raise ConstError(f"parsing expected {repr(self.value)} but parsed {repr(obj)}", path=path)
construct.core.ConstError: Error in path (parsing) -> magic
parsing expected 524114809 but parsed 3
    self._channel = dvt.make_channel(self.IDENTIFIER)
  File "/Users/chennan/code/pymobiledevice3/pymobiledevice3/services/remote_server.py", line 285, in make_channel
    ret, aux = self.recv_plist()
  File "/Users/chennan/code/pymobiledevice3/pymobiledevice3/services/remote_server.py", line 316, in recv_plist
    data, aux = self.recv_message(channel)
  File "/Users/chennan/code/pymobiledevice3/pymobiledevice3/services/remote_server.py", line 328, in recv_message
    packet_stream = self._recv_packet_fragments(channel)
  File "/Users/chennan/code/pymobiledevice3/pymobiledevice3/services/remote_server.py", line 353, in _recv_packet_fragments
    mheader = dtx_message_header_struct.parse(data)
  File "/Users/chennan/code/pymobiledevice3/venv/lib/python3.9/site-packages/construct/core.py", line 404, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/Users/chennan/code/pymobiledevice3/venv/lib/python3.9/site-packages/construct/core.py", line 416, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/Users/chennan/code/pymobiledevice3/venv/lib/python3.9/site-packages/construct/core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
  File "/Users/chennan/code/pymobiledevice3/venv/lib/python3.9/site-packages/construct/core.py", line 2236, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/Users/chennan/code/pymobiledevice3/venv/lib/python3.9/site-packages/construct/core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
  File "/Users/chennan/code/pymobiledevice3/venv/lib/python3.9/site-packages/construct/core.py", line 2770, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/Users/chennan/code/pymobiledevice3/venv/lib/python3.9/site-packages/construct/core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
  File "/Users/chennan/code/pymobiledevice3/venv/lib/python3.9/site-packages/construct/core.py", line 2845, in _parse
    raise ConstError(f"parsing expected {repr(self.value)} but parsed {repr(obj)}", path=path)
construct.core.ConstError: Error in path (parsing) -> magic
parsing expected 524114809 but parsed 0
```
**Additional context**
How can we retrieve data in parallel? Can DvtSecureSocketProxyService be used in parallel?

Thanks to everyone!!! 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by cnyy99** [comment]
I tested using a different instance of **dvt** and everything works fine, so maybe that's the answer?
```python3
def tes1(lockdown=None):
    with DvtSecureSocketProxyService(lockdown=lockdown) as dvt:
        with Graphics(dvt) as graphics:
            for stats in graphics:
                logger.info(stats)


def tes2(lockdown=None):
    with DvtSecureSocketProxyService(lockdown=lockdown) as dvt:
        with Sysmontap(dvt) as graphics:
            for stats in graphics:
                logger.info(stats)


def tes():
    lockdown = create_using_usbmux()
    threading.Thread(target=tes1, args=(lockdown,)).start()
    time.sleep(2)
    threading.Thread(target=tes2, args=(lockdown,)).start()


if __name__ == '__main__':
    tes()
    time.sleep(30)
```

**Comment by doronz88** [comment]
Correct. The current DVT implementation doesn't aspire to be multi-purpose for different uses

**Comment by cnyy99** [comment]
Thanks! I will close this issue.
