### ISSUE TITLE
InstallationProxyService。lookup is not working on iOS >=17

### ISSUE THREAD

**Issue by codeskyblue** [doronz88/pymobiledevice3#779]
Tested on iPhone 13 Pro (17.2)

**Comment by doronz88** [comment]
Please provide the full testcase for that. I just tested it on my 17.1 and it works fine.
Could it be you're not testing with latest version of pymobile?

**Comment by codeskyblue** [comment]
```python
from pymobiledevice3.services.installation_proxy import InstallationProxyService
from pymobiledevice3.lockdown import create_using_usbmux

try:
    service_provider = create_using_usbmux()
    with InstallationProxyService(lockdown=service_provider) as install_service:
        result = install_service.lookup('com.apple.Preferences')
        print(result)
except:
    import traceback
    traceback.print_exc()
```

Output
```
Traceback (most recent call last):
  File "/var/folders/32/syzj7rw54sz64nbxcwy_t_m00000gn/T/ipykernel_45561/3190347457.py", line 7, in <module>
    result = install_service.lookup('com.apple.Preferences')
  File "/Users/codeskyblue/projects/github/pymobiledevice3/pymobiledevice3/services/installation_proxy.py", line 127, in lookup
    return self.service.send_recv_plist(cmd).get('LookupResult')
  File "/Users/codeskyblue/projects/github/pymobiledevice3/pymobiledevice3/service_connection.py", line 124, in send_recv_plist
    return self.recv_plist(endianity=endianity)
  File "/Users/codeskyblue/projects/github/pymobiledevice3/pymobiledevice3/service_connection.py", line 163, in recv_plist
    return parse_plist(self.recv_prefixed(endianity=endianity))
  File "/Users/codeskyblue/projects/github/pymobiledevice3/pymobiledevice3/service_connection.py", line 137, in recv_prefixed
    size = self.recvall(4)
  File "/Users/codeskyblue/projects/github/pymobiledevice3/pymobiledevice3/service_connection.py", line 131, in recvall
    raise ConnectionAbortedError()
ConnectionAbortedError
```

**Comment by doronz88** [comment]
I'm very much confused by this example since it should never work. 

- The `lookup()` method takes a `Mapping`, not a string.
https://github.com/doronz88/pymobiledevice3/blob/2b64e6c8ddcce14fe21f4eb84ecb9fc630f39c45/pymobiledevice3/services/installation_proxy.py#L122-L127
- The `create_using_usbmux()` method is only used for connecting over usbmuxd - meaning old lockdown connections. You were asking for RSD connections which are done using `RemoteServiceDiscoveryService()` instead.
  - See https://github.com/doronz88/pymobiledevice3?tab=readme-ov-file#python-api for example

You can also test this works well using:

```shell
# Assuming you already have a tunnel running
pymobiledevice3 apps list --system --tunnel ''
```

In general, the `cli` module may acts as as examples repository to most APIs.

**Comment by codeskyblue** [comment]
my fault, after change the options from `com.apple.Prererences` to `{'BundleIDs': ["com.apple.Preferences"]}`, it looks fine now.

```python
from pymobiledevice3.services.installation_proxy import InstallationProxyService
from pymobiledevice3.lockdown import create_using_usbmux
from pprint import pprint

try:
    service_provider = create_using_usbmux()
    with InstallationProxyService(lockdown=service_provider) as install_service:
        result = install_service.lookup({'BundleIDs': ['com.apple.Preferences']})
        pprint(result.get("com.apple.Preferences"))
except:
    import traceback
    traceback.print_exc()
```

BTW: I guess RemoteServiceDiscoveryService and usbmux service both connect to the same backend(iPhone), so I guess if usbmux got something wrong, the rsd should have the same error.
