### ISSUE TITLE
Developer disk image doesn't mount.

### ISSUE THREAD

**Issue by Quirijn09** [doronz88/pymobiledevice3#789]
**Test environment**
- MacOS Monterey
- iPad 8th gen Wifi iOS 17.2

**Describe the bug**
Developer disk image doesn't mount.

**To Reproduce**
Go to terminal, type sudo python3 -m pymobiledevice3 mounter auto-mount

**Expected behavior**
Expect it to mount.

**Logs**
quirijn@iMacvanQuirijn ~ % sudo python3 -m pymobiledevice3 mounter auto-mount 
/Users/quirijn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/construct/core.py", line 213, in stream_tell
    return stream.tell()
AttributeError: 'SafeStreamSocket' object has no attribute 'tell'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/__main__.py", line 148, in <module>
    main()
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/__main__.py", line 100, in main
    cli()
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1686, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/click/core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/click/core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/cli_common.py", line 177, in udid
    devices = select_devices_by_connection_type(connection_type='USB', usbmux_address=self.usbmux_address)
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/usbmux.py", line 447, in select_devices_by_connection_type
    for device in list_devices(usbmux_address=usbmux_address):
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/usbmux.py", line 409, in list_devices
    mux = create_mux(usbmux_address=usbmux_address)
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/usbmux.py", line 405, in create_mux
    return MuxConnection.create(usbmux_address=usbmux_address)
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/usbmux.py", line 180, in create
    response = usbmuxd_response.parse_stream(sock)
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/construct/core.py", line 416, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/construct/core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/construct/core.py", line 4869, in _parse
    substream = BytesIOWithOffsets.from_reading(stream, length, path)
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/construct/core.py", line 241, in from_reading
    offset = stream_tell(stream, path)
  File "/Users/quirijn/Library/Python/3.9/lib/python/site-packages/construct/core.py", line 215, in stream_tell
    raise StreamError("stream.tell() failed", path=path)
construct.core.StreamError: Error in path (parsing)
stream.tell() failed
.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
You are using an incompatible `construct` version. Please update your `pymobiledevice3` so this requirement will get fixed aswell
