### ISSUE TITLE
python3.8 start-tunnel error: ValueError: 'fe80::a078:17ff:feb6:fac7%ap1' does not appear to be an IPv4 or IPv6 address

### ISSUE THREAD

**Issue by codeskyblue** [doronz88/pymobiledevice3#805]
It happends on >= 2.38

```bash
sudo pymobiledevice3 remote start-tunnel --script-mode --udid 00008101-00015C8A1A05001E
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/bin/pymobiledevice3", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/pymobiledevice3/__main__.py", line 101, in main
    cli()
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/pymobiledevice3/cli/cli_common.py", line 108, in wrapper
    func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/pymobiledevice3/cli/remote.py", line 174, in cli_start_tunnel
    rsd = select_device(udid)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/pymobiledevice3/cli/remote.py", line 135, in select_device
    devices = get_device_list()
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/pymobiledevice3/cli/remote.py", line 27, in get_device_list
    for address in get_remoted_addresses():
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/pymobiledevice3/remote/bonjour.py", line 50, in get_remoted_addresses
    bonjour_queries = [query_bonjour(adapter) for adapter in ips]
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/pymobiledevice3/remote/bonjour.py", line 50, in <listcomp>
    bonjour_queries = [query_bonjour(adapter) for adapter in ips]
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/pymobiledevice3/remote/bonjour.py", line 42, in query_bonjour
    zc = Zeroconf(interfaces=[ip])
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/zeroconf/_core.py", line 173, in __init__
    ip_version = autodetect_ip_version(interfaces)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/zeroconf/_utils/net.py", line 408, in autodetect_ip_version
    has_v6 = any(
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/zeroconf/_utils/net.py", line 409, in <genexpr>
    isinstance(i, int) or (isinstance(i, str) and ipaddress.ip_address(i).version == 6)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: 'fe80::a078:17ff:feb6:fac7%ap1' does not appear to be an IPv4 or IPv6 address
```

When I downgrade version to 2.37.1, everything goes back to normal.

**Comment by doronz88** [comment]
@codeskyblue could please test if #806 resolves the issue?

**Comment by codeskyblue** [comment]
@doronz88 it's not working

```bash
$ git checkout bugfix/tunnel-address
$ sudo python -m pymobiledevice3  remote start-tunnel --udid 00008101-00015C8A1A05001E
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/codeskyblue/projects/github/pymobiledevice3/pymobiledevice3/__main__.py", line 154, in <module>
    main()
  File "/Users/codeskyblue/projects/github/pymobiledevice3/pymobiledevice3/__main__.py", line 101, in main
    cli()
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/codeskyblue/projects/github/pymobiledevice3/pymobiledevice3/cli/cli_common.py", line 110, in wrapper
    func(*args, **kwargs)
  File "/Users/codeskyblue/projects/github/pymobiledevice3/pymobiledevice3/cli/remote.py", line 174, in cli_start_tunnel
    rsd = select_device(udid)
  File "/Users/codeskyblue/projects/github/pymobiledevice3/pymobiledevice3/cli/remote.py", line 135, in select_device
    devices = get_device_list()
  File "/Users/codeskyblue/projects/github/pymobiledevice3/pymobiledevice3/cli/remote.py", line 27, in get_device_list
    for address in get_remoted_addresses():
  File "/Users/codeskyblue/projects/github/pymobiledevice3/pymobiledevice3/remote/bonjour.py", line 50, in get_remoted_addresses
    bonjour_queries = [query_bonjour(adapter) for adapter in ips]
  File "/Users/codeskyblue/projects/github/pymobiledevice3/pymobiledevice3/remote/bonjour.py", line 50, in <listcomp>
    bonjour_queries = [query_bonjour(adapter) for adapter in ips]
  File "/Users/codeskyblue/projects/github/pymobiledevice3/pymobiledevice3/remote/bonjour.py", line 42, in query_bonjour
    zc = Zeroconf(interfaces=[ip])
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/zeroconf/_core.py", line 173, in __init__
    ip_version = autodetect_ip_version(interfaces)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/zeroconf/_utils/net.py", line 408, in autodetect_ip_version
    has_v6 = any(
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/zeroconf/_utils/net.py", line 409, in <genexpr>
    isinstance(i, int) or (isinstance(i, str) and ipaddress.ip_address(i).version == 6)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: 'fe80::a078:17ff:feb6:fac7%10' does not appear to be an IPv4 or IPv6 address
```

**Comment by doronz88** [comment]
since i'm not able to reproduce it, please test what solution works on your workstation and submit a PR

**Comment by codeskyblue** [comment]
> since i'm not able to reproduce it, please test what solution works on your workstation and submit a PR

2.37.1 works fine

**Comment by doronz88** [comment]
@codeskyblue As I said, you are able to reproduce it while I am not. Only you can point at the bug

**Comment by doronz88** [comment]
Also, that is just a guess, but try updating your `zeroconf`

**Comment by doronz88** [comment]
Was actually able to reproduce it. It's a bug on `zeroconf` python3.8 support specifically (python3.9 works just fine). You can submit the issue there

**Comment by codeskyblue** [comment]
Just a few modification will make it works on python3.8 (python 3.9 is also ok)

File: `pymobiledevice3/remote/bonjour.py`

```python
 def query_bonjour(ip: str) -> BonjourQuery:
-    zc = Zeroconf(interfaces=[ip])
+    zc = Zeroconf(interfaces=[ip.split('%')[0]])
     listener = RemotedListener(ip)
     service_browser = ServiceBrowser(zc, '_remoted._tcp.local.', listener)
     return BonjourQuery(zc, service_browser, listener)
```

**Comment by codeskyblue** [comment]
The problem still exists.
- pymobiledevice3 version 4.5.2
- python 3.8
- zeroconf 0.132.2

```
sudo pymobiledevice3 remote start-tunnel --script-mode --udid 00008101-00015C8A1A05001E
Traceback (most recent call last):
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/bin/pymobiledevice3", line 8, in <module>
    sys.exit(main())
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/pymobiledevice3/__main__.py", line 100, in main
    cli()
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/pymobiledevice3/cli/cli_common.py", line 120, in wrapper
    func(*args, **kwargs)
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/pymobiledevice3/cli/remote.py", line 197, in cli_start_tunnel
    asyncio.run(
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/pymobiledevice3/cli/remote.py", line 163, in start_tunnel_task
    tunnel_services = await get_tunnel_services[connection_type](udid=udid)
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/pymobiledevice3/remote/tunnel_service.py", line 1004, in get_core_device_tunnel_services
    for rsd in await get_rsds(bonjour_timeout=bonjour_timeout, udid=udid):
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/pymobiledevice3/remote/utils.py", line 18, in get_rsds
    for answer in await browse_remoted(timeout=bonjour_timeout):
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/pymobiledevice3/bonjour.py", line 123, in browse_remoted
    return await browse_ipv6(REMOTED_SERVICE_NAMES, timeout=timeout)
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/pymobiledevice3/bonjour.py", line 100, in browse_ipv6
    return await browse(service_names, OSUTILS.get_ipv6_ips(), timeout=timeout)
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/pymobiledevice3/bonjour.py", line 83, in browse
    bonjour_queries = [query_bonjour(service_names, adapter) for adapter in ips]
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/pymobiledevice3/bonjour.py", line 83, in <listcomp>
    bonjour_queries = [query_bonjour(service_names, adapter) for adapter in ips]
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/pymobiledevice3/bonjour.py", line 74, in query_bonjour
    aiozc = AsyncZeroconf(interfaces=[ip])
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/zeroconf/asyncio.py", line 166, in __init__
    self.zeroconf = zc or Zeroconf(
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/zeroconf/_core.py", line 172, in __init__
    ip_version = autodetect_ip_version(interfaces)
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/zeroconf/_utils/net.py", line 408, in autodetect_ip_version
    has_v6 = any(
  File "/Users/codeskyblue/projects/github/tidevice3/.venv/lib/python3.8/site-packages/zeroconf/_utils/net.py", line 409, in <genexpr>
    isinstance(i, int) or (isinstance(i, str) and ipaddress.ip_address(i).version == 6)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: 'fe80::a078:17ff:feb6:fac7%ap1' does not appear to be an IPv4 or IPv6 address
```

I can see the error is related to ipaddress. it can only parse address like `'fe80::a078:17ff:feb6:fac7`
