### ISSUE TITLE
Feature Request: Allow installing `.app` bundle (not only IPA)

### ISSUE THREAD

**Issue by wojciech-kulik** [doronz88/pymobiledevice3#839]
Hi!

It would be very handy to be able to install the app by specifying the path to `ProjectName.app` folder like:

```
pymobiledevice3 apps install "/Users/myname/Library/Developer/Xcode/DerivedData/MyApp-hash/Build/Products/Debug-iphoneos/MyApp.app"
```

This feature is supported by `go-ios`.

**Comment by doronz88** [comment]
Could you please test if #840 solves this issue?

**Comment by wojciech-kulik** [comment]
Wow, thank you for the amazing work and quick reaction. Unfortunately, I get some errors:

```
╰─ python3 -m pymobiledevice3 apps install /Users/me/Library/Developer/Xcode/DerivedData/MyApp-ABCD/Build/Products/Debug-iphoneos/MyApp.app
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/wkulik/Downloads/pymobiledevice3/pymobiledevice3/__main__.py", line 156, in <module>
    main()
  File "/Users/wkulik/Downloads/pymobiledevice3/pymobiledevice3/__main__.py", line 98, in main
    cli()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/wkulik/Downloads/pymobiledevice3/pymobiledevice3/cli/cli_common.py", line 171, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "/Users/wkulik/Downloads/pymobiledevice3/pymobiledevice3/cli/apps.py", line 54, in install
    InstallationProxyService(lockdown=service_provider).install_from_local(ipa_path)
  File "/Users/wkulik/Downloads/pymobiledevice3/pymobiledevice3/services/installation_proxy.py", line 78, in install_from_local
    afc.set_file_contents(remote_path, open(ipa_path, 'rb').read())
IsADirectoryError: [Errno 21] Is a directory: '/Users/me/Library/Developer/Xcode/DerivedData/MyApp-ABCD/Build/Products/Debug-iphoneos/MyApp.app'

```

**Comment by wojciech-kulik** [comment]
Wow, thank you for the amazing work and quick reaction. Works great, exactly what I needed. Thank you!

**Comment by wojciech-kulik** [comment]
I noticed only a problem on iOS 14:
```
╰─ python3 -m pymobiledevice3 apps install /Users/wkulik/Library/Developer/Xcode/DerivedData/MyApp-ABCD/Build/Products/Debug-iphoneos/MyApp.app
2024-02-19 10:46:14 Wojciech-MacBook-M1.local pymobiledevice3.services.installation_proxy[67867] INFO 5% Complete
2024-02-19 10:46:14 Wojciech-MacBook-M1.local pymobiledevice3.services.installation_proxy[67867] INFO 15% Complete
2024-02-19 10:46:16 Wojciech-MacBook-M1.local pymobiledevice3.services.installation_proxy[67867] INFO 20% Complete
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/wkulik/Downloads/pymobiledevice3/pymobiledevice3/__main__.py", line 156, in <module>
    main()
  File "/Users/wkulik/Downloads/pymobiledevice3/pymobiledevice3/__main__.py", line 98, in main
    cli()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/wkulik/Downloads/pymobiledevice3/pymobiledevice3/cli/cli_common.py", line 171, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "/Users/wkulik/Downloads/pymobiledevice3/pymobiledevice3/cli/apps.py", line 54, in install
    InstallationProxyService(lockdown=service_provider).install_from_local(ipa_or_app_path)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/parameter_decorators/common.py", line 28, in new_f
    return f(*ba.args, **ba.kwargs)
  File "/Users/wkulik/Downloads/pymobiledevice3/pymobiledevice3/services/installation_proxy.py", line 107, in install_from_local
    self._watch_completion(handler, args)
  File "/Users/wkulik/Downloads/pymobiledevice3/pymobiledevice3/services/installation_proxy.py", line 49, in _watch_completion
    raise AppInstallError(f'{error}: {response.get("ErrorDescription")}')
pymobiledevice3.exceptions.AppInstallError: APIInternalError: Failed to open /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.f9gEVL/extracted/Payload : No such file or directory
```

**Comment by sk2212** [comment]
Have not tested it but it would be nice if the output after installing could be like that:

? installationURL: file:///private/var/containers/Bundle/Application/99A23981-947A-4FF3-B282-5DE6D633F3BB/QMLTest.app/
? launchServicesIdentifier: unknown
? databaseUUID: 82F0A8CD-F632-490A-AECE-6DCF20401F73
? databaseSequenceNumber: 2028
? options:

**Comment by doronz88** [comment]
@wojciech-kulik just pushed a fix for that. could you please test it again?
@sk2212 this data can be retrieved by `pymobiledevice3 apps query`

**Comment by wojciech-kulik** [comment]
@doronz88 we are getting close, `Info.plist` is missing:

```
raise AppInstallError(f'{error}: {response.get("ErrorDescription")}')
pymobiledevice3.exceptions.AppInstallError: PackageInspectionFailed: Failed to load Info.plist from bundle at path /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.QCL4eI/extracted/Payload/MyApp.app; Extra info about Info.plist: Couldn't stat /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.QCL4eI/extracted/Payload/MyApp.app/Info.plist: No such file or directory
```

**Comment by wojciech-kulik** [comment]
@doronz88  Sorry, actually it works! I forgot I was messing up with `.app` to test it :)
