### ISSUE TITLE
'_X25519PublicKey' object has no attribute 'public_bytes_raw'

### ISSUE THREAD

**Issue by lycfr** [doronz88/pymobiledevice3#861]
```
cfr@bogon ~ % sudo python -m pymobiledevice3 remote start-tunnel
Traceback (most recent call last):
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/__main__.py", line 156, in <module>
    main()
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/__main__.py", line 98, in main
    cli()
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/cli/cli_common.py", line 145, in wrapper
    func(*args, **kwargs)
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/cli/remote.py", line 197, in cli_start_tunnel
    asyncio.run(tunnel_task(rsd, secrets, script_mode, max_idle_timeout=max_idle_timeout, protocol=protocol),
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/cli/remote.py", line 112, in tunnel_task
    async with start_tunnel(service_provider, secrets=secrets, max_idle_timeout=max_idle_timeout,
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 752, in start_tunnel
    with create_core_device_tunnel_service(service_provider, autopair=True) as service:
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 742, in create_core_device_tunnel_service
    service.connect(autopair=autopair)
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 328, in connect
    if not self._validate_pairing():
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 602, in _validate_pairing
    'data': self.x25519_private_key.public_key().public_bytes_raw()},
AttributeError: '_X25519PublicKey' object has no attribute 'public_bytes_raw'
```
Can you help me solve this problem?

Device Information：
```
iPhone 15 Pro   17.0
```

pymobiledevice3：2.43.8

**Comment by doronz88** [comment]
Sounds like an outdated `cryptography`. Please update after updating it:
```shell
python3 -m pip install -U cryptography
```

**Comment by lycfr** [comment]
I have updated the cryptography, but the error still occurs after executing it.
But when I use [go-ios](https://github.com/danielpaulus/go-ios) to start the tunnel, go-ios actually successfully starts the tunnel. Why is this?
```
cfr@bogon ~ % sudo python -m pymobiledevice3 remote start-tunnel
Traceback (most recent call last):
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/__main__.py", line 156, in <module>
    main()
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/__main__.py", line 98, in main
    cli()
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/cli/cli_common.py", line 145, in wrapper
    func(*args, **kwargs)
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/cli/remote.py", line 197, in cli_start_tunnel
    asyncio.run(tunnel_task(rsd, secrets, script_mode, max_idle_timeout=max_idle_timeout, protocol=protocol),
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/cli/remote.py", line 112, in tunnel_task
    async with start_tunnel(service_provider, secrets=secrets, max_idle_timeout=max_idle_timeout,
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 752, in start_tunnel
    with create_core_device_tunnel_service(service_provider, autopair=True) as service:
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 742, in create_core_device_tunnel_service
    service.connect(autopair=autopair)
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 328, in connect
    if not self._validate_pairing():
  File "/Users/cfr/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 602, in _validate_pairing
    'data': self.x25519_private_key.public_key().public_bytes_raw()},
AttributeError: '_X25519PublicKey' object has no attribute 'public_bytes_raw'

cfr@bogon ~ % sudo /Users/cfr/PycharmProjects/tidevice_tool/logserver/mac/go-ios tunnel start --pair-record-path /Users/cfr
{"level":"info","msg":"no udid specified using first device in list","time":"2024-02-28T14:12:02+08:00","udid":"00008130-000930AE2403401C"}
{"level":"info","msg":"start tunnel","time":"2024-02-28T14:12:03+08:00","udid":"00008130-000930AE2403401C"}
{"level":"info","msg":"create tunnel listener","time":"2024-02-28T14:12:05+08:00"}
{"address":"fe80::c71:a4ff:fedc:10a9%en5","level":"info","msg":"connect to tunnel endpoint on device","port":57113,"time":"2024-02-28T14:12:05+08:00"}
^C
```

**Comment by doronz88** [comment]
Unfortunately I cannot guess what's causing this.
I would recommend trying to locate the outdated pypi package causing this. This very much sounds like a problem with `cryptography` since the accessed member is very basic in their API:
https://cryptography.io/en/latest/hazmat/primitives/asymmetric/x25519/#cryptography.hazmat.primitives.asymmetric.x25519.X25519PublicKey.public_bytes_raw

You can also try and submit an issue on their repo

**Comment by lycfr** [comment]
I uninstalled and installed pymobiledevice3 again, and then used it normally
