### ISSUE TITLE
Can pymobiledevice3 be packaged into an executable exe file using pyinstaller?

### ISSUE THREAD

**Issue by lycfr** [doronz88/pymobiledevice3#865]
I have tried packaging several times but failed?
Can you give me some guidance?

**Comment by doronz88** [comment]
Haven't tried that myself but take a look at this doc:
https://github.com/doronz88/pymobiledevice3/blob/master/misc/pyinstaller.md

**Comment by lycfr** [comment]
Your suggestions are very useful, and I have successfully packaged and used them on MacOS, but it failed on Windows and the error is as follows:
```
 Traceback (most recent call last):
  File "pmd3_main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pymobiledevice3\cli\remote.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pymobiledevice3\cli\cli_common.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "inquirer3\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "inquirer3\prompt.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "inquirer3\themes.py", line 9, in <module>
  File "blessed\terminal.py", line 164, in __init__
  File "blessed\terminal.py", line 253, in __init__streams
AttributeError: 'NoneType' object has no attribute 'fileno'

```
I feel that I have no idea how to solve it. Please help me solve it.

**Comment by lycfr** [comment]
I solved it temporarily. After commenting "blessed\terminal.py", line 164, self.__init__streams(), the package ran successfully, but I don't know what the specific function of this method is?

**Comment by doronz88** [comment]
I'm not sure. This is something internal within `blessed`

**Comment by lycfr** [comment]
thanks

**Comment by mega6453** [comment]
@lycfr @doronz88  Can any of you help me how to generate exe of pymobiledevice3? I'm not a python guy, so it's new to me.. Detailed steps will be helpful..
I tried using pyinstaller. but some issues coming up.. 
I tried running the script mentioned here https://github.com/doronz88/pymobiledevice3/blob/master/misc/pyinstaller.md
as well.. this creates exe but when running it says some module is missing..

**Comment by doronz88** [comment]
You can view this PR till its merged:
https://github.com/doronz88/pymobiledevice3/pull/971

**Comment by mega6453** [comment]
ok thanks

**Comment by mega6453** [comment]
**I executed this script(pyinstaller.md) using Python IDLE and getting below error:**

Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 13:49:07) [MSC v.1938 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:\Users\mc\AppData\Local\Programs\Python\Python312-32\newsetup.py
1002 INFO: PyInstaller: 6.6.0, contrib hooks: 2024.5
1010 INFO: Python: 3.12.3
1197 INFO: Platform: Windows-10-10.0.19045-SP0
1210 INFO: wrote C:\Users\mc\AppData\Local\Programs\Python\Python312-32\__main__.spec
Traceback (most recent call last):
  File "C:\Users\mc\AppData\Local\Programs\Python\Python312-32\Lib\importlib\metadata\__init__.py", line 397, in from_name
    return next(cls.discover(name=name))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mc\AppData\Local\Programs\Python\Python312-32\newsetup.py", line 13, in <module>
    PyInstaller.__main__.run([
  File "C:\Users\mc\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\PyInstaller\__main__.py", line 212, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\mc\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\PyInstaller\__main__.py", line 69, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\mc\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\PyInstaller\building\build_main.py", line 1186, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\mc\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\PyInstaller\building\build_main.py", line 1126, in build
    exec(code, spec_namespace)
  File "C:\Users\mc\AppData\Local\Programs\Python\Python312-32\__main__.spec", line 6, in <module>
    datas += copy_metadata('apple_compress')
  File "C:\Users\mc\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 957, in copy_metadata
    dist = importlib_metadata.distribution(package_name)
  File "C:\Users\mc\AppData\Local\Programs\Python\Python312-32\Lib\importlib\metadata\__init__.py", line 862, in distribution
    return Distribution.from_name(distribution_name)
  File "C:\Users\mc\AppData\Local\Programs\Python\Python312-32\Lib\importlib\metadata\__init__.py", line 399, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for apple_compress

**Comment by mega6453** [comment]
@doronz88 Created exe using the **pyinstaller.md** script... when running the exe, getting below error.. 

C:\Users\mc\AppData\Local\Programs\Python\Python312-32\output>__main__.exe
Traceback (most recent call last):
  File "pymobiledevice3\__main__.py", line 168, in <module>
  File "pymobiledevice3\__main__.py", line 100, in main
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1077, in main
  File "click\core.py", line 943, in make_context
  File "click\core.py", line 1641, in parse_args
  File "click\core.py", line 704, in get_help
  File "click\core.py", line 1325, in get_help
  File "click\core.py", line 1358, in format_help
  File "click\core.py", line 1564, in format_options
  File "click\core.py", line 1617, in format_commands
  File "pymobiledevice3\__main__.py", line 84, in get_command
ModuleNotFoundError: No module named 'pymobiledevice3.cli'
[30040] Failed to execute script '__main__' due to unhandled exception!

**Comment by mega6453** [comment]
@doronz88  If possible, can u release windows exe version as well please...? that will be easy !

**Comment by mega6453** [comment]
@doronz88  I've created exe using the "master/misc/pyinstaller.md" doc.. When I run it, I'm seeing below error; How to resolve this? I tried adding " '--hidden-import=win32ctypes'," in the .py file.. but still it's same.. Help Please..

C:\Users\mega\AppData\Local\Programs\Python\Python312\dist\setup>setup.exe
Could not import `pywintypes` or `win32api` from `win32ctypes.pywin32`.
Please make sure that `pywin32-ctypes` is installed and importable, for example:

pip install pywin32-ctypes

**Comment by doronz88** [comment]
Looks like @AnNEDoMini (❤️)  already solved the issue in #1019

**Comment by mega6453** [comment]
@doronz88 
Still seeing the same issue with the updated script as well.. Please find the script below.. Am I doing something wrong?

```
import shutil
import os
import site

import PyInstaller.__main__

site_packages_path = site.getsitepackages()[1]
out_dir = "./output"
if os.path.exists(out_dir):
    shutil.rmtree(out_dir)


PyInstaller.__main__.run([
    './Lib/site-packages/pymobiledevice3/__main__.py',
    '--hidden-import=ipsw_parser',
    '--hidden-import=zeroconf',
    '--hidden-import=pyimg4',
    '--hidden-import=apple_compress',
    '--hidden-import=zeroconf._utils.ipaddress',
    '--hidden-import=zeroconf._handlers.answers',
    '--hidden-import=readchar',
    '--copy-metadata=pyimg4',
    '--copy-metadata=readchar',
    '--copy-metadata=apple_compress',
    '--add-binary', f"{site_packages_path}/pytun_pmd3/*;pytun_pmd3",
    '--onefile'
])

shutil.move('dist', './output')

```

I tried to install "pywin32-ctypes" again but it says already available:
`Requirement already satisfied: pywin32-ctypes in c:\users\mc\appdata\local\programs\python\python312\lib\site-packages (0.2.2)`

When I run the above script using pyinstaller, It creates a exe file in the dist folder.. I'm running that file and getting error as below:
```
Could not import `pywintypes` or `win32api` from `win32ctypes.pywin32`.
Please make sure that `pywin32-ctypes` is installed and importable, for example:

pip install pywin32-ctypes
```

I don't have any idea about python. So, please help me on this. Thanks!

**Comment by AnNEDoMini** [comment]
I have not encountered your error, try this: https://stackoverflow.com/questions/52194396/unable-to-run-pyinstaller-please-install-pywin32-or-pywin32-ctypes it may help

**Comment by mega6453** [comment]
@AnNEDoMini  Thanks, I tried the suggestion from stackoverflow. I'm not getting that error now. 
But now there are lot of exceptions in the output..  I've given the main file path as below in the script. Is that right first?
```
PyInstaller.__main__.run([
    './Lib/site-packages/pymobiledevice3/__main__.py',
```

If yes then below is the error displaying when i'm running the exe...


```
C:\Users\mc\AppData\Local\Programs\Python\Python312\dist\newsetup>newsetup.exe
Traceback (most recent call last):
  File "newsetup.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "PyInstaller\__init__.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "PyInstaller\compat.py", line 75, in <module>
  File "platform.py", line 448, in win32_ver
  File "platform.py", line 386, in _win32_ver
  File "platform.py", line 326, in _wmi_query
KeyboardInterrupt
[9336] Failed to execute script 'newsetup' due to unhandled exception!
Traceback (most recent call last):
  File "PyInstaller\isolated\_parent.py", line 389, in call
  File "PyInstaller\isolated\_parent.py", line 304, in call
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "newsetup.py", line 13, in <module>
  File "PyInstaller\__main__.py", line 170, in run
  File "PyInstaller\__main__.py", line 136, in generate_parser
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "PyInstaller\building\build_main.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "PyInstaller\building\api.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "PyInstaller\building\splash.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "PyInstaller\utils\hooks\tcl_tk.py", line 66, in <module>
  File "PyInstaller\isolated\_parent.py", line 420, in wrapped
  File "PyInstaller\isolated\_parent.py", line 388, in call
  File "PyInstaller\isolated\_parent.py", line 257, in __exit__
OSError: [Errno 22] Invalid argument
[23188] Failed to execute script 'newsetup' due to unhandled exception!
Traceback (most recent call last):
  File "PyInstaller\isolated\_parent.py", line 389, in call
  File "PyInstaller\isolated\_parent.py", line 304, in call
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "newsetup.py", line 13, in <module>
  File "PyInstaller\__main__.py", line 170, in run
  File "PyInstaller\__main__.py", line 136, in generate_parser
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "PyInstaller\building\build_main.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "PyInstaller\building\api.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "PyInstaller\building\splash.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "PyInstaller\utils\hooks\tcl_tk.py", line 66, in <module>
  File "PyInstaller\isolated\_parent.py", line 420, in wrapped
  File "PyInstaller\isolated\_parent.py", line 388, in call
  File "PyInstaller\isolated\_parent.py", line 257, in __exit__
OSError: [Errno 22] Invalid argument
[34744] Failed to execute script 'newsetup' due to unhandled exception!
```

This didn't stop here.. I stopped it by exiting.. It's keep on going.. 

Any help? Thanks !
