### ISSUE TITLE
mach-o file, but is an incompatible architecture

### ISSUE THREAD

**Issue by KingRat0011** [doronz88/pymobiledevice3#888]
Has anyone seen this before, please?

MAC M1 chip
- Sonoma 14.4
- MacMini and iOS 17.4

```
/usr/bin/python3 -m pymobiledevice3 developer dvt screenshot --tunnel 00008110-xxxxxxxxxxx01E 00008110-xxxxxxxxxxxxxx01E.png
ImportError: dlopen(/Users/diginetiot/Library/Python/3.9/lib/python/site-packages/_cffi_backend.cpython-39-darwin.so, 0x0002): tried: '/Users/diginetiot/Library/Python/3.9/lib/python/site-packages/_cffi_backend.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/diginetiot/Library/Python/3.9/lib/python/site-packages/_cffi_backend.cpython-39-darwin.so' (no such file), '/Users/diginetiot/Library/Python/3.9/lib/python/site-packages/_cffi_backend.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.20.3/src/err/mod.rs:788:5:
Python API call failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/diginetiot/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/__main__.py", line 156, in <module>
    main()
  File "/Users/diginetiot/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/__main__.py", line 98, in main
    cli()
  File "/Users/diginetiot/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/diginetiot/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/diginetiot/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1682, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/Users/diginetiot/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1729, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/Users/diginetiot/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/__main__.py", line 82, in get_command
    mod = __import__(f'pymobiledevice3.cli.{CLI_GROUPS[name]}', None, None, ['cli'])
  File "/Users/diginetiot/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/developer.py", line 21, in <module>
    from pymobiledevice3.cli.cli_common import BASED_INT, Command, RSDCommand, default_json_encoder, print_json, \
  File "/Users/diginetiot/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/cli_common.py", line 19, in <module>
    from pymobiledevice3.lockdown import LockdownClient, create_using_usbmux
  File "/Users/diginetiot/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/lockdown.py", line 18, in <module>
    from pymobiledevice3.ca import ca_do_everything
  File "/Users/diginetiot/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/ca.py", line 3, in <module>
    from cryptography import x509
  File "/Users/diginetiot/Library/Python/3.9/lib/python/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509 import certificate_transparency, verification
  File "/Users/diginetiot/Library/Python/3.9/lib/python/site-packages/cryptography/x509/certificate_transparency.py", line 11, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
pyo3_runtime.PanicException: Python API call failed
```

I tried 
`pip3 install pymobiledevice3 --compile --force-reinstall`
and
`pip3 install cffi --compile --force-reinstall`
```
pip3 list | grep cffi
cffi                  1.16.0
```

**Comment by doronz88** [comment]
sounds like something wrong with your python installation

**Comment by KingRat0011** [comment]
Thanks let me recheck everything

**Comment by KingRat0011** [comment]
ok reinstalled python and the problem is not there anymore, thanks for the tip
