### ISSUE TITLE
remote tunneld with iPad connected via USB gives "Too many open files" errors

### ISSUE THREAD

**Issue by warmenhoven** [doronz88/pymobiledevice3#898]
**Test environment**
- M2 Ultra Mac Studio, macOS 14.4.1
- iPad Pro (11-inch) (2nd generation), iOS 17.4.1
- pymobiledevice3 3.0.1

**Describe the bug**
I have my iPad connected via USB-C and unlocked. I start getting the following error messages periodically:
```
Error raised from: handle-new-potential-usb-cdc-ncm-interface-task-fe80::a6fc:14ff:fe0c:66ba%utun13: Traceback (most recent call last):
  File "/Users/eric/src/SideJITServer/venv/lib/python3.9/site-packages/pymobiledevice3/tunneld.py", line 179, in handle_new_potential_usb_cdc_ncm_interface_task
  File "/Users/eric/src/SideJITServer/venv/lib/python3.9/site-packages/pymobiledevice3/bonjour.py", line 93, in browse
  File "/Users/eric/src/SideJITServer/venv/lib/python3.9/site-packages/pymobiledevice3/bonjour.py", line 93, in <listcomp>
  File "/Users/eric/src/SideJITServer/venv/lib/python3.9/site-packages/pymobiledevice3/bonjour.py", line 85, in query_bonjour
  File "/Users/eric/src/SideJITServer/venv/lib/python3.9/site-packages/zeroconf/asyncio.py", line 170, in __init__
  File "/Users/eric/src/SideJITServer/venv/lib/python3.9/site-packages/zeroconf/_core.py", line 176, in __init__
  File "/Users/eric/src/SideJITServer/venv/lib/python3.9/site-packages/zeroconf/_utils/net.py", line 374, in create_sockets
  File "/Users/eric/src/SideJITServer/venv/lib/python3.9/site-packages/zeroconf/_utils/net.py", line 331, in new_respond_socket
  File "/Users/eric/src/SideJITServer/venv/lib/python3.9/site-packages/zeroconf/_utils/net.py", line 230, in new_socket
  File "/Applications/Xcode-15.1.0.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 232, in __init__
OSError: [Errno 24] Too many open files
```

**To Reproduce**
1. Connect iPad and unlock it
2. Start `remote tunneld` (I was using SideJITServer in the trace above but I've seen the exact same trace just running from the CLI directly)

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Can you provide a list of your network adapters?
Also, can you try running `sudo pymobiledevice3 remote tunneld --no-usb` so it will only discover WiFi devices and see if the error persists?

**Comment by briankrznarich** [comment]
I have encountered this on a system with a bunch of devices simultaneously attached. I couldn't find any issues with pymobiledevice3 at the time (such as accidentally opening too many files).   It just seemed like we were running into a default MacOS limit.

If you run this before launching `pymobiledevice3`, does the problem go away:
`
ulimit -n 1000  #Pick an even bigger number if you like
`

Your problem may just be the tiny default ulimit on MacOS. 
```
$ ulimit -a
...
open files                          (-n) 256
...
```

[edit] In #912 I noted that pymobiledevice3 has a tendency to open connections to all attached devices and inspect them.  There might be a leak in there I suppose, but tunneld() is going to have to maintain open connections to every device, so that might be unavoidable.

**Comment by doronz88** [comment]
@warmenhoven is this still an issue?

**Comment by warmenhoven** [comment]
I have not seen this since trying the different ulimit. I also haven't updated to 3.4 yet. If you'd like to mark this as closed I'm fine with that and will reopen/recreate if I see it again.
