### ISSUE TITLE
Meet Invalid Service error while try to kill app sometimes

### ISSUE THREAD

**Issue by zyonbao** [doronz88/pymobiledevice3#904]
**Test environment**
- Host OS version: MacOS 14.4.1
- Target device model and iOS version:  iPad mini 6 with iOS 16.7 installed

**Describe the bug**
Meet Invalid Service error while try to kill app sometimes, and once it occurs, I can not access "com.apple.instruments.remoteserver.DVTSecureSocketProxy" any longer. But if I connect the device to other mac which not  have the problem, the app in the device can be killed!.

Maybe there is a way to reset usbmux status?

**Expected behavior**
can kill app successfully.

**Logs**
Here is the traceback:

Traceback (most recent call last):
  File "/Users/username/test_code/ios_devcie_helper.py", line 289, in kill_app
    with DvtSecureSocketProxyService(lockdown=self.lockdown_service) as dvt:
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/services/dvt/dvt_secure_socket_proxy.py", line 24, in __init__
    super().__init__(lockdown, service_name, remove_ssl_context=remove_ssl_context)
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/services/remote_server.py", line 362, in __init__
    super().__init__(lockdown, service_name, is_developer_service=is_developer_service)
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/services/lockdown_service.py", line 20, in __init__
    service = start_service(service_name, include_escrow_bag=include_escrow_bag)
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/lockdown_service_provider.py", line 41, in start_lockdown_developer_service
    return self.start_lockdown_service(name, include_escrow_bag=include_escrow_bag)
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/lockdown.py", line 54, in _inner_reconnect_on_remote_close
    return f(*args, **kwargs)
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/lockdown.py", line 424, in start_lockdown_service
    attr = self.get_service_connection_attributes(name, include_escrow_bag=include_escrow_bag)
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/lockdown.py", line 414, in get_service_connection_attributes
    response = self._request('StartService', options)
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/lockdown.py", line 498, in _request
    raise exception_errors.get(error, LockdownError)(error)
pymobiledevice3.exceptions.InvalidServiceError: InvalidService

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Sounds like you're not mounting the developer disk image

**Comment by zyonbao** [comment]
@doronz88 It works! Thanks for your reply!
