### ISSUE TITLE
pymobiledevice3 developer dvt applist command "missing 1 required positional argument: 'color'" 

### ISSUE THREAD

**Issue by pachoo** [doronz88/pymobiledevice3#926]
**Test environment**
- MacOS 14.4.1
- iPad model J271AP, iOS 17.4.1

**Describe the bug**
The `pymobiledevice3 developer dvt applist command ` incorrectly has `color` as a positional parameter at https://github.com/doronz88/pymobiledevice3/blob/master/pymobiledevice3/cli/developer.py#L124. 

Happy to submit a PR, but the fix should be straightforward :)

**To Reproduce**
1.  run `pymobiledevice3 developer dvt applist`

**Expected behavior**
A list of the apps.

**Logs**
Error
```
% pymobiledevice3 developer dvt applist
Traceback (most recent call last):
  File "/Users/shaneg/.pyenv/versions/mf-3.9/bin/pymobiledevice3", line 8, in <module>
    sys.exit(main())
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/pymobiledevice3/__main__.py", line 98, in main
    cli()
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/pymobiledevice3/cli/cli_common.py", line 175, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
TypeError: applist() missing 1 required positional argument: 'color'
```

**Additional context**

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Thanks for reporting! 
Also, eventhough the fix is not complicated, still submitting a PR can save us some of the time
