### ISSUE TITLE
pymobiledevice3 developer dvt netstat command error "KeyError: 'hostname'"

### ISSUE THREAD

**Issue by pachoo** [doronz88/pymobiledevice3#927]
**Test environment**
- MacOS 14.4.1
- iPad model J271AP, iOS 17.4.1
- pymobiledevice3 version 3.2.0

**Describe the bug**
When running the cli command `pymobiledevice3 developer dvt netstat` there's an error, "KeyError: 'hostname'".    The ipaddress returned by `ipaddress.ip_address()` ( https://github.com/doronz88/pymobiledevice3/blob/master/pymobiledevice3/services/dvt/instruments/network_monitor.py#L8 ) does not contain a hostname member, though that is referenced in the cli code: https://github.com/doronz88/pymobiledevice3/blob/master/pymobiledevice3/cli/developer.py#L266

**To Reproduce**
1. Run `pymobiledevice3 developer dvt netstat`

**Expected behavior**
output of the command, e.g. lines like "Connection detected....".

**Logs**
```
 pymobiledevice3 developer dvt netstat --rsd fd8c:40a5:a0bf::1 62809
# Note this is some printf debugging I added :)
2024-04-10 18:06:15 Shanes-MacBook-Pro.local pymobiledevice3.cli.developer[84377] INFO !!! event: ConnectionDetectionEvent(local_address=Container(len=28, family=30, port=51574, data=Container(flow_info=0, address=IPv6Address('fd8c:40a5:a0bf::1'), scope_id=0)), remote_address=Container(len=28, family=30, port=52355, data=Container(flow_info=0, address=IPv6Address('fd8c:40a5:a0bf::2'), scope_id=0)), interface_index=14, pid=-2, recv_buffer_size=396939, recv_buffer_used=0, serial_number=0, kind=1)
Traceback (most recent call last):
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/construct/lib/containers.py", line 98, in __getattr__
    return self[name]
KeyError: 'hostname'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shaneg/.pyenv/versions/mf-3.9/bin/pymobiledevice3", line 8, in <module>
    sys.exit(main())
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/pymobiledevice3/__main__.py", line 98, in main
    cli()
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/pymobiledevice3/cli/cli_common.py", line 175, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/pymobiledevice3/cli/developer.py", line 264, in netstat
    f'Connection detected: {event.local_address.data.hostname}:{event.local_address.port} -> '
  File "/Users/shaneg/.pyenv/versions/3.9.18/envs/mf-3.9/lib/python3.9/site-packages/construct/lib/containers.py", line 100, in __getattr__
    raise AttributeError(name)
AttributeError: hostname
```

**Additional context**
I'm not sure if the ipaddress module perhaps changed the object it returns and it no longer includes hostname, or perhaps this hasn't worked.  I'd propose to just show the IPv4/IPv6 address in the output instead of trying to show a hostname.

This error also appears in issue https://github.com/doronz88/pymobiledevice3/issues/759.

happy to provide a PR, but I expect the fix is fairly striaghtforward.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Looks like apple just completely changed the data returned by this API
I'll instead just refactor it to print the data as-is, instead of forcing a fixed layout
