### ISSUE TITLE
Failed to mount developer image ios 17.4.1 iPhone 15plus

### ISSUE THREAD

**Issue by kj54321** [doronz88/pymobiledevice3#951]
**Test environment**
- Host OS version.
ios 17.4.1
- Target device model and iOS version.
iPhone 15plus
xcode 15.2 & command line tools installed
Developer mode is on under Privaacy & Security.
Latest pymobiledevice3 installed from pip

**Describe the bug**
Command ```pymobiledevice3 mounter auto-mount``` is not working, detailed error below:

```
sudo pymobiledevice3 mounter auto-mount
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 162, in query_personalization_manifest
    return response['ImageSignature']
           ~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'ImageSignature'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 208, in mount
    manifest = self.query_personalization_manifest('DeveloperDiskImage', hashlib.sha384(image).digest())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 164, in query_personalization_manifest
    raise MissingManifestError()
pymobiledevice3.exceptions.MissingManifestError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pymobiledevice3", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/__main__.py", line 100, in main
    cli()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/cli/cli_common.py", line 146, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/cli/mounter.py", line 120, in mounter_auto_mount
    auto_mount(service_provider, xcode=xcode, version=version)
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 362, in auto_mount
    auto_mount_personalized(lockdown)
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 355, in auto_mount_personalized
    PersonalizedImageMounter(lockdown=lockdown).mount(image, build_manifest, trustcache)
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 211, in mount
    manifest = self.get_manifest_from_tss(plistlib.loads(build_manifest.read_bytes()))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 242, in get_manifest_from_tss
    raise NoSuchBuildIdentityError(f'Could not find the manifest for board {board_id} and chip {chip_id}')
pymobiledevice3.exceptions.NoSuchBuildIdentityError: Could not find the manifest for board 10 and chip 33056
 ```

Let meet know if more info is required.
Thanks

**Comment by kj54321** [comment]
Using latest command pymobiledevice3 lockdown start-tunnel solved the problem.
