### ISSUE TITLE
LocationSimulation - InvalidServiceError: InvalidService

### ISSUE THREAD

**Issue by taipingeric** [doronz88/pymobiledevice3#975]
**Test environment**
- Host OS version: macOS 12.6.2
- Target device model: iPhone Xs Max
- iOS version: 17.3.1

**Describe the bug**
I was able to set the location by these steps in CLI command
1. 
``` sudo python3 -m pymobiledevice3 remote start-tunnel --rsd HOST PORT ```
2. 
``` python -m pymobiledevice3 developer dvt simulate-location set --rsd HOST PORT -- LAT LON ```
3.
But got the errors while using these python codes to set the location

```python
from pymobiledevice3.services.dvt.instruments.location_simulation import LocationSimulation
from pymobiledevice3.lockdown import create_using_usbmux
from pymobiledevice3.services.dvt.dvt_secure_socket_proxy import DvtSecureSocketProxyService

# Create a LockdownClient instance
lockdown = create_using_usbmux()
print(lockdown)
# Use it to create a DVT instance
dvt = DvtSecureSocketProxyService(lockdown)
dvt.perform_handshake()
LocationSimulation(dvt).set(LAT, LON)
```

Thanks for helping

 **To Reproduce**
1. Connect device
2. Start tunnel ``` sudo python3 -m pymobiledevice3 remote start-tunnel ``` on macOS
3. Run python code

**Expected behavior**
The GPS location is set

**Logs**
```
Traceback (most recent call last):
  File "/Users/cyli/Documents/project/gps/test1.py", line 15, in <module>
    dvt = DvtSecureSocketProxyService(lockdown)
  File "/Users/cyli/miniconda3/envs/gps/lib/python3.9/site-packages/pymobiledevice3/services/dvt/dvt_secure_socket_proxy.py", line 24, in __init__
    super().__init__(lockdown, service_name, remove_ssl_context=remove_ssl_context)
  File "/Users/cyli/miniconda3/envs/gps/lib/python3.9/site-packages/pymobiledevice3/services/remote_server.py", line 362, in __init__
    super().__init__(lockdown, service_name, is_developer_service=is_developer_service)
  File "/Users/cyli/miniconda3/envs/gps/lib/python3.9/site-packages/pymobiledevice3/services/lockdown_service.py", line 20, in __init__
    service = start_service(service_name, include_escrow_bag=include_escrow_bag)
  File "/Users/cyli/miniconda3/envs/gps/lib/python3.9/site-packages/pymobiledevice3/lockdown_service_provider.py", line 41, in start_lockdown_developer_service
    return self.start_lockdown_service(name, include_escrow_bag=include_escrow_bag)
  File "/Users/cyli/miniconda3/envs/gps/lib/python3.9/site-packages/pymobiledevice3/lockdown.py", line 62, in _inner_reconnect_on_remote_close
    return f(*args, **kwargs)
  File "/Users/cyli/miniconda3/envs/gps/lib/python3.9/site-packages/pymobiledevice3/lockdown.py", line 492, in start_lockdown_service
    attr = self.get_service_connection_attributes(name, include_escrow_bag=include_escrow_bag)
  File "/Users/cyli/miniconda3/envs/gps/lib/python3.9/site-packages/pymobiledevice3/lockdown.py", line 482, in get_service_connection_attributes
    response = self._request('StartService', options)
  File "/Users/cyli/miniconda3/envs/gps/lib/python3.9/site-packages/pymobiledevice3/lockdown.py", line 570, in _request
    raise exception_errors.get(error, LockdownError)(error, self.identifier)
pymobiledevice3.exceptions.InvalidServiceError: InvalidService
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Since your device iOS version is 17.0, you cannot use usbmux to establish a DVT connection (unless iOS >= 17.4), so you must instead use the RSD protocol to establish it. Please read on: https://github.com/doronz88/pymobiledevice3/blob/master/misc/understanding_idevice_protocol_layers.md#remotexpc

```python
from pymobiledevice3.remote.remote_service_discovery import RemoteServiceDiscoveryService
from pymobiledevice3.services.dvt.instruments.location_simulation import LocationSimulation
from pymobiledevice3.services.dvt.dvt_secure_socket_proxy import DvtSecureSocketProxyService

# Assuming 
host = 'fdc3:16b1:5cac::1'
port = 52954
rsd = RemoteServiceDiscoveryService((host, port))
await rsd.connect()

# Use it to create a DVT instance
dvt = DvtSecureSocketProxyService(rsd)
dvt.perform_handshake()
LocationSimulation(dvt).set(LAT, LON)
```

**Comment by taipingeric** [comment]
Thanks you so much, it works !
