### ISSUE TITLE
Failing to create the TUN device on windows

### ISSUE THREAD

**Issue by mumuxiao722** [doronz88/pymobiledevice3#994]
**Test environment**
- Windows11
- iPhone15 Pro Max，iOS17.3.1
- Python 3.12.3
- pymobiledevice3 4.5.4
-

**Describe the bug**
I'm Chinese, I'm going to use the translator next, I used SideJITServe to try to create a tunnel, and then I got the following error.The program will try again and again and again.Uninstalling and reinstalling pymobiledevice3 doesn't work anyway.

**Logs**
WARNING:pymobiledevice3.tunneld:[mobdev2-00008130-001014AC0288001C-192.168.6.153] failed to start CoreDeviceTunnelProxy - skipping
WARNING:pymobiledevice3.tunneld:[mobdev2-00008130-001014AC0288001C-169.254.107.108] failed to start CoreDeviceTunnelProxy - skipping
WARNING:pymobiledevice3.tunneld:[mobdev2-00008130-001014AC0288001C-240e:369:9300:7000::21f%0] failed to start CoreDeviceTunnelProxy - skipping
WARNING:pymobiledevice3.tunneld:[mobdev2-00008130-001014AC0288001C-fe80::14f6:eb42:4e74:af2a%0] failed to start CoreDeviceTunnelProxy - skipping
WARNING:pymobiledevice3.tunneld:[mobdev2-00008130-001014AC0288001C-240e:369:9300:7000:1c02:acd0:db97:e979%0] failed to start CoreDeviceTunnelProxy - skipping
WARNING:pymobiledevice3.tunneld:[mobdev2-00008130-001014AC0288001C-fe80::11:6177:d4e3:6a65%9] failed to start CoreDeviceTunnelProxy - skipping
WARNING:pymobiledevice3.tunneld:[mobdev2-00008130-001014AC0288001C-fe80::e827:95ff:fe83:dcf7%18] failed to start CoreDeviceTunnelProxy - skipping
ERROR:pymobiledevice3.tunneld:got exception from start-tunnel-task-usb-fe80::c74f:6942:462:c7bc%18: Traceback (most recent call last):
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pymobiledevice3\tunneld.py", line 196, in start_tunnel_task
    async with start_tunnel(protocol_handler, protocol=protocol) as tun:
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 984, in start_tunnel
    async with start_tunnel_over_core_device(
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 968, in start_tunnel_over_core_device
    async with service_provider.start_quic_tunnel(
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 427, in start_quic_tunnel
    client.start_tunnel(handshake_response['clientParameters']['address'],
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 232, in start_tunnel
    super().start_tunnel(address, mtu)
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 177, in start_tunnel
    self.tun = TunTapDevice()
               ^^^^^^^^^^^^^^
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pytun_pmd3\wintun.py", line 206, in __init__
    raise PyWinTunException(f"Failed to create adapter. Last error: {last_error.value}")
pytun_pmd3.exceptions.PyWinTunException: Failed to create adapter. Last error: 0

ERROR:pymobiledevice3.tunneld:got exception from start-tunnel-task-wifi-192.168.6.153: Traceback (most recent call last):
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pymobiledevice3\tunneld.py", line 196, in start_tunnel_task
    async with start_tunnel(protocol_handler, protocol=protocol) as tun:
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 988, in start_tunnel
    async with start_tunnel_over_remotepairing(
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 951, in start_tunnel_over_remotepairing
    async with remote_pairing.start_quic_tunnel(
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 427, in start_quic_tunnel
    client.start_tunnel(handshake_response['clientParameters']['address'],
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 232, in start_tunnel
    super().start_tunnel(address, mtu)
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 177, in start_tunnel
    self.tun = TunTapDevice()
               ^^^^^^^^^^^^^^
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pytun_pmd3\wintun.py", line 206, in __init__
    raise PyWinTunException(f"Failed to create adapter. Last error: {last_error.value}")
pytun_pmd3.exceptions.PyWinTunException: Failed to create adapter. Last error: 0

ERROR:pymobiledevice3.tunneld:got exception from start-tunnel-task-wifi-169.254.107.108: Traceback (most recent call last):
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pymobiledevice3\tunneld.py", line 196, in start_tunnel_task
    async with start_tunnel(protocol_handler, protocol=protocol) as tun:
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 988, in start_tunnel
    async with start_tunnel_over_remotepairing(
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 951, in start_tunnel_over_remotepairing
    async with remote_pairing.start_quic_tunnel(
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 427, in start_quic_tunnel
    client.start_tunnel(handshake_response['clientParameters']['address'],
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 232, in start_tunnel
    super().start_tunnel(address, mtu)
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 177, in start_tunnel
    self.tun = TunTapDevice()
               ^^^^^^^^^^^^^^
  File "C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pytun_pmd3\wintun.py", line 206, in __init__
    raise PyWinTunException(f"Failed to create adapter. Last error: {last_error.value}")
pytun_pmd3.exceptions.PyWinTunException: Failed to create adapter. Last error: 0

C:\Users\zy349\anaconda3\envs\SideJITServer\Lib\site-packages\pymobiledevice3\utils.py:55: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()

**Comment by doronz88** [comment]
This isn't an error - your device just doesn't support CoreDeviceTunnelProxy which was added on 17.4. The server just keeps searching till you connect one that does.
The real error error is that the adapter could not be created. Did you start this process as administrator?

**Comment by mumuxiao722** [comment]
> This isn't an error - your device just doesn't support CoreDeviceTunnelProxy which was added on 17.4. The server just keeps searching till you connect one that does. The real error error is that the adapter could not be created. Did you start this process as administrator?

I run it in administrator mode.

**Comment by doronz88** [comment]
Does it occur also when trying tunneld directly from latest installation of pymobile?

**Comment by xiabeize114514** [comment]
> Does it occur also when trying tunneld directly from latest installation of pymobile?

My device doesn't support the sudo command, so I used python3 -m pymobiledevice3 remote tunneld, which outputs C:\Users\zy349\AppData\Local\Programs\Python\Python312\python3.exe: No module named pymobiledevice3

**Comment by mumuxiao722** [comment]
> Does it occur also when trying tunneld directly from latest installation of pymobile?

I deleted the whole conda environment and recreated it, using python3 -m pymobiledevice3 remote tunneld is fine, using SideJITserver is also fine, I guess it's a python problem, during which I renamed the python.exe to python3.exe and configured Path, and everything worked fine after testing again
